### ISSUE TITLE
Not using custom format for date and time

### ISSUE THREAD

**Issue by dobrin** [thundernest/quicktext#10]
This bug came with version 0.9.11.12. If you set a custom format for date or time in the settings of the operating system, Quicktext does not use that custom format, it uses the default format for the region.
I'm testing on Windows 10 Pro x64 with Thunderbird 52.8.0. In Control Panel, Region I have format "English (United States)" and a custom format for short date "yyyy-MM-dd".  Quicktext 0.9.11.12 and 0.9.12 do not use format "yyyy-MM -dd" for the [[DATE]] token instead they use the default format for "English (United States)" - "MM/dd/yyyy". Quicktext 0.9.11.7 uses my custom format "yyyy-MM-dd" for the [[DATE]] token.
Quicktext 0.9.11.7 uses the specified custom formats for date and time:
![quicktext 0 9 11 7](https://user-images.githubusercontent.com/1698710/40270893-bc50e75a-5b9d-11e8-9bed-ed829c1c4f61.png)
Quicktext 0,9,12 uses the default format for the selected region:
![quicktext 0 9 12](https://user-images.githubusercontent.com/1698710/40270902-ea56a73e-5b9d-11e8-9128-efc80471be2b.png)

**Comment by jobisoft** [comment]
There was a discussion about the time format. I had to change the "old" impl because it was deprecated/not working. The "new" method "Services.intl" however is only in TB60.

Discussion with Jörg starts here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1391020#c49

Would the "Services.int" version fix this? I will try .... later ....

**Comment by lieser** [comment]
I'm currently working on a version which will use the old `nsIScriptableDateFormat`, `Intl.DateTimeFormat` or the new `new Services.intl.DateTimeFormat` depending on the Thunderbird version used.

**Comment by lieser** [comment]
Could you please try out if this is fixed for you in the *quicktext-0.9.15-beta.xpi* version attached to https://bugzilla.mozilla.org/show_bug.cgi?id=1391020#c63?

**Comment by dobrin** [comment]
I tested quicktext-0.9.15-beta.xpi on the same machine (Windows 10 Pro x64 with Thunderbird 52.8.0).
Formats for date and time are get correctly from the operating system settings.

**Comment by jobisoft** [comment]
Thanks. I will send this version to final review than. This can be closed.
