### ISSUE TITLE
basic template isnt working - i am doing something wrong?

### ISSUE THREAD

**Issue by Janko85** [thundernest/quicktext#100]
Hey there,
i have Thunderbird 68.3 (32-bit) and Quicktext 2.7 and just started with it cause it looks realy realy very usefull. But i hit the ground at very beginning :

I just want to test simple Template, where i click the button and TEXT epears in email body.
So i did, and it didnt work. so i checked tutorial, where was basicly wrote the same but it didnt work.

What Happends: i click the "button" and nothing happen. i attach the screenshot of the template setting. Anyone can help me out what i did wrong? thanks a lot!
![Clipboard01](https://user-images.githubusercontent.com/58506156/70125551-4e5f2900-1677-11ea-960d-83a5ad142619.jpg)

I mean, it looks like there is nothing you can make wrong, right? But it still didnt work for me :(

**Comment by jobisoft** [comment]
v2.7 seems broken. I removed it, please unintall and install v2.6

**Comment by jobisoft** [comment]
[quicktext_2.7.1.xpi](https://github.com/thundernest/quicktext/files/3921361/quicktext.zip)

Can you retry with this version?

**Comment by Janko85** [comment]
i removed 2.7 and put back 2.6 and it works perfectly! thanks very much

**Comment by szapeti** [comment]
I had the same problem.

Can confirm after installing version 2.7.1 it works again.

Thanks

**Comment by repair-frank** [comment]
2.7.1. works perfect! Thanks
