### ISSUE TITLE
tab added for autocompletion

### ISSUE THREAD

**Issue by floeff** [thundernest/quicktext#101]
Since a few versions, when using Tab for autocompletion, that Tab is added to the text.
A "Yours truly," becomes "Yours truly,    "

**Comment by jobisoft** [comment]
I cannot confirm this on Windows with Quicktext v2.7.1, what OS are you on?

**Comment by floeff** [comment]
I'm on mac OS 10.15.1 (Catalina). The problem was there some months ago, then disappeared after a Quicktext update and now is back for 2-3 weeks or so

**Comment by jobisoft** [comment]
Could you identify, which of the older versions have that flaw, and which not?
https://addons.thunderbird.net/de/thunderbird/addon/quicktext/versions/

**Comment by floeff** [comment]
2.3 works, 2.5 works (didn't test 2.4), 2.6 is broken

**Comment by jobisoft** [comment]
can you verify with the latest release?

**Comment by floeff** [comment]
Seems to work again now, thanks so much! ;)
