### ISSUE TITLE
Does not work with TB68.3

### ISSUE THREAD

**Issue by biva** [thundernest/quicktext#102]
My QuickText doesn't work anymore :( 
- Using Keywords (+tab to activate a keyword) removes the keyword but does not include the desired text
- Right click Quictext menu: does not include anything

Does anybody else meet the same issue?

TB version: 68.3.0 (but I had also the issue with the previous version, I think it was 68.2.2)

**Comment by jobisoft** [comment]
update your addons, a fixed version has been released already.

**Comment by Heliophob** [comment]
Hello John, Hello biva, 

I also had the same problem. Why is not the new version being imported automatically? It was necessary to uninstall QT and then reinstall it. But that helped.

Best Regards

**Comment by jobisoft** [comment]
Because Thunderbird only checks for updates once a day and he checked this morning and gave you the broken v2.7. You would have gotten the fixed version v2.8 tomorrow automatically.

But there is also the option to force him to update via the gear menu in the AddOn Manager.

**Comment by Heliophob** [comment]
Understand, found, THX! 

For posterity:
![update](https://user-images.githubusercontent.com/46809800/70170867-df60ef00-16cd-11ea-8b00-98bae2293237.png)

**Comment by biva** [comment]
What a shame, sorry for disturbing you for such a mistake from my side. I updated TB and did not think about updating the extension. Shame on me! I close this issue quickly :)

**Comment by jobisoft** [comment]
No need to be sorry, this was a real issue. I released a broken version yesterday.
