### ISSUE TITLE
Keyword expansion with Return key not working anymore

### ISSUE THREAD

**Issue by schoettl** [thundernest/quicktext#103]
Since about 2 days, the keyboard shortcut `Return` does not expand my keywords anymore.

- Thunderbird 68.3.0 on Arch Linux
- Quicktext 2.8 (2019-12-04)

If I set the keyboard shortcut for keyword expansion to `Tab` and `Space` it works! Only `Return` does not work anymore.

**Comment by jobisoft** [comment]
Why is linux always breaking things. :-(

**Comment by jobisoft** [comment]
Please uninstall your current quicktext, restart TB, close the AddOn Mangager after TB restarted, open the AddOn Manager again and install the following version via the gear menu:

[quicktext.xpi](https://github.com/thundernest/quicktext/files/3931801/quicktext.zip)

This version logs the key pressed in the editor window to the console. What do you get?

```
gQuicktext.keywordKey: <Enter>, e.code: <Tab>
gQuicktext.keywordKey: <Enter>, e.code: <Enter>
```

**Comment by schoettl** [comment]
Thank you! Oh, that is really annoying... Thunderbird on Linux is crazy:

I did not mention, that I have a changed keyboard layout: the `\` key (US keyboard) is assigned as my Enter key in `~/.Xmodmap`.

My new Enter key always works normal except that Thunderbird seems to report it as

```
gQuicktext.keywordKey: <Tab>, e.code: <Backslash>
```

That is probably something that has to be fixed in Thunderbird (or the GUI framework they are using). But why does the bug appear now after you updated the add-on?

**Comment by jobisoft** [comment]
I switched from the deprecated e.keyCode to e.Code:
https://developer.mozilla.org/de/docs/Web/API/KeyboardEvent/keyCode

keyCode used some numbers, code uses names.

I suggest you file a bug with mozilla to fix this. There is is nothing I can do. Can I close this?

**Comment by schoettl** [comment]
OK, thanks for looking into it!
