### ISSUE TITLE
Script Support

### ISSUE THREAD

**Issue by kelzared** [thundernest/quicktext#104]
Hey, is it somehow possible with html or javascript to retrieve a text file from the pc or network and then insert the text into the signature? I tested so many scripts unfortunately, no one works.

I would be very happy if someone could help me. :O

greetings

**Comment by jobisoft** [comment]
https://github.com/thundernest/quicktext/wiki/List-of-all-supported-tags#file

you do not need to write a script for that, the FILE or URL tag do exactly that.

**Comment by kelzared** [comment]
unfortunately I need a script, because I want to manage more signatures easier, 5 computers should retrieve the same text, and if something needs to be changed, I only edit 1 file on a network server and all 5 computers have the same text immediately.

**Comment by kelzared** [comment]
oh sorry i see its possible... its possible to get netzwerkserver ?

**Comment by jobisoft** [comment]
If you change the file (local, SMB or http) than all 5 computers will use the new file next time the template is used. It is not a static include.

**Comment by jobisoft** [comment]
I assume Netwerkserver = Netzwerkfreigabe = SMB. Use FILE for that.

**Comment by kelzared** [comment]
thank u =) sry i didnt try this :)

**Comment by jobisoft** [comment]
close this issue, if it works.
