### ISSUE TITLE
Template text area height

### ISSUE THREAD

**Issue by IgitBuh** [thundernest/quicktext#106]
I'm currently settings up several long templates and I'm wondering why the text area for templates has a fixed height. Even if I resize the preferences dialog it adjusts to the full width, but not to the full available height. The result is a lot of empty space between the text area and the options below it. This makes it quite difficult working with larger templates.

Could the text area please receive an auto-height to use the available space?

**Comment by jobisoft** [comment]
Not so easy, XUL is being removed from Mozilla and I have no idea how to do it with plain textbox (which has rows and not a height)

**Comment by IgitBuh** [comment]
Please add this CSS to the textarea:
`style="height: 100vh"`

I've checked with the developer tools inspector and it works just fine.

**Comment by jobisoft** [comment]
will do that soon, thanks for the tip. If you could do a PR, that would be faster :-)

**Comment by IgitBuh** [comment]
Okay, done... Please see if it works for you too before merging it to the main branch.

**Comment by jobisoft** [comment]
Thanks for your contribution, unfortunatly it does not work for me. It expands the window to the full screen height, which is actually correct, as "vh" is the viewport height. Got to undo the merge.

**Comment by IgitBuh** [comment]
I had checked this modification with the developer tools inspector and it worked fine there. Sorry to hear that a direct change in the project has a different result for some reason.
I'll do some research on how to correctly test Thunderbird add-ons. I need to do this for other (functional) modifications anyway. Hopefully there's an easy way (if you can point me into the right direction, I'd appreciate it).

**Comment by jobisoft** [comment]
Sure, you have your own fork of this addon and you can simply zip the entire thing (with your modifications) together and install it in thunderbird. XPI files are just renamed zip files. Just unzip the original XPI to see how it works.

You even do not need to name it XPI, you can install the file with a zip extensions as well.

The only thing: You need to uninstall the current version, restart, close addon manager, re-open addon manager and then install the new file. If you simply "install over" it could be that the old (cached) version is still used and your changes will have no effect.

**Comment by IgitBuh** [comment]
> The only thing: You need to uninstall the current version, restart, close addon manager, re-open addon manager and then install the new file. If you simply "install over" it could be that the old (cached) version is still used and your changes will have no effect.

That's a very valuable hint. Thanks. Although this makes it more complicated to test scenarios where pre-defined templates are required, because they need to be added manually with every code change!?
Additionally, it seems, it's probably better to develop and test in a VM.

**Comment by jobisoft** [comment]
templates are not stored in the addon itself, but in your profile. they will be there as before, you just exchanged the addon.

I do not use a VM. I have a dedicated development profile in Thudnerbird, that is all.

**Comment by jobisoft** [comment]
Can you checkout the pre release? 

You need to uninstall your current version, restart, and then install this version:
[quicktext.xpi](https://github.com/thundernest/quicktext/files/4124070/quicktext.zip)

**Comment by SamuelPlentz** [comment]
> The only thing: You need to uninstall the current version, restart, close addon manager, re-open addon manager and then install the new file. If you simply "install over" it could be that the old (cached) version is still used and your changes will have no effect.

@IgitBuh @jobisoft: For me a combination of `nglayout.debug.disable_xul_cache` and `-purgecaches` helped:
https://developer.thunderbird.net/add-ons/tips-and-tricks

Install + restart is enough now. Will move this to the wiki later.

**Comment by jobisoft** [comment]
2.12 is the current official release and includes this patch, no need to manually install it. Updates from addons.thunderbird.net do not have this issue.

@SamuelPlentz : If I ever upload pre-releases again, I will refer to the official Thunderbird doc:
https://developer.thunderbird.net/add-ons/tips-and-tricks#forcing-modified-xul-files-and-javascript-to-reload

I do not think we need this info in the quicktext wiki.

**Comment by SamuelPlentz** [comment]
Sorry for hijacking this solved thread.
My intention was for someone who wants to contribute to Quicktext to create a page with information's how to test changed versions without messing with version numbers bypassing thunderbirds caching system. You still disagree there should be a wiki page?

**Comment by jobisoft** [comment]
I do not think we should copy information from the official thunderbird doc and generate redundancy which needs to be updated whenever the doc changed. If you want, you can add a general info for developers to turn to developer.thunderbird.net if they want to know details about add-on coding.

But the main intention of the wiki is to help users.
