### ISSUE TITLE
Option for HTML templates to automatically replace line-breaks with <br>

### ISSUE THREAD

**Issue by IgitBuh** [thundernest/quicktext#107]
It would be nice to have an option that would make it unnecessary to define line breaks with `<br>`, `<p>` or `<div>`. If line breaks would be automatically converted to `<br>` tags when inserting, then an HTML template would be much clearer, because you would only use tags for the required formatting.

This option could be a checkbox together with the other options at the bottom of the template dialog:
`[  ] Replace line breaks automatically with <br>`

**Comment by jobisoft** [comment]
That breaks the html standard. Will not do.

**Comment by IgitBuh** [comment]
How is this breaking the html standard?

**Comment by IgitBuh** [comment]
Maybe I expressed myself misleadingly.

To make this more clear: If someone chooses "HTML" instead of "Text" for a template, then because they want to format some portion of the text.

Right now, one would need to write this:
```
Hi,<br>
<br>
This is <b>very</b> important.<br>
<br>
Bye
```

With my suggested option it would become this:
```
Hi,

This is <b>very</b> important.

Bye
```

Notice, this is optional, so nobody _has_ to use it. However, I believe that most users who use the HTML option do this to format some portions of the text, not to format each and every line-break and paragraph.

**Comment by jobisoft** [comment]
I would rather add markdown support (`*italic*`, `_underline_` etc.) than working on an extra option for a  single html tag. Your suggestion does indicate a need (simple styling), but the implementation must be broader. 

Wanna help by doing research on simple markdown to html conversion libs in javascript for client side implementation which are free to use?

**Comment by IgitBuh** [comment]
Hm, that's actually not what I had in mind. My code was the simplest example I could think of. In reality, some of my templates contain links, lists, images, etc.

I am really not so sure about your idea. There is already a markup support with HTML, so why add markdown as well? I'm glad to have the possibility to format the text with all kinds of HTML tags nicely, but adding `<br>` for every line-break results in a cluttered, less readable code. 

My suggestion is basically the simple `ln2br()` function from PHP, which could be something like this in JS:
https://stackoverflow.com/questions/7467840/nl2br-equivalent-in-javascript

**Comment by SamuelPlentz** [comment]
For the original request one could use a script `HTMLBreaks` like this:
``` Javascript
let text = mVariables[0];
text = text.replace(/\n/g, "<br>");
return text;
```

Use it inline like this:
```
[[SCRIPT=HTMLBreaks|Hi,

This is <b>very</b> important.

Bye]]
```

or by converting another template named `Templatename` in a folder named `Foldername`:
```
[[SCRIPT=HTMLBreaks|[[TEXT=Foldername|Templatename]]]]
```

**Comment by jobisoft** [comment]
I still oppose tempering with html. Either you have an HTML template or not. Once the template is inserted, you do not see the br tags, so this is only affecting the composition of the template itself.
