### ISSUE TITLE
Do not add image src tag, if added in TEXT mode or outside image tag

### ISSUE THREAD

**Issue by jobisoft** [thundernest/quicktext#110]

**Comment by SamuelPlentz** [comment]
Wouldn't it be a good idea to add another parameter to the IMAGE tag?
Like `[[IMAGE=path|type]]` where `type` could be `normal` (default) or `source only` where `normal` would resolve to: `<img src="cid:part1.[...]">` and `source only` would resolve only to the src part like `cid:part1.[...]`. So experts can adjust it to add alt text or size, but normal users can just drag it in.

Normal users do not know about `<img>`-stuff.

**Comment by jobisoft** [comment]
I agree, second parameter can now be "src" or "tag" (or whatever) and only if it is "src", the raw src attribute will be inserted, otherwise the entire image tag. Default is "tag".

Image tag is ignored now in TEXT mode.

**Comment by SamuelPlentz** [comment]
Nicely done.
Updated the wiki: https://github.com/thundernest/quicktext/wiki/List-of-all-supported-tags
