### ISSUE TITLE
TB 68.3.1 breaks Quicktext

### ISSUE THREAD

**Issue by arztnh** [thundernest/quicktext#111]
Subject says it all... is a fix pending shortly?

**Comment by jobisoft** [comment]
I do not think that is true. Maybe update your addons?

And frankly, that is the worst error description i have ever seen.

**Comment by arztnh** [comment]
My installation is set to automatically update addons - that's what
    does not appear to be working. I did a manual update and caught the
    update which is dated today.
    
    Noam
    
    On 12/24/2019 12:16 AM, John Bieling
      wrote:
    
    
      
      I do not think that is true. Maybe update your addons?
      And frankly, that is the worst error description i have ever
        seen.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thundernest/quicktext/issues/111?email_source=notifications\u0026email_token=AKUUUZ5O5UISAFPCIKA3ZBLQ2HAMLA5CNFSM4J6ZC4KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHSYJ4Q#issuecomment-568689906",
"url": "https://github.com/thundernest/quicktext/issues/111?email_source=notifications\u0026email_token=AKUUUZ5O5UISAFPCIKA3ZBLQ2HAMLA5CNFSM4J6ZC4KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHSYJ4Q#issuecomment-568689906",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jobisoft** [comment]
The latest version is from 4th of dezember, not from today.
https://addons.thunderbird.net/de/thunderbird/addon/quicktext/versions/

The addons-do-not-update issue is listed in the release notes of Thunderbird 68. It is not a issue of quicktext.
