### ISSUE TITLE
Incompatible with Thunderbird 68.3.1 (32-bit)

### ISSUE THREAD

**Issue by Perkin5** [thundernest/quicktext#113]
I have just auto-updated to the above version of TBird and now find that Quicktext is disabled due to incompatibility. I use this add-on all the time so would be grateful for any assurance that it will soon be updated to make it compatible.

**Comment by jobisoft** [comment]
Please update your Add-Ons. For some reason TB is not doing that doing upgrade from 60 to 68. Quicktext has been updated long ago to work with TB68.

**Comment by Perkin5** [comment]
Thanks for that advice - it worked!
