### ISSUE TITLE
Get the date (sent) from the original message

### ISSUE THREAD

**Issue by wehkah** [thundernest/quicktext#114]
Hello,

I've looked at the script wiki, and I wonder if it was possible to use a script to extract the date that the replied message was written, so that this date can be inserted into a customized citation intro. (Windows style)

I know I can use [[ORGHEADER=Date|\n]], but that string is not very nice to look at as an intro to a cited message. If a script could extract the date and transform it into a nicer form, maybe even taking into account the language being used, that would be the icing! :)

**Comment by jobisoft** [comment]
Use this script:

```
let dateobj = new Date(Date.parse(this.mQuicktext.get_orgheader(["DATE"])));
let options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
return dateobj.toLocaleDateString('de-DE', options);
```

and adapt what parts of the date object you actually want to use. Instead of using the localeDateString, you may use `getYear()` etc and put the returned string together as you want.

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by wehkah** [comment]
Thank you very much! That works like a charm. :)

I managed to extract the sending time as well, now I am trying to extract the timezone from the original message, which seems a bit above my capabilities. I tried this:

```
let dateobj = new Date(Date.parse(this.mQuicktext.get_orgheader(["DATE"])));
let zeitzone = dateobj.getTimezoneOffset();

let options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',hour:'numeric',minute:'numeric'};

return dateobj.toLocaleDateString('de-DE', options) + ' ' + zeitzone;
```
But that one only returns the difference between my system and UTC. But I want the timezone that the original message was sent from. 

Could you tell me how to do this? Is this possible at all, or is there no function for this?

**Comment by jobisoft** [comment]
You can request this via the **timeZoneName** member of the options object:

```
let options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: 'numeric', timeZoneName: 'short'};
```

Feel free to support QuickText by a donation.
https://www.paypal.me/johnbieling

**Comment by wehkah** [comment]
I thought so, too, but that does not work as expected: timeZoneName always returns the local time zone, the one my system is using, which is always "MEZ -60". It does not return the time zone that the original message was sent from. You can see this if you compare [[ORGHEADER=Date]] to the output of timeZoneName when you do a reply using that script.

I searched for the term "timezone" at developer.mozilla.org, and every result I found was referring to the local time zone. It's possible that there is no way of retrieving the time zone from the original message at all. :(

**Comment by jobisoft** [comment]
That is tricky. The original timezone is encoded in the string you get from the header:
```
Sun, 12 Jan 2020 02:13:01 -0500
```
Which would be Eastern Time.

As soon as you parse that, it is converted into a dateobject, which is a "point in time" and can be expressed in any timezone but has no inherent timezone information (as the timezone is only a viewport for that "point in time"). Finally toLocaleDateString() is displaying that "point in time" in the timezone of the displaying system. This is a good practice, as the local timezone will allow the local user to graps better, when the email was send. Otherwise he would need to manually convert the abouve time from Eastern Time to his own manually. Sending that information back to the sender is of course killing that idea. 

How do you actually want the above Eastern Time date string to be returned by your script?

**Comment by wehkah** [comment]
I would like to get the time zone information into the reply intro: 

```
----Original message----
From: John Doe
Date: Sunday, January 11, 2020, 17:05 -0800
Subject: Something funny
```
But if that is not possible or if it is too complicated to achieve, I can live without it.

**Comment by jobisoft** [comment]
I think you should just keep the date value as you get it from the server, as it comes in the correct form for the sender, to whom you will be sending it back.
