### ISSUE TITLE
Replacement of [[CURSOR]] tag not working if ENTER is used to activate keywords.

### ISSUE THREAD

**Issue by richbook** [thundernest/quicktext#119]
Hi there,

I just updated to Thuderbird 68.4.1, and now I am experiencing issues with the cursor position in quicktext. Most of the times, it appears as [[CURSOR]] in my email text when I use a template containing it. I cannot see a pattern, but sometimes it worked correctly for a template I just created, or for an existing one, reinserting the "[[CURSOR]]" element.

I also uninstalled and reinstalled quicktext, which did not help.

Who can help?

Thank you
Richard

**Comment by jobisoft** [comment]
What version of quicktext?

**Comment by richbook** [comment]
2.8, I checked for updates.

**Comment by jobisoft** [comment]
Can you check with this version?
[quicktext:2.9.xpi](https://github.com/thundernest/quicktext/files/4064886/quicktext.zip)

* uninstall the curret one, 
* restart, 
* after restart close add-on-manager, 
* re-open add-on-manager, 
* install xpi via gear icon, 
* restart

**Comment by richbook** [comment]
Dear John,

[[CURSOR]]

Best regards,
Richard

Thank you for your help. I appreciate it! Unfortunately though, it still looks like this. (I started typing where the cursor was.)

This is my template:

Dear [[TO=firstname]],

[[CURSOR]]

[[TEXT=Grüße|Best regards]]

**Comment by jobisoft** [comment]
Then you need to open the debug console (Tools -> Developer Tools -> Error Console) and look for errors when inserting a template. You should also see debug entries like 

```
CURSOR LOG failedSearchAttempts : 1
```

What other errors do you see?

For finding the root cause, can you disable all other addons to make sure it is not caused by some 
other add-on?

**Comment by richbook** [comment]
Yes, it keeps counting in this line (in this example: 2)
CURSOR LOG Failed to find CURSOR tag! 2 quicktext.js:616:15

I disabled all the other add-ons - no change.

There is one more quicktext error in the debug console (or maybe more, and I cannot see they are related to quicktext):
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFile.initWithPath]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://quicktext/content/modules/wzQuicktext.jsm :: loadSettings :: line 262"  data: no] wzQuicktext.jsm:262:18
    loadSettings chrome://quicktext/content/modules/wzQuicktext.jsm:262
    <anonym> chrome://quicktext/content/main.js:11
    loadScript resource:///modules/Overlays.jsm:573
    load resource:///modules/Overlays.jsm:231
    load resource:///modules/Overlays.jsm:48
    registerNonBootstrapped chrome://messenger/content/parent/ext-legacy.js:242
    forEach self-hosted:266
    registerNonBootstrapped chrome://messenger/content/parent/ext-legacy.js:236
    InterpretGeneratorResume self-hosted:1284
    AsyncFunctionNext self-hosted:839

**Comment by jobisoft** [comment]
I have no idea, he seems to miss it, even though it is right there.

This version has an increased log level (it should tell you how often he tried to find the tag, before he aborts) and it retries more often.

[quicktext.xpi](https://github.com/thundernest/quicktext/files/4065178/quicktext.zip)

What do you get in the log?

**Comment by richbook** [comment]
CURSOR LOG failedSearchAttempts : 100 quicktext.js:616:15
CURSOR LOG Failed to find CURSOR tag! quicktext.js:617:15

​I guess, that is the maximum.

**Comment by richbook** [comment]
John, I am sorry I did not notice before: I always use shortcuts in order to insert a quicktext template. Only when I created a new one (as I said in my very first post) I did not define a shortcut and clicked on it. And there we go: The cursor position tool works if I click on my templates. And it does not for shortcuts. (It used to, though, until yesterday, which means until Thunderbird 68.4.1)

Any ideas?

**Comment by jobisoft** [comment]
What are your QT settings? Can have a screenshot? What is the shortcut for the template which is failing?

**Comment by richbook** [comment]
Thank you for the hint on settings. Here are some new findings: it works for the space bar and the tab key, but not for the enter key (which was set to activate keywords).
I will change my settings to the tab key now.

My shortcut (keyword) for the Dear... template e.g. is just "d".

I could provide you with a screenshot, but what exactly do you want to see?

**Comment by jobisoft** [comment]
Ah ok, so you are not using the "keyboard shortcut" but an "activation keyword". And it fails with ENTER but works with all the other options (Tab, Space and F-Keys)?

No need for additional screenshoots than.

**Comment by jobisoft** [comment]
Try this:
[quicktext.xpi](https://github.com/thundernest/quicktext/files/4065743/quicktext.zip)

**Comment by richbook** [comment]
yes, sorry for not phrasing his correctly, my version is in German, so I did not know the corresponding English terminology. I will try your new version tomorrow. Thank you very much!

**Comment by richbook** [comment]
This version works with ENTER again, thank you very much!
> 
> Try this:
> [quicktext.xpi](https://github.com/thundernest/quicktext/files/4065743/quicktext.zip)
