### ISSUE TITLE
Feature Request: Add a fallback to firstname for the nickname variable

### ISSUE THREAD

**Issue by SamuelPlentz** [thundernest/quicktext#122]
Usually I use the firstname when addressing people I know well in the salutation, but close friends of mine have a nickname I use. I want to use quicktext with only one variable for both cases.

I already use a modified by me version of quicktext, that has this feature and wanted to share the code for 2 reasons. A) There might be others interested in this feature. B) Quicktext gets updated really often recently and I don't want to merge in my changes each time.

This is my attempt to create a nickname variable that has the firstname as fallback. I am not very familiar with javascript, there should be an easier way to copy a variable than copying char by char, but hey this works. ;-) Feel free to adjust.

File: chrome\content\modules\wzQuicktextVar.jsm
```
  get_to: function(aVariables)
  {
    var data = this.process_to(aVariables);


// ### BEGIN OF NEW: use name if nickname is not available

    if(aVariables[0]=='nickname'){
      if(typeof data['nickname']=='undefined'){
        data['nickname']=[];        
      }
      for (var i = 0; i < data['firstname'].length; i++){
        if(typeof data['nickname'][i]=='undefined'){
          data['nickname'][i]=data['firstname'][i]
        }
      }
    }

// ### END OF NEW: use name if nickname is not available


    if (typeof data[aVariables[0]] != 'undefined')
    {

      if (aVariables.length < 2)
        aVariables[1] = ", ";

      return data[aVariables[0]].join(aVariables[1].replace(/\\n/g, "\n").replace(/\\t/g, "\t"));

    }
    else
      return "";
  }
```

**Comment by SamuelPlentz** [comment]
Another solution could be a variable like "nick_firstname" or similar.

**Comment by jobisoft** [comment]
This is too special for general impl. but can be solved with a script. Compare my script given in #123.

**Comment by SamuelPlentz** [comment]
Thanks a lot for your hint with a script!

IMO this is not too special for general implementation:
If anyone wants to use the nickname variable, he is limited on it:
- He usually has not a nickname for all of his contacts. As an ugly workaround he could fill the missing nicknames with the firstnames.
- When not doing so, he is only able to use this template on persons with a nickname. He can't adress a mixed group or a group with firstnames only.

Anyone that wants to use nicknames faces this problems. But I don't want to start an open/close war here. I am happy now.

Came up with this script for others that are interested:
```
var data = this.mQuicktext.process_to(mVariables);

// use name if nickname is not available
if(mVariables[0] == 'nickname') {
  if(typeof data['nickname'] == 'undefined') {
    data['nickname'] = [];        
  }
  for(var i = 0; i < data['firstname'].length; i++) {
    if(typeof data['nickname'][i] == 'undefined') {
      data['nickname'][i] = data['firstname'][i];
    }
  }
}

if(typeof data[mVariables[0]] != 'undefined') {

  if(mVariables.length < 2) mVariables[1] = ", ";

  return data[mVariables[0]].join(mVariables[1].replace(/\\n/g, "\n").replace(/\\t/g, "\t"));

} else return "";
```

**Comment by jobisoft** [comment]
The idea of the script support is that users can add whatever feature they need. I do not know where to draw the line between "general interest" and "too special". If I start adding these I fell like it is going to never stop.

How about this: We start a new section in the wiki with a list of usefull scripts, where this script can be added. How does that sound?

**Comment by SamuelPlentz** [comment]
Would be a nice idea to have a script showroom in the wiki.
Useful scripts there could be considered to implement them direct into quicktext.

**Comment by SamuelPlentz** [comment]
Started a wiki page about this here. Feel free to improve the english (as I am German)
https://github.com/thundernest/quicktext/wiki/Script-showcase

**Comment by jobisoft** [comment]
Thanks, I reworked it. I will add a link from within quicktext to that list of scripts.

**Comment by jobisoft** [comment]
Reopen as reminder to add button into QT to link to community scripts...

**Comment by jobisoft** [comment]
Implemented.

**Comment by SamuelPlentz** [comment]
FYI: Searched the issues for the word "script" and inspected the scripts posted here. Not as much as I thought, I added CustomForwardHeader from them. I also added GoodMorning. Feel free to improve the english.

Thanks a lot for your work.
