### ISSUE TITLE
Feature Request: Add a "final separator" to the TO-tag

### ISSUE THREAD

**Issue by SamuelPlentz** [thundernest/quicktext#123]
Currently the TO-tag is defined like this: `[[TO=type|separator]]`
That means: `Hello [[TO=firstname|, ]]`
resolves to: `Hello Titus, Mathilda, Justus, Peter, Bob`

I want to extend the TO-tag definition like this: `[[TO=type|separator|final separator]]`
That means: `Hello [[TO=firstname|, | & ]]`
resolves to: `Hello Titus, Mathilda, Justus, Peter & Bob`

Of course like now one or both separators can be omitted.

I already use a modified by me version of quicktext, that has this feature and wanted to share the code for 2 reasons. A) There might be others interested in this feature. B) Quicktext gets updated really often recently and I don't want to merge in my changes each time.

This is my attempt to create a final separator in the TO-tag. I am not very familiar with javascript, feel free to adjust.

File: chrome\content\modules\wzQuicktextVar.jsm
```
  get_to: function(aVariables)
  {
    var data = this.process_to(aVariables);

    if (typeof data[aVariables[0]] != 'undefined')
    {


// ### BEGIN OF DELETE: final separator
/*
      if (aVariables.length < 2)
        aVariables[1] = ", ";

      return data[aVariables[0]].join(aVariables[1].replace(/\\n/g, "\n").replace(/\\t/g, "\t"));
*/
// ### END OF DELETE: final separator

// ### BEGIN OF NEW: final separator
      if (aVariables.length < 2){
        aVariables[1] = ", ";
        aVariables[2] = ", ";
      }
      if (aVariables.length < 3)
        aVariables[2] = aVariables[1];

      var result="";  // NEW: there are 2 kinds of separators: [Item1][S1][Item2][S1][Item3][S1][Item 4][S2][Item5]
      for (var i = 0; i < data[aVariables[0]].length; i++){
        if (i==0) {
          result=result+data[aVariables[0]][i];
        } else if (i+1==data[aVariables[0]].length) {
          result=result+aVariables[2].replace(/\\n/g, "\n").replace(/\\t/g, "\t")+data[aVariables[0]][i];
        } else {
          result=result+aVariables[1].replace(/\\n/g, "\n").replace(/\\t/g, "\t")+data[aVariables[0]][i];
        }
      }
      return result;    
// ### END OF NEW: final separator


    }
    else
      return "";
  }
```

**Comment by SamuelPlentz** [comment]
When this gets introduced the manual has to be updated.
I see this site, don't know if other places are affected:
https://github.com/thundernest/quicktext/wiki/List-of-all-supported-tags

**Comment by jobisoft** [comment]
This does look like being of general interest. But I cannot give you any guarantee or ETA.

To fix your patching issue: You could convert this to a script and use your own [[SCRIPT=MyTo|firstname]] instead of [[TO=firstname]]. No need to patch QuickText.

```javascript
let type = this.mVariables[0];
let otherSep = ", ";
let lastSep = " & ";

let entries = this.mQuicktext.get_to([type,"\n"]).split("\n");
let last = entries.pop();

let all = [];
if (entries.length > 0) all.push(entries.join(otherSep));
all.push(last);

return all.join(lastSep);
```
Works as you described with vanilla QuickText.

**Comment by SamuelPlentz** [comment]
Thanks a lot for this script and the hint to use scripts.

**Comment by jobisoft** [comment]
Implemented:
https://github.com/thundernest/quicktext/commit/28ecd1dee7689bc5e0b230faa671bcb85a7963e5

**Comment by SamuelPlentz** [comment]
Thanks a lot for implementing. Added the new possibility in the wiki:
https://github.com/thundernest/quicktext/wiki/List-of-all-supported-tags/_compare/0a5dcb0428938a5160af71a44c7ef4976c4c9ff2...f6a809be8a89fb11324d06422f5d8bcf65f0df43
