### ISSUE TITLE
Feature request: move the cursor after inserting template text

### ISSUE THREAD

**Issue by abdullahkhalids** [thundernest/quicktext#124]
I have templates where the content I have to type in, is in the middle of the template text. It would be nice if there was a script to move the cursor to some absolute or relative location within the template text. 

This way, one does not have to click with the mouse in the right spot. after inserting template. Thanks.

**Comment by jobisoft** [comment]
[[CURSOR]]

is what you seek, isn't it?

**Comment by abdullahkhalids** [comment]
Thanks. This was not documented in the wiki, which is why I wasted your time. I have made an edit to the wiki.

**Comment by jobisoft** [comment]
Perfect. Thanks.
