### ISSUE TITLE
can't increase window size

### ISSUE THREAD

**Issue by billibooy** [thundernest/quicktext#125]
Good day,

for some reason the Quciktext window is extremely small after a restart. I can't find any way to increase size. neither windows key + arrow key. Size tab is greyed out and the courser won't change to the resize option...

![thunderbird_vwurasBnXe](https://user-images.githubusercontent.com/60509620/73539409-a030ef00-442d-11ea-8efd-9ea1ba690320.png)

**Comment by jobisoft** [comment]
What OS? What version of Quicktext?

You cannot resize the window at the bottom right corner?

**Comment by jobisoft** [comment]
Do you also have the same issue, if you open the quicktext window using this menu option:

![grafik](https://user-images.githubusercontent.com/5830621/73543077-6b756580-4436-11ea-9a4d-bdf6537b6764.png)

I can confirm, that I have this isssue, wehn I use the addons options menu entry:

![grafik](https://user-images.githubusercontent.com/5830621/73543126-92cc3280-4436-11ea-8d9a-ee3207198016.png)

**Comment by jobisoft** [comment]
i just release quicktext 2.12, hoping this fixes your issue. Can you confirm?

**Comment by jobisoft** [comment]
@billibooy : Can you give some feedback?

**Comment by lt-codex** [comment]
I am on QuickText version 2.12 and Thunderbird 68.4.2. 

I've tried removing the QuickText and reinstalling it. This issue began 02/01/2020 with the QuickText window's height reduced in size slightly and continuously got smaller upon reopening the app and is now a the point where the text is no longer visible editable window. I'm also unable to move the window around the desktop.

**Comment by jobisoft** [comment]
Can I have a screenshoot of the window?

**Comment by jobisoft** [comment]
You are all on MacOS? Which version?
You all got Quicktext 2.12?
And you cannot resize the window?
Could you resize the window before?

@Letterus : This is the issue I was talking about.

**Comment by Letterus** [comment]
I'm on macOS 10.14.6, using TB 68.4.2 and a freshly installed QuickText version 2.12.

The "AddOn Einstellungen" sub menu is not working for me (does not display anything), but there is a meny entry "QuickText" within the "Extras" menu. The window behaviour works as expected.

**Comment by jobisoft** [comment]
@Letterus : With  "The window behaviour works as expected." you mean you can resize it by dragging its corner?

OT: When you say the "AddOn Einstellungen" sub menu is not doing anything, is this also true for the TbSync entry in that menu? It is using the same code (or at least I think so)...

**Comment by Letterus** [comment]
@jobisoft Yes. I can resize it, move it and when I reopen it its size is remembered correctly.

OT: Yes, I've got several plugins installed. The menu is not shown for any of these.

![Bildschirmfoto 2020-02-03 um 09 40 20](https://user-images.githubusercontent.com/2911501/73637765-516f9900-4669-11ea-9b00-86dfaf793832.png)

**Comment by billibooy** [comment]
sorry I only have access to this site and program while I am at work.

I am using Windows 10 Pro
Thunderbird version: 68.4.2 (32 bit)
Quicktext version: 2.11

It is currently working for me again but there is an Update in the queue. 
I updated it and now it is on version 2.12 and still working

**Comment by lt-codex** [comment]
@jobisoft 
- MacOS Mojave 10.14.1
- Quicktext 2.12
- Unable to resize window, but works fine on my work PC

![image](https://user-images.githubusercontent.com/40219829/73817758-9a763900-47a0-11ea-9f9b-30f70a125c2d.png)

**Comment by Letterus** [comment]
@leonktam Do you have a Retina display? 10.14.1 is quite outdated. Please try upgrading Mojave to 10.14.5 at least, that should be possible even if you are using HFS+ as file system.
Please make sure you have a current version of Thunderbird as well.

**Comment by jobisoft** [comment]
@leonktam 
@Letterus 

I created a dedicated issue for leonktam here:
https://github.com/thundernest/quicktext/issues/129
