### ISSUE TITLE
Can't hide toolbar

### ISSUE THREAD

**Issue by dmusican** [thundernest/quicktext#13]
I've typically kept the toolbar for Quicktext hidden, but recently it has appeared again. I can't seem to figure out how to rehide it. While the composition window is open, I can go to View, Toolbars, but Quicktext doesn't appear there as an option.

Using Quicktext 1.0, with Thunderbird 52.8.0.

**Comment by mahWae9i** [comment]
I'm also experiencing this issue on the latest Thunderbird - just appeared without prompting a couple of days after the update.

EDIT:
Noticed in the add-ons manager in the release notes, which is great if you want to use it but I can't find a way to disable with the GUI.

> Adds a toolbar with unlimited number of text to quickly insert. It's also possible to use variables like [[TO=firstname]]. With settings for everything.

**Comment by dmusican** [comment]
I'll also add that the toolbar for me is quite dark (very dark gray text on a black strip), and so it sticks out with the rest of the screen, and is also essentially unreadable.

![thunderbirdcomposescreenshot](https://user-images.githubusercontent.com/695685/40973500-0a9c9ee2-688a-11e8-8394-4be1390007b2.png)

**Comment by jobisoft** [comment]
Fixed?

https://bugzilla.mozilla.org/show_bug.cgi?id=1391020#c65

Due to double review process, it will take a while, before it will show up at AMO. If this fixes your issue, please close this.

I cannot do anything about the color stuff, I guess this is due to your theme?

**Comment by dmusican** [comment]
Fixed! Many thanks for the quick response.

Color stuff: I've got the menu bar hidden now, so doesn't matter to e now on that one. :)
