### ISSUE TITLE
Community script: CleanSubject

### ISSUE THREAD

**Issue by SamuelPlentz** [thundernest/quicktext#133]
I got inspired by the community script [SetSubject](https://github.com/thundernest/quicktext/wiki/Script:-SetSubject) and by the fact that the addon [Clean Subject](https://addons.thunderbird.net/de/thunderbird/addon/clean-subject/) is not maintained anymore. I created a [CleanSubject](https://github.com/thundernest/quicktext/wiki/Script:-CleanSubject) community script and I am pretty satisfied with it.

Writing it I came across some possible small and big improvements for QuickText:
- Could we get a monospaced "programming" font like Consolas in the script dialog? Would make formatting a little bit easier. (syntax highlighting would be another but much bigger step into that direction)
- Would it be possible to auto-execute a script? (either when applying any template or on creation of a new email)
- Should this rather popular addon somehow be integrated a little bit more into QuickText? (perhaps bundle some/all community scripts with QuickText; perhaps even create a GUI?)

**Comment by SamuelPlentz** [comment]
Added a [pull request](https://github.com/thundernest/quicktext/pull/135) for the monospace font part of this issue. Tested it locally, works.

**Comment by jobisoft** [comment]
> Could we get a monospaced "programming" font like Consolas in the script dialog? Would make formatting a little bit easier. (syntax highlighting would be another but much bigger step into that direction)

Fixed by your pull request.

> Would it be possible to auto-execute a script? (either when applying any template or on creation of a new email)

Please create a dedicated issue for this. Present a use case and some details of the desired feature request.

> Should this rather popular addon somehow be integrated a little bit more into QuickText? (perhaps bundle some/all community scripts with QuickText; perhaps even create a GUI?)

I have no idea what you mean by that. Create a dedicated issue and elaborate more.
