### ISSUE TITLE
Let all supported tags be added by the menu.

### ISSUE THREAD

**Issue by SamuelPlentz** [thundernest/quicktext#139]
Currently many of the supported tags can be added by the menus.
The following ones can't.
- COUNTER
- INPUT
- ORGATT
- ORGHEADER
- SCRIPT
- TEXT
- URL

**Comment by jobisoft** [comment]
Analyzing the current situation.

There are two places with menu:
1. In the quicktext settings UI
2. In the message composer

* COUNTER is missing in both
* INPUT is missing in both
* ORGATT is missing in both and seems to be broken (for me) 
* ORGHEADER is missing in both
* SCRIPT is avail in settings UI (via dedicated submenu) and missing in message composer
* TEXT is avail in both (via dedicated submenu)
* URL is missing in both

**Comment by jobisoft** [comment]
If a variable needs parameters, it cannot be directly added in the messenger. Thus this issue breaks down to:

* add COUNTER to both
* add INPUT to settings UI
* add ORGATT to settings UI
* add ORGHEADER to settings UI
* add URL to settings UI

**Comment by jobisoft** [comment]
@SamuelPlentz : Could you do QA for the current master branch and check if this issue is solved?

**Comment by SamuelPlentz** [comment]
No bugs spotted. My thoughts:

1. Remove Counter from message composer. No need to insert "1" by a button. ;)
2. Rename the German translation of "Counter" to "Zähler"
3. Reorder the menu entries by importance and group them together, currently it seems random. Add more menuseparators, perhaps even add new folders.
I will propose in German - sry:

- Cursor positionieren
- Selektion
- Zwischenablage
- `-----`
- Header hinzufügen
- Betreff
- Ursprüngliche Anhangsinformationen
- Ursprüngliche Header-Informationen
- `-----`
- Inhalt einer Datei (Quicktext Variablen werden ersetzt)
- Eingebettetes HTML Bild
- Rückgabewert einer URL-Anfrage
- `-----`
- Eingabewert von einer Eingabeaufforderung
- Counter
- Thunderbird Version

**Comment by SamuelPlentz** [comment]
If you agree I could create pull requests for 1, 2 and 3.

**Comment by jobisoft** [comment]
1: the counter is not reset, so even in the message composer you get the current counter value (which happens to be "1", if you have never used it). So I will keep the entry there.

2: ok, i will accept PR

3: I separated the entries by text-insert-variables and action-variables (cursor and Header). The order should be based on the english variable names. 

To make the order not look random, one could start with the variable name followed by a short explanation. Would you like to try that? For now I would not like to add more separators.

**Comment by SamuelPlentz** [comment]
2: See #150.

3: IMO there is much room to improve.

- We could sort the strings by localized texts.
- We could add the variable name in brackets `[[URL]] Rückgabewert einer URL-Anfrage`
- We could link to the wiki, what is expected as parameter and for further description.
- Perhaps even add translated parameter information similar to IntelliSense inline.

**Comment by jobisoft** [comment]
3: I am open for PRs, but I will not spend time on that.
