### ISSUE TITLE
Template text no longer has word wrap

### ISSUE THREAD

**Issue by multiwebinc** [thundernest/quicktext#141]
As the title says. We need word wrap in the template text in the settings window. It's difficult to edit the text because we have to scroll horizontally.

![image](https://user-images.githubusercontent.com/901732/74377178-0ceea680-4da9-11ea-96b1-ffc843b764a7.png)

Tested on Thunderbird 68.4.1 on Linux, QuickText 2.12.

**Comment by multiwebinc** [comment]
This appears to be the commit that introduced this behavior: https://github.com/thundernest/quicktext/blob/e71a3c14731c8eb1e4b507d181c945688720cb84/chrome/content/settings.xul#L261

https://github.com/thundernest/quicktext/blob/e71a3c14731c8eb1e4b507d181c945688720cb84/chrome/content/settings.xul#L347

I'm assuming you could just remove `wrap="off"`.

@jobisoft Was there any reason for turning off word wrap?

**Comment by SamuelPlentz** [comment]
I don't know about this one.

IMO:
The template text usually is nicer to read with word-wrap enabled.
The script text usually is nicer to read with word-wrap disabled.

But in some cases the other word-wrap option would be a nice to have. So I propose a button to switch with the default enabled in template text and disabled in script text.

**Comment by jobisoft** [comment]
Turning off word wrap was intentional for scripts and a mistake for templates. I will revert it for templates.

Will look into the switch button.
