### ISSUE TITLE
[[CURSOR]] tag not working in HTML mode

### ISSUE THREAD

**Issue by Nerd2k** [thundernest/quicktext#142]
The following template code fails setting the cursor to the wanted position.
```
<p>Dear [[TO=fullname]],</p>
<p>[[CURSOR]]</p>
<p>Best regards<br>
John Sample<p>
```
Instead it produces:
***
Dear John Sample,

[[CURSOR]]

Best regards
John Sample
***
The error message in the debug console is:
```
Argument 1 of Range.setStart is not an object. quicktext.js:550
    insertBody chrome://quicktext/content/quicktext.js:550
    insertTemplate chrome://quicktext/content/quicktext.js:359
    editorKeyPress chrome://quicktext/content/quicktext.js:797
    load chrome://quicktext/content/quicktext.js:48
```
Can you help? :)

**Comment by jobisoft** [comment]
Works for me. Please provide:

Operating System: 
Quicktext Version:

**Comment by Nerd2k** [comment]
Thanks for your quick reply!

Operating System: Windows 10, 1803
Quicktext Version: 2.12

**Comment by jobisoft** [comment]
It looks like you used a key word or something to trigger the insert of the template? Does the error also happen, if you insert the template via the template drop-down menu?

What are the exact steps and settings to reproduce your use case and the resulting error?

**Comment by Nerd2k** [comment]
Yes, I used a keyword and the tab-key is the set key to activate the template.
If I insert the template via the drop-down menu, it produces the following output instead:
***
Dear John Sample,

Best regards
John Sample
***
and this log entry: `CURSOR LOG failedSearchAttempts : 1 quicktext.js:617:15` and no blinking cursor visible anywhere after the insertion.

The steps are quite straight forward:
1) Hit reply on an email
2) Insert template via drop-down or instert template via typing the keyword and hitting tab-key

Please let me know if you need any further info, I'm happy to help getting to the bottom of this.

**Comment by jobisoft** [comment]
The non-blinking cursor is a bug in Thunderbird (I think). If you start typing, it will insert your text at the desired position. The cursor is at the position indicated by [[CURSOR]]. Can you confirm?

The log you see is debug, because the tag has been troublesome in the last month. No need to worry about that. If you see 100 failed search attempts, something is wrong :-)

I will try to reproduce your issue with the tab key ...

**Comment by Nerd2k** [comment]
Thunderbird version: 68.5.0 (32-Bit)
No additional other add-ons, quicktext is the only add-on installed. No special quicktext settings.

![grafik](https://user-images.githubusercontent.com/11968010/74458036-63331680-4e89-11ea-862a-69bf811fa23d.png)

![grafik](https://user-images.githubusercontent.com/11968010/74458284-c45aea00-4e89-11ea-9bdd-d6afd10c81f7.png)

**Comment by jobisoft** [comment]
The non-blinking cursor is a bug in Thunderbird (I think). If you start typing, it will insert your text at the desired position. The cursor is at the position indicated by [[CURSOR]]. **Can you confirm?**

The log you see is debug, because the tag has been troublesome in the last month. No need to worry about that. If you see 100 failed search attempts, something is wrong :-)

I will try to reproduce your issue with the tab key ...

**Comment by Nerd2k** [comment]
> The non-blinking cursor is a bug in Thunderbird (I think). If you start typing, it will insert your text at the desired position. The cursor is at the position indicated by [[CURSOR]]. **Can you confirm?**

Ah yes, cool, I can confirm that. So inserting via the drop-down menu works as intended. Thank you :)

> The log you see is debug, because the tag has been troublesome in the last month. No need to worry about that. If you see 100 failed search attempts, something is wrong :-)

Ok :)

> I will try to reproduce your issue with the tab key ...

That would be cool, I'd really like to have the keyword thing working as it's much quicker for me.

**Comment by SamuelPlentz** [comment]
Can't confirm:
- Operating System: Windows 10, 1909 (differs from Nerd2k: 1803)
- Quicktext Version: 2.12
- Thunderbird 68.5.0 (32bit)

Setting everything up like above.
Writing `ht` + `Tab` works like intended.

Affected lines:
```javascript
if (aStr.indexOf('[[CURSOR]]') > -1 && specialRange && endRange)
{
  var newRange = editor.document.createRange();
  newRange.setStart(specialRange[0].childNodes[specialRange[1]], specialRange[2]);
  newRange.setEnd(endRange.endContainer, endRange.endOffset);

  // Take care of the CURSOR-tag
  await this.parseCursorTag(editor, newRange);
}
```
The exeption seems to say that newRange is null.
```
Argument 1 of Range.setStart is not an object. quicktext.js:550
    insertBody chrome://quicktext/content/quicktext.js:550
    insertTemplate chrome://quicktext/content/quicktext.js:359
    editorKeyPress chrome://quicktext/content/quicktext.js:797
    load chrome://quicktext/content/quicktext.js:48
```

**Comment by jobisoft** [comment]
I was able to reproduce it and I may have fixed it (that cursor code is one large black box with ancient code from Emil).

[quicktext_pre.xpi](https://github.com/thundernest/quicktext/files/4221804/quicktext.zip)

@Nerd2k : Can you verify? Remove your current version of quicktext, restart TB, close AddOnManger, reopen AddOnManager and install this version via the gear menu in the AddOnManager. You cannot just install it over the current installed version.

@Nerd2k 
@SamuelPlentz 

Is any of you able to verify, if the [[CURSOR]] tag still works on linux with this version?

**Comment by jobisoft** [comment]
Updated Version.

[quicktext_pre.xpi](https://github.com/thundernest/quicktext/files/4221804/quicktext.zip)

**Comment by ovari** [comment]
![image](https://user-images.githubusercontent.com/17465872/74813402-6e82b800-5349-11ea-824b-fb3a643f4a0e.png)

![image](https://user-images.githubusercontent.com/17465872/74813170-fae0ab00-5348-11ea-8f09-acca07498b70.png)

In the email, the
* `[[CURSOR]]` is in the correct place
* `<p>` and `<br>` tags are showing

Linux Mint 19.3 Cinnamon
Thunderbird 68.4.1 (64-bit)
Quicktext https://github.com/thundernest/quicktext/issues/142#issuecomment-587908774

Hope this helps.

**Comment by SamuelPlentz** [comment]
You need to choose HTML from the template insert as dropdown.

**Comment by jobisoft** [comment]
I consider this fixed. Thanks for your help @ovari !

**Comment by SamuelPlentz** [comment]
> @SamuelPlentz
> Is any of you able to verify, if the [[CURSOR]] tag still works on linux with this version?

Sorry only windows in use here.

**Comment by Nerd2k** [comment]
@jobisoft I just tested the new quicktext version 2.15 and the issue is solved, works like a charm now. Good job, thank you so much! 👍
