### ISSUE TITLE
Fix groupbox caption

### ISSUE THREAD

**Issue by jobisoft** [thundernest/quicktext#147]
It looks like the groupbox caption is not looking good with standard Thunderbird styles and they look different for Windows, MacOS and Linux.

I now added a OS selector attribute to the outer dialog of the settings window:

https://github.com/thundernest/quicktext/blob/bc03d073a75574af306aa1c3c3a8c71b7fd4700b/chrome/content/settings.js#L23-L25

On the console you can see what attribute is added. For windows it is WINNT.

This selector can now be used to apply different styles for each OS:

https://github.com/thundernest/quicktext/blob/bc03d073a75574af306aa1c3c3a8c71b7fd4700b/chrome/skin/quicktext.css#L46-L54

Feel free to contribute CSS styles for MacOS and Linux.

**Comment by jobisoft** [comment]
@ovari : Could you help out here for Linux?
@Letterus : Could you help out here for MacOS?

**Comment by ovari** [comment]
@jobisoft it worked correctly with the 21 Feb 2019 version of Quicktext. Please see the image shown at https://github.com/thundernest/quicktext/issues/58#issue-412813517. Can the settings from then please be used?

**Comment by SamuelPlentz** [comment]
In this case it should work with the code that is online right now. Could you test that?

**Comment by jobisoft** [comment]
@ovari 
@Letterus 

Could you test the version I linked [here](https://github.com/thundernest/quicktext/issues/142#issuecomment-587882377)?

Besides testing the layout of the groupbox caption, could you also test, if the [[CURSOR]] tag is still working with that version on your plattforms? I fixed something reported on windows and it seems like everytime I change something on the cursor code for one plattform, I break something for the other plattforms.

**Comment by ovari** [comment]
@jobisoft the results are shown at https://github.com/thundernest/quicktext/issues/142#issuecomment-588084205

**Comment by jobisoft** [comment]
I consider this fixed. Thanks for your help @ovari !
