### ISSUE TITLE
thunderbird 52.8.0 32 bit

### ISSUE THREAD

**Issue by dmahler1** [thundernest/quicktext#15]
My pc just updated to what I assume is a newer version of thunderbird, and, quicktext no longer works...  wont even load up... anyone help?  please?  I use quicktext almost every email I send....  THANK YOU!!
for further clarification.... its seems that there is a toolbar with my scripts, but, even after I select load quicktext on right click, it wont load....

**Comment by jobisoft** [comment]
have you installed quicktext 1.0 ?
https://addons.mozilla.org/de/thunderbird/addon/quicktext/

**Comment by dmahler1** [comment]
is there a link like this but in ENGLISH???

**Comment by jobisoft** [comment]
https://addons.mozilla.org/en-US/thunderbird/addon/quicktext/

But you can also download quicktext 1.1, which fixes a few bugs (will be officially released shortly):
https://bugzilla.mozilla.org/show_bug.cgi?id=1391020#c65

**Comment by dmahler1** [comment]
When I try to download and install this one, it stops and advises that 
the add on can not be verified, and will not install.
is there a fix????

**Comment by jobisoft** [comment]
see my instructions in the other issue...

**Comment by jobisoft** [comment]
@dmahler1 Can you close this?

**Comment by dmahler1** [comment]
done... thank you
