### ISSUE TITLE
Option to not show bar (just working with keyword + hotkeys)

### ISSUE THREAD

**Issue by Spiegel-Leser** [thundernest/quicktext#152]
I'd like to have an option to not show the quicktext menu bar. I only ever use the keywords and hotkeys and it's taking up unnecessary space.

**Comment by jobisoft** [comment]
I think that is implemented:
![grafik](https://user-images.githubusercontent.com/5830621/76154547-92caec80-60de-11ea-80c6-f3d015fa316f.png)
