### ISSUE TITLE
Update 2.14 - changed IMAGE variable

### ISSUE THREAD

**Issue by jnk5** [thundernest/quicktext#154]
> - change IMAGE variable to include entire image html tag per default

Why? I was using base64 in src. Now I can't change other IMG attributes like width.
Is it still possible to get base64?

**Comment by SamuelPlentz** [comment]
Yes, see [here](https://github.com/thundernest/quicktext/wiki/List-of-all-supported-tags#image). [Discussion](https://github.com/thundernest/quicktext/issues/110).

`<img src="[[IMAGE=C:\picture.png|src]]" alt="Cats">`

**Comment by jnk5** [comment]
Oh, I missed that page in Wiki. Thank you!

**Comment by SamuelPlentz** [comment]
You are welcome.
Is there a changelog, that I didn't see until now? Or didn't you quote a changelog?

@jobisoft:
IMO we should have a file for that. Would you accept a pull request or does it exist somewhere?

**Comment by jobisoft** [comment]
He quoted the official change log:
https://addons.thunderbird.net/en-US/thunderbird/addon/quicktext/versions/

**Comment by SamuelPlentz** [comment]
I searched here for it, but it didn't show up there:
https://addons.thunderbird.net/de/thunderbird/addon/quicktext/versions/

Should we add a wiki page for greater visibility?

**Comment by jobisoft** [comment]
I think it is a bug, that the english text does not show up in the other languages, if they has not been a dedicated translation. Will file a bug.

The beauty about the changelog at ATN: They will show up inside Thunderbird as well.

I added an information to the main README and the wiki. Would that be enough?

**Comment by SamuelPlentz** [comment]
Sorry for the late answer.

> The beauty about the changelog at ATN: They will show up inside Thunderbird as well.

The downside of this changelog is that it can only be maintained by a single person. And currently some versions are missing a description. By deploying you could easily copy the text from there. IMO it would be a better way to use the wiki or even a file in Git itself, allowing to change it with each commit.

> I added an information to the main README and the wiki. Would that be enough?

Better to find now, thanks.
