### ISSUE TITLE
shortcut modifier space block writing 

### ISSUE THREAD

**Issue by userQAY** [thundernest/quicktext#156]
I want to write "your" and i want get "Your" using "space" modifier. But after i use space, i cant write next space to continue writing / or in another words/  the first space is not visible. After first space i can write characters, but not "space" but, first space is not visible, so I need to write next space, but it is imposible. Could you fix it please?

**Comment by jobisoft** [comment]
Include the space in your replace template

**Comment by userQAY** [comment]
thanks a lot !!

**Comment by jobisoft** [comment]
Closing as solved
