### ISSUE TITLE
is it possibility inserting html code via scripts? 

### ISSUE THREAD

**Issue by userQAY** [thundernest/quicktext#157]
when I want insert html code via script, it is inserted as a plain text, not as a formatted text. so instead bold text i get `<b>text</b>`.  
please, could i get an advice?

**Comment by jobisoft** [comment]
the template which is including the script must be set to html

**Comment by Stan-Stani** [comment]
I am going to add this to the wiki (unless it's hidden somewhere) because I was wondering how to do this and only found the solution by searching the issues.
