### ISSUE TITLE
The configuration disappears

### ISSUE THREAD

**Issue by bepolymathe** [thundernest/quicktext#161]
Hi, 

It's amazing but it's been three times that my configuration (template and scripts) disappears after a new Thunderbird startup. 

Do you have an idea? Besides, I manage to import new scripts thanks to the xml backup file but not the templates. That's weird. 

Fedora 32
Thunderbird 68.7.0
Quicktext 2.15

**Comment by bepolymathe** [comment]
This problem makes the extension unusable and I don't understand where it comes from. 

Each reboot of Thunderbird erases the entire configuration. Worse, I can't import the templates I had created and for which I had a backup file. I tried to reinstall the extension without success. I get stuck.

**Comment by jobisoft** [comment]
Give me a view days, these times are not easy.

**Comment by bepolymathe** [comment]
Could I give you some logs that would help?

**Comment by jobisoft** [comment]
Status with Quicktext 3.2?
