### ISSUE TITLE
[Feature] Have values of system variables available in a template

### ISSUE THREAD

**Issue by JoergPalmer** [thundernest/quicktext#162]
I think it would be great if we could use the values of system environment variables within the template, e.g. "HOME". On a Linux system I would expect that example to point to my home folder. I do think there are many use cases out there where this could be helpful.

Here is my use case: I'm using my private cloud to store the quicktext templates. Some templates reference files, which also are located in my cloud sync folder. On different machines the path changes because the name of the home folder changes.

**Comment by SamuelPlentz** [comment]
Is there any possibility to get system variables from javascript? For me it looks like this is not wanted.
- https://stackoverflow.com/questions/21315708/reading-environment-variables-with-javascript

I couldn't even get the computername in javascript. @jobisoft: any idea - is there a thunderbird internal variable one could query?

As a workaround you could use scripts like this:

Script `computername`:
``` javascript
// return current environment (computername) - adjust that line for each computer in use
return "Computer1";
```

Script `homepath`:
``` javascript
var computername = this.mQuicktext.process_script(['computername']);

var homepath = '';
if(computername == "Computer1") homepath = '...';
if(computername == "Computer2") homepath = '...';

return homepath;
```

**Comment by jobisoft** [comment]
That is correct, we will not be able to catch the home folder. I like @SamuelPlentz suggestion, it is your best bet.

**Comment by Alfred-Peters** [comment]
I have found a way (tested on Windows with TB91.9 and TB102.0a1) to read the environment variables:

Template: `getEnv`:
`[[SCRIPT=scGetEnv|[[INPUT=Script|select|COMPUTERNAME;HOMEPATH;TEMP;USERNAME]]]]`

Script: `scGetEnv`:
```
function getEnv(name) {
  try {
    var environment = Cc["@mozilla.org/process/environment;1"].getService(
      Ci.nsIEnvironment
    );
    return environment.get(name);
  } catch (e) {
    return("Error scGetEnv(): "+ e);
  }
  return undefined;
}
return getEnv(this.mVariables[0]);
```

**Comment by Alfred-Peters** [comment]
> Is there any possibility to get system variables from javascript? For me it looks like this is not wanted.
> 
>     * https://stackoverflow.com/questions/21315708/reading-environment-variables-with-javascript

It is certainly undesirable for a script on a website to be able to read information about your computer.

In the Quicktext context, however, they are user scripts. Here it should be OK.
However, it must be ensured that Quicktext never executes scripts from an e-mail or from a web page.

**Comment by SamuelPlentz** [comment]
Added the community script: [GetEnvironmentVariable](https://github.com/jobisoft/quicktext/wiki/Script:-GetEnvironmentVariable). Thanks Alfred Peters.

**Comment by Alfred-Peters** [comment]
> Added the community script: [GetEnvironmentVariable](https://github.com/jobisoft/quicktext/wiki/Script:-GetEnvironmentVariable).

```
Get environment variable from the system. Possible variables are USERNAME, COMPUTERNAME, HOMEPATH and TEMP.
```

That sounds so limiting. I have chosen these variables only as an example.
The script works also with all other environment variables.

**Comment by SamuelPlentz** [comment]
Good point, I changed the description to:

> Get environment variable from the operating system. It should return the value of any variable that is defined by the operating system. For example: `USERNAME`, `COMPUTERNAME`, `HOMEPATH`, `TEMP`, ...
