### ISSUE TITLE
Special Keywords

### ISSUE THREAD

**Issue by aschiller2** [thundernest/quicktext#163]
Is it possible to make use of special keywords like "compose", "reply" and "forward" to insert the template into a new message, reply to a message or a forwarded message?

I was lookin for such a feature within Quicktext, but cannot find a hint neither in the documentation nor in the source code, so I think this is a feature request?

**Comment by SamuelPlentz** [comment]
I would like this. Would solve my need to auto execute the [CleanSubject](https://github.com/jobisoft/quicktext/wiki/Script:-CleanSubject) script.

**Comment by jobisoft** [comment]
Duplicate of https://github.com/jobisoft/quicktext/issues/200
