### ISSUE TITLE
don't work Thunderbird 78.0.1

### ISSUE THREAD

**Issue by tsunli** [thundernest/quicktext#165]
Quicktext 2.5 No automatic upgrade.
After manual upgrade to 3.1, it works fine.
![image](https://user-images.githubusercontent.com/9134728/88752783-55e6bb80-d18d-11ea-8e57-399a46e6ba1a.png)

**Comment by jobisoft** [comment]
Not true. 

https://addons.thunderbird.net/addon/quicktext/versions/

**Comment by Coernel82** [comment]
It does work however the settings menu can not be found as documented. Create a new email - ander Extras you will find the options!

**Comment by PotatoCarl** [comment]
Nope. Sorry, does not. No Menu, no setting, no quick-text. It is listed under addons as "active". but in a new email I do not see anything. Neither in the "extra" menu.

**Comment by jobisoft** [comment]
![grafik](https://user-images.githubusercontent.com/5830621/88947927-8adc3680-d291-11ea-8259-35db38dd696e.png)

I have no idea what is going wrong on your system. Quicktext 3.1 is running fine in TB 78.0.1

**Comment by tsunli** [comment]
Quicktext 2.5 No automatic upgrade.
After manual upgrade to 3.1, it works fine.
thanks  everybody.

**Comment by PotatoCarl** [comment]
I have version 3.1 installed. No configuration accessible. In a new message the menu is not displayed. 
Not working 78.0.1

**Comment by PotatoCarl** [comment]
Reinstalled Thunderbird 68 - wanted to "recreate profile", so reinstalled Thunderbid 78 again - disabled Addon - Enabled Quciktext -> Now it is working.
Ghost in the machine...
