### ISSUE TITLE
Problems with TB version 78

### ISSUE THREAD

**Issue by Hondoe1950** [thundernest/quicktext#166]
Previously, when writing a new email, one could click on a quicktext template and it would fill the body of the email, even if the focus was still on the To: or Subject:

With the new version 78 update, this won't happen unless the focus is on the body of the email.

Can this be fixed?

**Comment by jobisoft** [comment]
Can you try 3.2?
[quicktext_3.2.xpi](https://github.com/jobisoft/quicktext/files/5102434/quicktext.zip)

**Comment by jobisoft** [comment]
Quicktext 3.2 officially released.
