### ISSUE TITLE
Feature request: add cc and bcc

### ISSUE THREAD

**Issue by bt7411** [thundernest/quicktext#17]
Hi, would like to be able to add cc and bcc's to a template (like can do in the SmartTemplate4 add-on). Currently have to manually edit templates.xml as explained in this thread: http://extensions.hesslow.se/forum/thread/370/Create+TO+using+quicktext/

**Comment by tju79** [comment]
I wish this future too :)

**Comment by multiwebinc** [comment]
Please take a look at https://github.com/multiwebinc/quicktext. It's a start, but it has the following issues:

* Only one header is added at a time (CC or BCC) unless you insert the template into the email more than once
* Reply-To is not working for some reason
* It doesn't perform any email format validation
* It's not translated.

**Comment by jobisoft** [comment]
I added a header tag: 
https://github.com/thundernest/quicktext/wiki/List-of-all-supported-tags#header

Happy Testing:
[quicktext.xpi](https://github.com/thundernest/quicktext/files/3918319/quicktext.zip)

@multiwebinc : Thanks for the inspirations!
