### ISSUE TITLE
Automatically replacing the attribution line

### ISSUE THREAD

**Issue by the-solipsist** [thundernest/quicktext#171]
Hi,
I have the following set up as my “Reply” template in Quicktext:

    Dear [[TO=firstname]],
    [[SELECTION]][[CURSOR]]

    Regards,
    [[FROM=firstname]]

    [[TO=fullname]] <[[TO=email]]> [[[SCRIPT=DateTime]]]:

The last line is supposed to be the attribution line (“On [date], [person] wrote”), formatted the way I’d like it to be. But since there is already an attribution line, I have to manually delete the pre-existing one. Is there any way that I can remove the pre-existing attribution line using Quicktext?

I realize this isn't a bug, but I [the discourse forum](https://discourse.mozilla.org/t/quicktext-need-help-removing-existing-attribution-line-in-a-reply-message/66480) doesn't seem to be very active.

**Comment by jobisoft** [comment]
You mean the line added by TB at the top? Hm. Changing existing body is currently not suported. There is a lot of work ahead to adapt to the new extension framework, so I will not add new features at the moment.

**Comment by the-solipsist** [comment]
Thanks.  Being able to delete such text, along with the ability to set automated templates for reply, forwards, etc., would make this add-on a great replacement for [Change Quote and Reply Format](https://freeshell.de/~kaosmos/changequote-en.html).   I'm closing this issue for now, as it is a feature request that can't be addressed soon.

And thank you very much for your fantastic work on this add-on.

**Comment by SamuelPlentz** [comment]
You could probably solve this by a community Script.

A combination of this two scripts could probably work: (adding some code to identify and replace the current attribution line)
https://github.com/jobisoft/quicktext/wiki/Script:-CustomForwardHeader
https://github.com/jobisoft/quicktext/wiki/Script:-GetMailBody

Also please notice that the script CustomForwardHeader contains better information about the original email.

**Comment by the-solipsist** [comment]
Hi, @SamuelPlentz. I tried to do things like:
```
text = this.mQuicktext.get_script(["GetMailBody"])
var lines = text.split('\n');
lines.splice(0,1);
var newtext = lines.join('\n');
return lines;
```
However, while that removed the TB-set attribution line, it also mangled up the text body.  I'm not very familiar with Javascript.  Would you have any suggestions on how to do it the right way in JS?

**Comment by SamuelPlentz** [comment]
I came up with this prove of concept:
Skript ```remove_attribution_line```:
```Javascript
var editor = this.mWindow.gMsgCompose.editor;
var text = editor.outputToString('text/html', 0)
text = text.replace(/On .* wrote:/, '')
editor.selectAll();
editor.insertHTML(text);
return ''
```

Use like ```[[SCRIPT=remove_attribution_line]]```.

It automatically replaces the current attribution line. However the cursor is set to the end of the text.
