### ISSUE TITLE
TB78 : Menu entries missing an dropdown arrow

### ISSUE THREAD

**Issue by SamuelPlentz** [thundernest/quicktext#172]
In QuickText version 3.2 there is no dropdown arrow next to template-group-menu-entries anymore.

When writing an email, the toolbar above contains the names of my template-groups. In prior versions each template-group had a dropdown arrow next to it. There is only a visual bug, as I can still click on the template-group opening the dropdown and afterwards selecting the template-item.

**Comment by jobisoft** [comment]
Would this do it?
[quicktext.zip](https://github.com/jobisoft/quicktext/files/5213182/quicktext.zip)

**Comment by SamuelPlentz** [comment]
Its better, but different.
Previously (left side) there were arrows, but no buttons around them. Now there are buttons (right side) for each entry and the spacing inside the buttons looks weird. There is also some unnecessarily space between the buttons.

Could you have a look or give me a hint where to adjust the look? (CSS?)

![QT Toolbar](https://user-images.githubusercontent.com/1890854/93070471-2d544b80-f67f-11ea-9e25-c0a2301c1eb6.png)

**Comment by jobisoft** [comment]
This CSS file is loaded into the composer window: /skin/quicktext.css

In the version I shared in this issue, the buttons are <button type="menu"> inside <toolbar id="quicktext-toolbar">

If you could adjust their style, that would be great.

John

**Comment by SamuelPlentz** [comment]
Adding this lines to `/chrome/skin/quicktext.css` seems to work fine:
``` CSS
#quicktext-toolbar button {
  border:       0px;
  margin-left:  2px;
  margin-right: 2px;
  min-width:    auto;
}
```

The massive borders are removed. The margin between the buttons is reduced and the min width (that made buttons with very short text look strange) is removed.

![neu](https://user-images.githubusercontent.com/1890854/93115254-ee90b680-f6bb-11ea-80de-051956f85d9b.png)

**Comment by SamuelPlentz** [comment]
Created a pull request: #179
