### ISSUE TITLE
id in manifest.json

### ISSUE THREAD

**Issue by Mechtilde** [thundernest/quicktext#173]
Hello,

I try to package Quicktext for Debian and found that the id in manifest.json has the old format and not the new one as in Tbsync etc.

Can you please have a look?

Mechtilde

**Comment by jobisoft** [comment]
I cannot change the id, as all users will not get updates anymore. To use a new id I would need to create a new addon. Are you sure the old but still supported id format does not work for sideloading?

**Comment by Mechtilde** [comment]
Hello john,

if they are still supported I will do some more test.

Am 05.09.20 um 19:39 schrieb John Bieling:
> I cannot change the id, as all users will not get updates anymore. To use a new id I would need to create a new addon. Are you sure the old but still supported id format does not work for sideloading? 
> 
> 

-- 
Mechtilde Stehmann
## Apache OpenOffice
## Freie Office Suite für Linux, MacOSX, Windows und OS/2
## Debian Developer## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by jobisoft** [comment]
Did it work?
