### ISSUE TITLE
[Feature request] CardBook support (currently Quicktext reads names of CardBook contacts only from address in compose window)

### ISSUE THREAD

**Issue by bege10** [thundernest/quicktext#174]
Since I have changed to CardBook as my standard address manager I found that Quicktext does not reliably read recipient names from CardBook address books if the contact contains no last name.
If the first name is a name of two names with blank in between Quicktext reads only the first one and reads the second as last name. First names with only one name remain empty and the first name is read as last name.

Additionally, there should be an option to choose whether to read recipient names from CardBook (if installed) or standard Thunderbird address books.

**Comment by jobisoft** [comment]
There is no Cardbook support in Quicktext and there will never be. Except someone else implements it.

**Comment by bege10** [comment]
Oh, so I can be happy that it works with contacts with first and last name. How does that come?
Is there something that can be done on CardBook side to fix the reported issue?
Unfortunately I am not a developer. Quicktext and CardBook are worth to be compatible.
Thank you for your work.

**Comment by jobisoft** [comment]
I bet QT is just reading the standard contacts in the default AB. There is no code whatsoever in QT that reads Cardbooks Database.

**Comment by bege10** [comment]
To test that I created a fake contact in CardBook and it works with Quicktext as reported.

**Comment by jobisoft** [comment]
Magic. I do not know. There is no Cardbook code in QT. Maybe Cardbook also copies the new contact back into the standard AB or intercepts standard AB requests and injects Cardbook contacts. Better ask with Cardbook. Trust me. I do not support Cardbook.

**Comment by bege10** [comment]
As the fake contact is not in the standard address book it must work the second way you mention. So I will ask with CardBook and report back here the outcome. Thank you so far.

**Comment by SamuelPlentz** [comment]
AFAIR there are 2 ways Quicktext tries to gather the recipient information. If possible it searches the Addressbooks (not CardBook) for the current address. If this is not possible the recipient itself `John Doe <john.doe@gmail.com>` is parsed for pre- and surnames.

If I am correct this is what happens here.

**Comment by SamuelPlentz** [comment]
If you reduce the recipient to `john.doe@gmail.com` there should be no magic happening anymore.

AFAIR magic should be:
`John Doe` will result to prename `John` surname `Doe`.
`Doe, John` will result to prename `John` surname `Doe`.
`Doe` will result to surname `Doe`.
`John` will wrongly result to surname `John`.

**Comment by bege10** [comment]
Indeed Quicktext seems not to read the names from the CardBook contact. I changed the display name to a different name than the names. The result: first name remains empty, last name now is the display name. So in my previous tests Quicktext must have read from the address line in the compose window.
That is good for it works with contacts with first and last name, it is a pity because CardBook cannot fix it.
So I must hope for someone who is able to implement CardBook support in Quicktext.

**Comment by SamuelPlentz** [comment]
> AFAIR magic should be:
> `John Doe` will result to prename `John` surname `Doe`.
> `Doe, John` will result to prename `John` surname `Doe`.
> `Doe` will result to surname `Doe`.
> `John` will wrongly result to surname `John`.

Perhaps there could be an option to switch the magic:
`Doe` will wrongly result to prename `Doe`.
`John` will result to prename `John`.

Or like this:
`Doe` will wrongly result to prename `Doe` and surname `Doe`.
`John` will wrongly result to prename `John` and surname `John`.

**Comment by CardBook** [comment]
Hi folks

I've made a pull request for this : #199 

Philippe

**Comment by ovari** [comment]
Should [CardBook](https://addons.thunderbird.net/addon/cardbook/) compatibility be added to Quicktext's ATN listing at https://addons.thunderbird.net/addon/quicktext/?

Thank you
