### ISSUE TITLE
write in the To field

### ISSUE THREAD

**Issue by ShargAA** [thundernest/quicktext#178]
this.mQuicktext.get_to(["email"]).value =  '123@df.ru';
or
this.mWindow.document.getElementById('msgSubject').value =  '123@df.ru';

It doesn't work!
Please help!

**Comment by SamuelPlentz** [comment]
Try this in your template:
`[[HEADER=to|123@df.ru]]`

**Comment by ShargAA** [comment]
No template,
Need code in the script.
Thanks!

**Comment by ShargAA** [comment]
[[HEADER=to|[[SCRIPT=Email_TO]]]]

It doesn't work!
Please help!

**Comment by ShargAA** [comment]
write in the To field?
Please help!

**Comment by ShargAA** [comment]
write in the To field?
Please help!

**Comment by SamuelPlentz** [comment]
> [[HEADER=to|[[SCRIPT=Email_TO]]]]

Also mentioned this. The current header handling would need a major makeover to make that work. Currently the `insertTemplate` function doesn't support nested tags, because it handles the header tag inline. Other tags are handled by `insertTemplate` > `insertBody` > `gQuicktextVar.parse` > `gQuicktextVar.parseText`.

Here is a working script that can add a header like "TO" or "CC":
``` Javascript
// possible values for the first parameter "recipientType" of the function "awAddRecipientsArray"
//   "addr_to"    - TO header
//   "addr_cc"    - CC header
//   "addr_bcc"   - BCC header
//   "addr_reply" - Reply-to header

var win = this.mWindow;
win.awAddRecipientsArray("addr_to", ["John Doe <john.doe@example.com>", "Jane Doe <jane.doe@example.com>"]);
win.awAddRecipientsArray("addr_cc", ["test@example.com"]);
```

Whats your use case? Perhaps there should be a community script.

**Comment by SamuelPlentz** [comment]
With #185 you should be able to use:
`[[HEADER=to|[[SCRIPT=Email_TO]]]]`

**Comment by jobisoft** [comment]
Merged #185.

**Comment by SamuelPlentz** [comment]
Could be closed now.

**Comment by ShargAA** [comment]
`var win = this.mWindow;
win.awAddRecipientsArray("addr_to", ["John Doe <john.doe@example.com>", "Jane Doe <jane.doe@example.com>"]);`

It works great!
But I need to delete the old address first!
How do I clear it ?
Thank you very much!

**Comment by SamuelPlentz** [comment]
Here you go:

``` Javascript
var win = this.mWindow;

// possible values for the first parameter "recipientType" of the function "getElementById"
//   "toAddrInput"    - TO header
//   "ccAddrInput"    - CC header
//   "bccAddrInput"   - BCC header
//   "replyAddrInput" - Reply-to header

// remove existing recipients
for (let pill of win.document.getElementById("toAddrInput").closest(".address-container").querySelectorAll("mail-address-pill")) {
  pill.remove();
}
for (let pill of win.document.getElementById("ccAddrInput").closest(".address-container").querySelectorAll("mail-address-pill")) {
  pill.remove();
}

// possible values for the first parameter "recipientType" of the function "awAddRecipientsArray"
//   "addr_to"    - TO header
//   "addr_cc"    - CC header
//   "addr_bcc"   - BCC header
//   "addr_reply" - Reply-to header

// add new recipients
win.awAddRecipientsArray("addr_to", ["John Doe <john.doe@example.com>", "Jane Doe <jane.doe@example.com>"]);
win.awAddRecipientsArray("addr_cc", ["test@example.com"]);
```

@jobisoft: Perhaps we should add a new tag named `CLEARHEADER` or `HEADERCLEAR`, to support removing recipients from an email.

**Comment by SamuelPlentz** [comment]
Probably there should be a second parameter for the `HEADER` tag named `cleartype` with values like:

- clear nothing (default)
- clear all
- clear to
- clear cc
- clear bcc
- clear reply-to

**Comment by SamuelPlentz** [comment]
@jobisoft: can you comment this?

**Comment by jobisoft** [comment]
This is user script area. Check the TB source in [searchfox.org](https://searchfox.org/comm-esr78/source/). I have no idea.

**Comment by SamuelPlentz** [comment]
> Here you go:
> 
> ```js
> var win = this.mWindow;
> 
> // possible values for the first parameter "recipientType" of the function "getElementById"
> //   "toAddrInput"    - TO header
> //   "ccAddrInput"    - CC header
> //   "bccAddrInput"   - BCC header
> //   "replyAddrInput" - Reply-to header
> 
> // remove existing recipients
> for (let pill of win.document.getElementById("toAddrInput").closest(".address-container").querySelectorAll("mail-address-pill")) {
>   pill.remove();
> }
> for (let pill of win.document.getElementById("ccAddrInput").closest(".address-container").querySelectorAll("mail-address-pill")) {
>   pill.remove();
> }
> 
> // possible values for the first parameter "recipientType" of the function "awAddRecipientsArray"
> //   "addr_to"    - TO header
> //   "addr_cc"    - CC header
> //   "addr_bcc"   - BCC header
> //   "addr_reply" - Reply-to header
> 
> // add new recipients
> win.awAddRecipientsArray("addr_to", ["John Doe <john.doe@example.com>", "Jane Doe <jane.doe@example.com>"]);
> win.awAddRecipientsArray("addr_cc", ["test@example.com"]);
> ```
This one works well - the question is, if we should extend the tags:
Perhaps we should add a new tag named `CLEARHEADER` or `HEADERCLEAR`, to support removing recipients from an email.

Probably there should be a second parameter for the `HEADER` tag named `cleartype` with values like:
- clear nothing (default)
- clear all
- clear to
- clear cc
- clear bcc
- clear reply-to

**Comment by SamuelPlentz** [comment]
Added the community scripts: [AddRecipients](https://github.com/jobisoft/quicktext/wiki/Script:-AddRecipients) and [RemoveRecipients](https://github.com/jobisoft/quicktext/wiki/Script:-RemoveRecipients).
