### ISSUE TITLE
Add-on setting do not work anymore after update to Thunderbird 78

### ISSUE THREAD

**Issue by stolzpet** [thundernest/quicktext#184]
Thunderbird 78.3.1 64Bit
Operating System: openSUSE Tumbleweed 20201004
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.8.12-1-default
OS Type: 64-bit
Processors: 6 × Intel® Core™ i5-9400 CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa DRI Intel® UHD Graphics 630

Hello,

after update to Thunderbird 78.3.1 64Bit the add-on settings do not work anymore. I get only a gray window:

![grafik](https://user-images.githubusercontent.com/43900659/95201522-5d0af500-07e0-11eb-8ef3-896628dabd80.png)

Can you please help and fix the bug?

Dear Peter

**Comment by SamuelPlentz** [comment]
Could be related to #177.
Could you check if Thunderbirds error console has QuickText related entries?
Can you try if disabling all other Addons helps and disabling the Master Password (if set) helps?

**Comment by stolzpet** [comment]
I deactivated all add-ons. Still same error. I do not use a master password.

Error console:

Uncaught TypeError: document.getElementById(...).view is null
    buildTreeGUI chrome://quicktext/content/settings.js:1368
    updateGUI chrome://quicktext/content/settings.js:505
    init chrome://quicktext/content/settings.js:51
    onload chrome://quicktext/content/settings.xhtml:1
settings.js:1368:34
    buildTreeGUI chrome://quicktext/content/settings.js:1368
    updateGUI chrome://quicktext/content/settings.js:505
    init chrome://quicktext/content/settings.js:51
    onload chrome://quicktext/content/settings.xhtml:1

**Comment by SamuelPlentz** [comment]
Reformatted error message:
```
Uncaught TypeError: document.getElementById(...).view is null
function: buildTreeGUI chrome://quicktext/content/settings.js:1368 / settings.js:1368:34
function: updateGUI    chrome://quicktext/content/settings.js:505
function: init         chrome://quicktext/content/settings.js:51
function: onload       chrome://quicktext/content/settings.xhtml:1
```

I don't know why this should fail...
@jobisoft Any idea?

https://github.com/jobisoft/quicktext/blob/60db00b2fbb276a2720536fa9f11085112d17e19/chrome/content/settings.js#L1367-L1376

Could you please try if this version works or writes something else to the error console (CTRL + ALT + J)?

- [quicktext-3.3a3-tb.xpi.zip](https://github.com/jobisoft/quicktext/files/5343286/quicktext-3.3a3-tb.xpi.zip) (remove the ".zip" extension and install it)

**Comment by stolzpet** [comment]
Still the same error:

Uncaught TypeError: document.getElementById(...).view is null
    selectTreeRow chrome://quicktext/content/settings.js:1381
    buildTreeGUI chrome://quicktext/content/settings.js:1374
    updateGUI chrome://quicktext/content/settings.js:505
    init chrome://quicktext/content/settings.js:51
    onload chrome://quicktext/content/settings.xhtml:1
settings.js:1381:14
    selectTreeRow chrome://quicktext/content/settings.js:1381
    buildTreeGUI chrome://quicktext/content/settings.js:1374
    updateGUI chrome://quicktext/content/settings.js:505
    init chrome://quicktext/content/settings.js:51
    onload chrome://quicktext/content/settings.xhtml:1

**Comment by SamuelPlentz** [comment]
The only explanation I have is that the openSUSE OS somehow breaks the `tree.view` object. I have no clue why and what to do.
One could remove all `tree.view` occurrences, but that would strip `getSelectedItem` and `setSelectedItem` and these are needed to select templates and add/delete them.

@jobisoft Any idea?

**Comment by stolzpet** [comment]
I updated today to Thunderbird 78.3.2 (64-Bit) and now it works on one of my three PCs. All PCs have the same tumbleweed snapshot, Thunderbird version and newest quicktext. Strange behavior.

**Comment by stolzpet** [comment]
I reinstalled thunderbird and now it works.
