### ISSUE TITLE
Bug: [CURSOR] tag not working in MacOS in TB 52.9.1

### ISSUE THREAD

**Issue by jobisoft** [thundernest/quicktext#19]
I do not know, why the CURSOR tag is not working. This is a bug.

**Comment by vsantana** [comment]
I couldn't reproduce that. 
Can you try this? `Here is [[CURSOR]] my cursor!`

**Comment by de-es** [comment]
I guess this refers to 60.0+ only. I can confirm the bug for both releases (x86 and x64).

**Comment by ite-jankl** [comment]
To reproduce:

* Add HTML template `Here is [[CURSOR]] my cursor!`
* Open a new email
* Set the paragraph format to `paragraph`
* enter text `aaa`
* Press enter to insert a second paragraph
* enter text `aaa`
* Select both paragraphs
* Execute the template

This will replace the two paragraphs/lines with the template including the `[[CURSOR]]` as text.

This is on 52.9.1 (32-bit), QuickText 1.1 (last updated 2018-08-01).

**Comment by ite-jankl** [comment]
I edited the comment to reflect more findings and infos. More than I initially posted.

**Comment by vsantana** [comment]
In https://github.com/thundernest/quicktext/blob/a0bf82cac23bf20ce1ffd5f89ab5776eb7fd2a5a/chrome/content/quicktext.js#L533, newRange is blank. This is why [[CURSOR]] is not replaced.

**Comment by vsantana** [comment]
Please review my PR https://github.com/thundernest/quicktext/pull/26. This a workaround to replace tags on two or more paragraphs.

**Comment by pjzzzz** [comment]
@vsantana Hope it will get fixed/implemented in the next release

**Comment by jobisoft** [comment]
Are we talking about the same thing? The bug is as follows:

Windows, quicktext 1.1., 32-bit

On TB 52.9.1 the CURSOR tag is removed and the cursor is moved to the position as expected. If CURSOR tag is used multiple times, all tags are removed and the cursor is moved to the last position specified.

On TB 60.0 (32bit) the CURSOR tag is not replaced at all and the cursor is not moved anywhere.

The fix of @vsantana is not changing that for me. Anyone else?

**Comment by vsantana** [comment]
My PR fixes the bad behavior reported by @ite-klass at https://github.com/thundernest/quicktext/issues/19#issuecomment-412116245

**Comment by jobisoft** [comment]
I cannot see a bad behavior in https://github.com/thundernest/quicktext/issues/19#issuecomment-412116245.

This is exactly what I expect to happen. After the replacement of the selected text, the cursor sits at the defined position.

What is wrong about that and must be fixed? What am I missing?

**Comment by vsantana** [comment]
Hi, @jobisoft.
The bad behavior is the [[CURSOR]] tag is not replaced and the cursor is not positioned correctly.

Please, watch this screencast https://streamable.com/u9yjz

**Comment by pjzzzz** [comment]
@jobisoft That's what I meant ;-) 

> The bad behavior is the [[CURSOR]] tag is not replaced and the cursor is not positioned correctly.

**Comment by jobisoft** [comment]
screencast -> nice!

But still:

https://github.com/thundernest/quicktext/issues/19#issuecomment-412116245 is saying that the tag IS INDEED replaced and everything is working perfectly. The only thing I have here are words, so lets be specific to not get lost:
 - that comment is not describing any bad behavior
 - that comment is referring to windows, TB 52.9.1 and quicktext 1.1
 - there is no issue with the CURSOR tag with TB 52.9.1 on windows with quicktext 1.1

However with TB60.0
 - as shown in your screencast, the tag is not replaced
 - the fix of @vsantana is NOT fixing that for me (windows, TB60.0, 32-bit)

Is that true for all of you?

**Comment by vsantana** [comment]
the screencast was recorded on a macos high sierra, TB 52.9.1. and quicktext 1.1.
I haven't a MSWindows to check it out. sorry.

**Comment by jobisoft** [comment]
ok, can some other mac user confirm, that #26 fixes CURSOR on TB 52.9.1?

**Comment by ite-jankl** [comment]
> #19 (comment) is saying that the tag IS INDEED replaced and everything is working perfectly.

That comment says (emphasis by me)

> This will replace the two paragraphs/lines with the template **_including the [[CURSOR]] as text_**.

as in the ``[[CURSOR]]`` is not replaced but inserted as text. It does describe bad behavior.

**Comment by jobisoft** [comment]
Good that we have that sorted out. Now lets get some data for TB 52.9.1

MacOS high sierra: broken, working with fix #26 applied
Windows 10: working and still working with fix #26 applied
Linux: ?
?

All I want to find out now, if this fix is doing harm to other OS.

For TB 60.0, it looks like CURSOR is broken for all OS and fix #26 does not seem to work.

Any other input?

**Comment by vsantana** [comment]
I can confirm that for TB60 on MacOS HighSierra, [[CURSOR]] is broken. The fix #26 doesn't fixes on that.
What I suggest is that another Issue should be created specifically to TB60.

I can investigate this next week. If anyone else is interested in investigating, feel free (but let me know).

**Comment by jobisoft** [comment]
done.

**Comment by jobisoft** [comment]
I will close this issue, as it looks like it is a duplicate of #27, just with TB60 instead of TB52. 

There is a proposed fix for you to try out, but please update to TB60 as we cannot support old versions of TB: https://github.com/thundernest/quicktext/issues/27#issuecomment-448032612

I know that some of you stick to TB52 for reasons, but we just do not have the wo*manpower to fix this for older versions of TB separately. 

If that fix by any chance also works with TB52, please give a short feedback here so others know.
