### ISSUE TITLE
Does not work in TB Beta 82

### ISSUE THREAD

**Issue by taylormia** [thundernest/quicktext#191]
I am using TB 82.0b3 and am not able to install the Quicktext extension. Any chance of making it compatible with TB 82? Would really appreciate it.
![image](https://user-images.githubusercontent.com/34145387/96395339-06130180-118a-11eb-8302-95c01c2fcd63.png)

**Comment by SamuelPlentz** [comment]
Could you try to tweak the `strict_max_version` in the `manifest.json` from the `Quicktext.xpi` file?

**Comment by taylormia** [comment]
I renamed the xpi file with zip extension, unzipped and modified the `strict_max_version` in the `manifest.json` to `"82.*"`. Re-zipped the folder, renamed with extension xpi and get this error when installing from file.
![image](https://user-images.githubusercontent.com/34145387/96457517-7dc24a00-11e5-11eb-95ec-fe3d14d3cb5a.png)

**Comment by SamuelPlentz** [comment]
Could you try this one?
[quicktext 3.3 pre max_version.zip](https://github.com/jobisoft/quicktext/files/5403102/quicktext.3.3.pre.max_version.zip)

**Comment by taylormia** [comment]
Works perfectly. I use this extension for highlighting text in emails. Thanks so much!!

**Comment by SamuelPlentz** [comment]
@jobisoft should we remove the strict_max_version (if there is no known problem with current versions) or set it to a max number (which one)?
