### ISSUE TITLE
Feature Request: Fix or Script so [[TO=firstname]] returns only original sender

### ISSUE THREAD

**Issue by Tlon2010** [thundernest/quicktext#192]
First, thank you so much for continuing to update this plug in. It's a life and time saver.

A few versions of Thunderbird ago, the developers changed the long-standing behavior of reply to so that all people in the original To: field would carry over to the To: field on reply. This means in emails such as this, using [[TO=firstname]] now inserts multiple people instead of replying to just the person who sent the email.

I'm just curious if there is a good way to fix this behavior in [[TO=firstname]] variable or to provide an alternative or a script with the alternative behavior (i.e, only inserting one name in place of the variable).

**Comment by SamuelPlentz** [comment]
To get it right:

1. You are `A`. `F` writes a message with TO: `A`, `B`, `C`, with CC: `nothing` and with the message: `Hi A, hi B, hi C,` or `Hi together,`.
2. If you answer that, you automatically create a message with TO: `F`, `B`, `C` and with CC: `nothing`. You don't want to write `Hi F, hi B, hi C,`, but `Hi F,` instead.
3. If you answered that in previous Thunderbird versions, you automatically created a message with TO: `F`, with CC: `B`, `C` and with the message: `Hi F,`.

IMO the current behavior is what I would expect, then. If you don't want to write a message to everyone `Hi F, hi B, hi C,` simply drag that other recipients to the CC section before using the template. IMO it is wrong to write an email with TO: `A`, `B`, `C` and only `Hi F,` in your message.

Did I get something wrong?

Side note: There is the [orgheader tag](https://github.com/jobisoft/quicktext/wiki/List-of-all-supported-tags#orgheader). But I think you only need the first name.

**Comment by Tlon2010** [comment]
Hi Samuel,

Yes, you are exactly right in your description of the behavior. What I am looking for is a way to mimic the behavior of previous versions of Thunderbird, as you note in #3. While I agree this may not be the expected behavior for some, for others it's more common and follows the assumption that A is replying to F primarily, and cc'ing the rest. FWIW, there was, for a short time, an addon that did this but it has since stopped working with the newer versions.

You are also exactly correct that this could be solved by dragging the other recipients to the cc line, but this is an extra step or set of steps that reduces some of the value of the QuickText addon (i.e., very quick replies).

If a defined variable is out of the question, is there a relatively easy way to do this with a script? I do not write javascript, so it's beyond my ability.

With thanks for your consideration regardless.

**Comment by Tlon2010** [comment]
I was able to write a small script to do what I needed, so I'm going to close the issue. Thank you again for keeping this add on alive. It's really great.

**Comment by SamuelPlentz** [comment]
Could you share it?

**Comment by Tlon2010** [comment]
Sure. Sorry. I'm sure there is a better way to do this, but this works:

Script: FirstFirstName
`return this.mQuicktext.process_to(mVariables)['firstname'][0];`

Script call:
`[[SCRIPT=FirstFirstName|]]`

**Comment by SamuelPlentz** [comment]
Sounds like a smart workaround, thanks for sharing. You can shorten that `|`. ;-)

**Comment by Tlon2010** [comment]
Ah, right! Thanks :-)
