### ISSUE TITLE
Quicktext does not work with TB 78.4.0 (32-Bit) on Windows 10

### ISSUE THREAD

**Issue by rhegewald-duisburg** [thundernest/quicktext#193]
Quicktext Menue does not appear when I start in TB. 
Then I reinstall from file "quicktext-3.3-tb.xpi" and its OK. But after restart of TB is gone again.
My other addons:
- Cardbook
- Provider für CalDAV & CardDAV
- TbSync

**Comment by grischahaag** [comment]
Same here with "Thunderbird 78.4.0 (64-bit) on linux (debian 10 buster)

**Comment by SamuelPlentz** [comment]
Looks related to #167, but that issue should have been solved by Quicktext 3.3.
Can you try to disable all other addons? Does it stay active after restart?
Do you use a master password?

**Comment by SamuelPlentz** [comment]
Does disabling and enabling Quicktext in addon settings reactivate it?
What does the Thunderbird error console say? (CTRL+J)

**Comment by rhegewald-duisburg** [comment]
Does disabling and enabling Quicktext in addon settings reactivate it?
Yes it does

What does the Thunderbird error console say? (CTRL+J)
No error in list

**Comment by grischahaag** [comment]
Disabling all other addons worked for me. After enabling some addons it still works. Perhaps there was a problem with an old Enigma addon.

**Comment by nklamann** [comment]
My tests show an incompatiobility with cardbook 52.5 If I disable this, it works, otherwise not.  , 52.6 same problem

**Comment by jobisoft** [comment]
The developer of cardbook is working on a new release with a different internal framework, lets wait if that fixes the issue.

**Comment by WAH67** [comment]
No other AddOn installed 
Quicktext - shows empty popup menue on click right

**Comment by jobisoft** [comment]
> No other AddOn installed
Quicktext - shows empty popup menue on click right

That is indeed a bug, but it is far from "Quicktext does not work with TB 78.4.0 (32-Bit) on Windows 10". If there is none, please create a new issue for your findings.

**Comment by SamuelPlentz** [comment]
So everyone here (beside @WAH67) has problems with an additional addon (Enigma / Cardbook).
@jobisoft Didn't you expected Thunderbird to automatically deactivate the incompatible Addons?

@WAH67 Could you please create a new issue with more informations?
Where do you right click? Does the menu entry show up? Is the Quicktext setting page working? Does the menu strip show up?

**Comment by jobisoft** [comment]
TB should now deactivate incompatible add-ons, but enigmail and Cardbook are compatible by definition but somehow do bad things which influence other add-ons. I believed the current Enigmail fixed its issue (and it is not needed at all, as it only moves the keys to the new internal openPGP function). I have no idea what CardBook is doing, but I know Philipp is switching from a very early draft of the WindowListener API to the latest one and this *might* fix this issue already.

**Comment by WAH67** [comment]
Moues at position for insertin text (signature) - click right - empty menue box 
![IMG_7583](https://user-images.githubusercontent.com/73592035/97537501-8e35aa00-19c7-11eb-9daa-8e69bf4b7196.JPG)

this finaly has as result that Quicktext is not working

**Comment by jobisoft** [comment]
You can enable the quicktext buttons, to get around that for now:
![grafik](https://user-images.githubusercontent.com/5830621/97543638-ce495c80-19c8-11eb-9f50-3dc39ba54867.png)

(See "New group" and "New template in the screenshot)

**Comment by rhegewald-duisburg** [comment]
Disabling and then enabling Quicktext in the add-on-configuration works. Otherwise my "View" doesnt show up QT:
![quicktext](https://user-images.githubusercontent.com/73489278/97554247-c5f81e00-19d6-11eb-9de6-dac3d56003a2.JPG)

**Comment by proteomis** [comment]
Under 78.4.0 (64 bits) I installed Quicktext 3.3. When I start Thunderbird, Quicktext does not work although parked as active. I have to activate the extension to make it work. Each time I start TB, I have to activate Quicktext again...
Regards

**Comment by jobisoft** [comment]
@proteomis : Any other addons installed? Does this also happen in a new profile (thunderbird -p)?

**Comment by proteomis** [comment]
Yes, a few addons. I deactivated Cardbook and restarted TB : Quicktext works. 
As mentioned above, it seems to be an incompatibility with Cardbook.
Once Cardbook is activated, and if I do not leave TB, Quicktext continues to work.
At least, I can use it!

**Comment by nklamann** [comment]
@proteomis  This works for me too. Not nice but bearable  for the time being

**Comment by jobisoft** [comment]
CardBook is close to release a new version, talk to him yesterday.

**Comment by proteomis** [comment]
Thank you!

**Comment by WAH67** [comment]
Sorry,
Still not working 
after
disable/enable
uninstall/re install

having also different menue's

![image](https://user-images.githubusercontent.com/73592035/97712118-ad673100-1ac6-11eb-8e38-679287edf5d2.png)

![image](https://user-images.githubusercontent.com/73592035/97712073-9cb6bb00-1ac6-11eb-938a-5a9ba7e3bc53.png)

**Comment by jobisoft** [comment]
The "view" menu is the "view" menu of the composer.

**Comment by WAH67** [comment]
Sorry, 

not looking at the right window - activating Quicktext within  the "new message" menu has enabled this workaround.


Thank you!

**Comment by bege10** [comment]
QT 3.3 does not work on TB 78.4.0 whether CardBook is enabled or not. QT 3.2 works almost flawlessly, only keyword plus TAB don't work. Shortcut, buttons and context menu work. Maybe an issue of the new CardBook support in the latest version?

**Comment by jobisoft** [comment]
There is no cardbook support in the released versions. Please always include which **Operating-System** you are using, if it **works in a fresh profile** and if you have the **MasterPassword prompt enabled** or not. Otherwise we will never solve this.

**Comment by jobisoft** [comment]
I fixed the missing context menu:
[quicktext_3.4pre1.zip](https://github.com/jobisoft/quicktext/files/5483786/quicktext_3.4pre1.zip)

Can you verify that its working again?

**Comment by jobisoft** [comment]
now also the button is back thanks to @SamuelPlentz 
[quicktext_3.4pre2.zip](https://github.com/jobisoft/quicktext/files/5484001/quicktext_3.4pre2.zip)

**Comment by quinze26** [comment]
The only other add-on I have is ImportExportTools. Thunderbird doesn't allow me to install QuickText as it say it's incompatible with Thunderbird 78.4.0.

**Comment by jobisoft** [comment]
It is. Just search for it in the Add-On Manger.

**Comment by rhegewald-duisburg** [comment]
I don't know how to install this zip-file quicktext_3.4pre2.zip

**Comment by quinze26** [comment]
OK, thanks. I had to remove it first, then reinstall it. No error this time.

**Comment by SamuelPlentz** [comment]
> I don't know how to install this zip-file quicktext_3.4pre2.zip

@rhegewald-duisburg: Just download the file and drag it to the addon page.

**Comment by proteomis** [comment]
Once dowloaded, rename it quicktext_3.4pre2.xpi 
Go to TB, Tools, Addons, click on the dented wheel and choose "install add-on from file".
It is better described here : https://support.mozilla.org/en-US/kb/thunderbird-add-ons-frequently-asked-questions

**Comment by rhegewald-duisburg** [comment]
It still works only when I deactiveate and activate it. Sorry

**Comment by priplatv** [comment]
MacOS Mojave 10.14.6 - TB 78.4.0 - QuickText 3.3 : **Problems**
Restart TB with all Extensions -> Not Working
Disable all Extensions except QT, then restart TB -> OK
Enable Cardbook Extension and QT, then restart TB -> Not Working
Enable all Extensions except Cardbook, then restart TB -> OK
Enable all Extensions, then disable QT only, then restart, then enable QT -> OK
Hope that this will help.

**Comment by rhegewald-duisburg** [comment]
Exactly the same happens to me. 
It really seems to be cardbook

**Comment by jobisoft** [comment]
Can you all try this one?
[quicktext_3.4pre3.zip](https://github.com/jobisoft/quicktext/files/5489117/quicktext_3.4pre3.zip)

**Comment by rhegewald-duisburg** [comment]
Fantastic!
It works with Cardbook.
Thank You so much!!!

**Comment by jobisoft** [comment]
It will be only fantastic if everybody can give me the same reply *fingers crossed*

**Comment by bege10** [comment]
> Can you all try this one?
> [quicktext_3.4pre3.zip](https://github.com/jobisoft/quicktext/files/5489117/quicktext_3.4pre3.zip)

It works on Windows 10 Professional 64 bit. After a first restart I got a shock: QT has vanished even from the Addons-Manager. New installation and a few restarts and starts later it still works. Thank you very much.

**Comment by jobisoft** [comment]
Are your QT settings still as you have set them?

**Comment by bege10** [comment]
Buttons are there twice now.
![Screenshot_256](https://user-images.githubusercontent.com/1184237/98141862-682c7000-1ec7-11eb-86a8-d94c0b5e93b7.png)

I have exported the settings from QT 3.2 and imported them to the new one. Everything seems to be there as before.

**Comment by jobisoft** [comment]
If you imported your settings and QT was working as supposed (preserving your settings), then having everything twice now is sort of expected - or did you setup QT in a fresh profile?

**Comment by priplatv** [comment]
MacOS Mojave 10.14.6 - TB 78.4.0 - QuickText 3.4pre3 : 
All Extensions enabled -> QT is working correctly as previously with all settings set as before.
Thanks a lot for your help.

**Comment by bege10** [comment]
> If you imported your settings and QT was working as supposed (preserving your settings), then having everything twice now is sort of expected - or did you setup QT in a fresh profile?

OK, I thought deleting QT 3.2 would also remove the settings. That's why I imported the settings after installing the new one. So thanks again.

**Comment by OliverBonn** [comment]
Keywords work in lowercase only, even if keyword is given as uppercase. I use SIG as keyword for my signature with TAB as trigger. SIG+TAB does nothing, sig+TAB adds my signature.
