### ISSUE TITLE
Tab order

### ISSUE THREAD

**Issue by lenhodder** [thundernest/quicktext#197]
Great add-on!  When composing an email, I enter the "to" address and enter, then press tab.  Enter subject, press tab.  Previously, this would jump you directly into the message section, ready to type "Hi, Bob..." or whatever.  Now, though, every press of tab scans through the quicktext buttons, before finally bringing you to the message section.  Can the tab order be changed to fix that?  Thanks.
![image](https://user-images.githubusercontent.com/40070071/97632101-6a468880-1a08-11eb-833e-e888ba7a6451.png)

**Comment by uncoolcentral** [comment]
Came here to say this. 
I've disabled this addon for the time being. Four extra tab keys every email composed was driving me up a wall.
UX sand in the eye.
While I understand tab-able UI elements are a feature to those with certain accessibility needs, why not have it both ways? Options: enable/disable tab control of Quicktext UI. OR, Move Quicktext UI to some other part of the workflow, vs. inserting it into EVERY email composition. 
I'm nixing Quicktext from TB until this is fixed.

**Comment by SamuelPlentz** [comment]
Could you please confirm, that the attached version solves the problem?
[quicktext taborder.zip](https://github.com/jobisoft/quicktext/files/5533141/quicktext.taborder.zip)

**Comment by SamuelPlentz** [comment]
Used a tabindex of -1 like described here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by weksupport** [comment]
It worked !



------------------------------------------------------------------------
*Van:* SamuelPlentz [mailto:notifications@github.com]
*Datum:* donderdag 12 november 2020 21:33
*Aan:* jobisoft/quicktext <quicktext@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Onderwerp:* [jobisoft/quicktext] Tab order (#197)

**Comment by lenhodder** [comment]
Yes, it seems work!  Tabbing from the subject line now takes you down to the message body.  As for issue #208, though, adding the [[CURSOR]] tag isn't working for me.  Maybe I have something wrong?  See my signature HTML below.

Thanks for your time to resolve this!

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<style></style>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
  </head>
  <body bgcolor="#ffffff" text="#000000">
    <div class="moz-signature"><font color="#000000"> Cheers.</font>
      <meta http-equiv="content-type" content="text/html;
        charset=ISO-8859-1">
      <title></title>
      <font color="#000000"><br>
      </font>
      <div class="moz-signature"><font color="#000000"> Len<br>
          Cell: xxx-xxx-xxxx<br> <br> <br>
      </div>
    </div>
    <p>[[CURSOR]]</p>
  </body>
</html>

**Comment by uncoolcentral** [comment]
FYI - disabled the new beta version because it was causing other problems, consistently. Yeah, it fixed the tab problem, but TB was riddled with warnings when trying to interact with it. ""The folder 'Drafts' cannot be compacted because another operation is in progress. Please try again later." Disabling QuickText fixes that. Enabling it brings the errors back :(

**Comment by SamuelPlentz** [comment]
I don't think the beta version introduced something like this.
Can you tell exactly what beta version you used? (there are 3 versions clipboard, focus, taborder)
Did you just disable the beta or did you downgrade to a previous Quicktext version? (which version)

Can you check if the error console (ctrl+shift+j) tells something about Quicktext?

**Comment by uncoolcentral** [comment]
It's the taborder beta.
I disabled the beta, and everything worked fine.
However, I now notice it somehow became reactivated - and now there aren't any problems. Weird. So, I'm using Quicktext 3.5 taborder and it's working fine. Strange. Disregard previous comment, I guess. If it gets buggy again, I'll check the error console and report back. Thank you.

**Comment by SamuelPlentz** [comment]
IMO should be closed, as it should be fixed by 3.5.
