### ISSUE TITLE
Bug: Quicktext does not work with Thunderbird 78.4.0 on Mac

### ISSUE THREAD

**Issue by mardugas** [thundernest/quicktext#198]
Update to Thunderbird 78.4.0 (64bit) on Mac
=> Quicktext button is not available any more.
Right-Click on new text does not work any more.

In previous versions, everything worked find.
Thanks for Your support!

**Comment by jobisoft** [comment]
can you follow the suggestions here:
https://github.com/jobisoft/quicktext/issues/193

**Comment by jobisoft** [comment]
[quicktext_3.4pre1.zip](https://github.com/jobisoft/quicktext/files/5483786/quicktext_3.4pre1.zip)

Is the context menu back with this version?

**Comment by jobisoft** [comment]
now also the button is back thanks to @SamuelPlentz 
[quicktext_3.4pre2.zip](https://github.com/jobisoft/quicktext/files/5484001/quicktext_3.4pre2.zip)

**Comment by SamuelPlentz** [comment]
Will test that later - thanks for merging everything.

**Comment by jobisoft** [comment]
I think we have to disable the new button by default and activate it after Quicktext has fired up successfully, or we could use the button to generate debug info, in case QT did NOT fire up and the user clicks the button. The button will be there regardless of the QT startup issues, as it is controlled by the manifest and not by background (which gets stuck in the erroneous case).

**Comment by jobisoft** [comment]
Can you all try this one?
[quicktext_3.4pre3.zip](https://github.com/jobisoft/quicktext/files/5489117/quicktext_3.4pre3.zip)

This may be a promising candidate.

**Comment by SamuelPlentz** [comment]
Pre3 works fine for me.
