### ISSUE TITLE
Bug: Auto-import from webserver does not work

### ISSUE THREAD

**Issue by jobisoft** [thundernest/quicktext#20]
In the original documentation, Emil Hesslow states, that the auto-import of templates/scripts during Thunderbird/AddOn start should also work from a webserver. This does not work for me. I think this is a bug.

**Comment by alie2n** [comment]
This hit me today also. Somehow the auto import function won't import from http or https urls...

**Comment by kicktipp** [comment]
I can confirm this. As my URL serves an UTF-8 file it might be related to https://github.com/thundernest/quicktext/issues/25

**Comment by kicktipp** [comment]
I debugged the situation and I get in the method importFromHTTPFile inside wzQuicktext.js an error:

> new TypeError("Components.classes['@mozilla.org/xmlextras/xmlhttprequest;1'] is undefined"

I think this is because since TB 60 nsIXMLHttpRequest is obsolete

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXMLHttpRequest#Example_code

I tried to get it working again but failed. I think we should move to WebExtensions as quickly as possible.

**Comment by jobisoft** [comment]
Would you mind testing 1.2-pre3?

[quicktext1.2-pre3.xpi](https://github.com/thundernest/quicktext/files/2718312/quicktext.zip)

**Comment by kicktipp** [comment]
I tested it and it doesn't work. I should have told you that I already tried using new XMLHttpRequest(); If you put a try/catch around it, you get the error message in the console:

```
try {
      var req = new XMLHttpRequest();
} catch(error) {
  console.log(error);
}
```
Result:

`console.log: (new ReferenceError("XMLHttpRequest is not defined", ...)`

The complete MDN documentation for writing plugins is very unclear to me. Maybe XMLHttpRequest is only available if you habe a plugin based on WebExtensions and not on the old XUL thingy.

Are there any plans to do a rewrite with WebExtensions? I really need this plugin and would spend some time helping to migrate (but I am not an expert in mozilla plugin development).

**Comment by jobisoft** [comment]
Retry:
[quicktext1.2-pre4.xpi](https://github.com/thundernest/quicktext/files/2718604/quicktext.zip)

forgot the include statement

**Comment by kicktipp** [comment]
works! Great! So simple if you know how to do it.

**Comment by jobisoft** [comment]
Thanks for pointing me in the right direction

**Comment by jobisoft** [comment]
No negative feedback -> Released
https://addons.thunderbird.net/addon/quicktext/
