### ISSUE TITLE
How to insert my signature file at the cursor (lack of a simple help example)

### ISSUE THREAD

**Issue by PhilipOakley** [thundernest/quicktext#210]
Hi, questions elsewhere have suggested that Quicktext can be used to insert my plain text signature block file at the cursor (at least that's what I'd like to be able to do.

However I can't see from the Help file / Wiki how to do that. The help assumes that one already understands what the 'templates' etc are all about.

Any guidance please (ideally as a simple use case that shows in the help wiki)?

**Comment by SamuelPlentz** [comment]
Isn't this page the one you are looking for?
https://github.com/jobisoft/quicktext/wiki/Installation-and-creating-a-template

Of course instead of writing:
```
Hi [[TO=firstname]],

[[SELECTION]][[CURSOR]]

Kind regards
[[FROM=fullname]]
```


You could also write:
```
Kind regards
John Doe
```


Or use a longer signature:
```
Kind regards
John Doe
ABC-Company
Handy: 0123 456789
E-Mail: john@example.com
```

Such simple text insertions are possible with Quicktext, but Quicktext is great at variables. (as shown in the first example)
IMO the wiki page should not be changed.

**Comment by PhilipOakley** [comment]
Hi @SamuelPlentz 

> Isn't this page the one you are looking for?
> https://github.com/jobisoft/quicktext/wiki/Installation-and-creating-a-template

Thank you for the reply. I had already been there, and it didn't enlighten me. I couldn't work out what it was trying to say beyond that, it seemed to me,  I would be forced to start all emails (apparently) exactly like that (It's a template for starting an email..). 

I'm still not sure how to do those simple text insertions you mentioned via a keystroke/sequence, hence my thought that there could be another wiki page with a real simple 'hand holding' example to get folk past whatever the conceptual block is.

**Comment by jobisoft** [comment]
I updated that page to also include references to shortcuts and keywords.
https://github.com/jobisoft/quicktext/wiki/Installation-and-creating-a-template

This is the important part:

> Alternatively, the template can be inserted by using the defined shortcut `Alt + 1 `or by typing the defined keyword `gr` followed by the keyword activator (which is Tab by default but can be changed in the general Quicktext settings.)

![](https://raw.githubusercontent.com/jobisoft/quicktext/TB78/screenshoots/settings.png)

**Comment by PhilipOakley** [comment]
Thanks for the additional documentation.

The part that confuses me, and may be others, is that the instructions imply that one should insert the template at the start of the preparation (after completing the addressees), and doesn't cover how to add, say, an extra signature block (e.g. showing a postal address & telephone) when the message is almost finished.

I'm **guessing** that one would create a second template that has the details of the postal address, mail stop and telephone - not sure if it should mention the cursor to indicate if the insert is above or below the current cursor - and then hit the short cut key to add such a signature block (maybe) _at the end_, or simply at the current cursor.

regards

Philip
