### ISSUE TITLE
usage problems with latest Tbird update

### ISSUE THREAD

**Issue by afabent** [thundernest/quicktext#216]
I've been a quicktext user for many years and previously a paid subscriber. It has become a vital part of email for me, but it has become frustrating to navigate with the latest Thunderbird. I can no longer tab through recipient and subject lines to message body without getting caught up in the collection of QT group tabs and, worst of all, I can't seamlessly drop text into the document without the same problem of getting caught in the group tabs. It is particularly troublesome for dropping links into an email because, even after all of the necessary clicking in and out of the groups and templates, any additional typing carries the link text forward unless I do a line return to break it then backspace back into my paragraph.

Is anybody else suffering from this? Is there a solution other then to revert to an old version of Thunderbird?

Thanks in advance for any help that you can offer.

**Comment by SamuelPlentz** [comment]
You are not alone: #213, #208, #197.

See new Testversion in #208.

**Comment by afabent** [comment]
Thanks so much, Samuel! I'll look into this as soon as time permits.

**Comment by jobisoft** [comment]
@SamuelPlentz : Is that testversion stable enough to be pushed upstream? Any unresolved issues?

**Comment by SamuelPlentz** [comment]
@jobisoft:
Yes it works fine for me and seems to work fine for everyone else. There was 1 complaint, but that did resolve without the need of any change.

**Comment by SamuelPlentz** [comment]
Just use the 2 pull requests to use that version.

**Comment by SamuelPlentz** [comment]
The pull request #209 is already merged, but not published.

**Comment by jobisoft** [comment]
will do in next week (a few days off)
