### ISSUE TITLE
Feature Request -- Allow text templates that are not part of a group

### ISSUE THREAD

**Issue by swbrains** [thundernest/quicktext#217]
I have about a dozen templates that I always use. They are all related, so I don't use groups.  But I must have them all in a group, so when I right-click and hover over QuickText in the menu, a second "group" menu appears and I must hover the group to get to my templates.  

I would like to be able to hover QuickText on the initial popup menu and have my list of templates appear immediately on the initial QuickText submenu rather than having to go to a group submenu to get to them.

**Comment by SamuelPlentz** [comment]
There is a setting:
Open Quicktext Settings > Common > Settings > collapse, when a group only contains one template.

Enable it and create a group with exactly one template at a time. Then the entries are there in the first level, instead of the second level.

**Comment by swbrains** [comment]
Thanks!  I have the setting "collapse group when it only contains one template" checked, but are you saying I should create a separate group for each template in order to get them to appear at the first level?

Thanks again!

**Comment by SamuelPlentz** [comment]
Yes.

**Comment by swbrains** [comment]
Thanks - will do.
