### ISSUE TITLE
Feature request -- Add setting to hide the bar with the group buttons in the TB compose message window

### ISSUE THREAD

**Issue by swbrains** [thundernest/quicktext#218]
I previously used a different TB "clippings" extension for this purpose, but it no longer works in the current version of TB.  So  out of habit I always use the right-click menu method to insert new text templates in my message.  I don't need the group button bar above the message composition area, so it would be nice if it could be optionally hidden, or perhaps settings to have the group button bar visible, the right-click menu entry visible, or both visible.

**Comment by SamuelPlentz** [comment]
1) **enable and disable right click menu:** Open Quicktext Settings > Common > Settings > Show Quicktext on right click.
2) **enable and disable Quicktext toolbar:** Open Compose Window > F10 (open thunderbird menu) > View > Quicktext

**Comment by swbrains** [comment]
Ah thanks!
