### ISSUE TITLE
QuickText and Thunderbird 84 and 85

### ISSUE THREAD

**Issue by yann-gael** [thundernest/quicktext#219]
Hi!
I'm on the beta updates channel and have been using 84 and 85 and QuickText doesn't seem to work in these versions: it appears as an add-on, it can be enabled/disabled, but, when enabled, the menu and templates do not appear. Is it maybe just for me? If not, how could I help you debug the problems?

**Comment by jobisoft** [comment]
As indicated by the ATN listing, Quicktext is compatible with TB78. There is no release version for any beta yet. Next year.
