### ISSUE TITLE
exported XML File not readable by editor 

### ISSUE THREAD

**Issue by MightyMirko** [thundernest/quicktext#22]
Hello, 

i tried to export my templates but the generated file had no ending. So i put a xml suffix to eat and tried to read it with different editors. Unfortunately, there is a space between every character.

```templates                                                                                         
 < ? x m l   v e r s i o n = " 1 . 0 " ? > 
 < q u i c k t e x t   v e r s i o n = " 2 " > 
 	 < f i l e t y p e > t e m p l a t e s < / f i l e t y p e > 
 	 < m e n u > 
 	 	 < t i t l e > < ! [ C D A T A [ N e u e   G r u p p e ] ] > < / t i t l e > 
 	 	 < t e x t s > 
 	 	 	 < t e x t   s h o r t c u t = " "   t y p e = " 0 " > 
 	 	 	 	 < n a m e > < ! [ C D A T A [ U R L _ R e g ] ] > < / n a m e > 
............
```

**Comment by jobisoft** [comment]
Yes, that is the file format used by quicktext.

**Comment by jorgk3** [comment]
It's UTF-16. Try converting that to UTF-8.

**Comment by jobisoft** [comment]
That is a better answer, thanks @jorgk3 . I just wanted to point out, that this is indeed the fileformat chosen by Eric and it will be difficult to change that.

**Comment by jorgk3** [comment]
I don't know how difficult it would be. I remember that when you were making QuickText fit for TB 60, we considered getting rid of UTF-16 in favour of UTF-8.

**Comment by jobisoft** [comment]
That is true, but than we need to detect, what fileformat the user is currently using, when reading the templates during startup and I failed on that. Since it was not needed to get quicktext running again, i kept the old format.

**Comment by jobisoft** [comment]
I made some changes and hope to have fixed this issue, can you test quicktext 1.2-pre2 (this also includes the proposed fix for [[CURSOR]]).

BEFORE installing this, make backups of your config files!

This version of quicktext should be able to read the old file format and the new one. Can you verify, that we do not run into UTF-8 encoding issues?

[quicktext-1.2-pre2.zip](https://github.com/thundernest/quicktext/files/2691156/quicktext-1.2-pre2.zip)

**Comment by aflinta** [comment]
Thanks, I've installed this extension, restarted Thunderbird and verified that version 1.2-pre2 is installed, then tried to insert my test text and unfortunately it's still not working as expected. 
I've tried using plain text file with following text: „Zażółć gęślą jaźń” and as a result inserted text was: „ZaÅ¼Ã³ÅÄ gÄÅlÄ jaÅºÅ”. Same results when inserting HTML file, which had proper unicode header.

**Comment by jobisoft** [comment]
so these issues are not related, ok, I will cont. to investigate.

**Comment by kicktipp** [comment]
I have encoding issues with 1.2-pre2 (on TB 60.2.1 on Linux/Ubuntu 18)
First I created a simple template "Mit freundlichen Grüßen". 
Then I exported this into a file. This works fine. I get an UTF-8 XML File with proper Encoding with Umlaut.

cat qt.export.xml
```
<?xml version="1.0"?>
<quicktext version="2">
	<filetype>templates</filetype>
	<menu>
		<title><![CDATA[templates]]></title>
		<texts>
			<text shortcut="" type="0">
				<name><![CDATA[mfg]]></name>
				<body><![CDATA[Mit freundlichen Grüßen]]></body>
			</text>
		</texts>
	</menu>
</quicktext>
```
file qt.export.xml
```
qt.export.xml: XML 1.0 document, UTF-8 Unicode text
```

I can use it directly and it works first. Then when I restart TB, the encoding is broken. I see in the Quicktext GUI and when using the template "Mit freundlichen GrÃ¼Ãen"

Then I deleted this template (and the group) and reimported the xml file I exported in step 2. The encoding was still broken. 

In my opinion this is even getting worse: The old format was exported and can be reimported. The new format is used by default but cannot be read again.

**Comment by kicktipp** [comment]
The reading of the file should be adapted. You changed writing the file with OS.File.writeAtomic(...) but the reading is done with scriptableinputstream and no "converting" takes place. Umlaute like Ä are written with two bytes even in UTF-8. But no converting takes place. So in line 608 (else block) you should use OSFile too? 

https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm/OS.File_for_the_main_thread#Example_Read_the_contents_of_a_file_as_text

Just an idea. I just get used to all this TB/MDN API. Can I help you coding this? Send me an email to vygen@kicktipp.de

**Comment by jobisoft** [comment]
The fix in 1.2-pre was mainly to address the readability of the saved files, which no longer uses that strange utf16 format. I did not have to change the read function, because it already contained two cases and one of them is able to read the new utf8 style.

Is that part working for you? Can you read the saved files with normal text editors?

I hoped, that the fix also fixed the encoding issue, but apparently it does not. I will look into this later, but if you find a way that still allows to read the old files (backward compatibility) and fixes the encoding issue, just send me a pull request.

**Comment by kicktipp** [comment]
https://github.com/thundernest/quicktext/pull/45

**Comment by jobisoft** [comment]
Please try the release candidate of quicktext 1.2:
[quicktext-1.2-RC.xpi](https://github.com/thundernest/quicktext/files/2722370/quicktext.zip)

**Comment by aflinta** [comment]
Great! Works perfect for me now. Thanks and Happy New Year! :)

**Comment by jobisoft** [comment]
No negative feedback -> Released
https://addons.thunderbird.net/addon/quicktext/
