### ISSUE TITLE
Possible to replace the from-field automatically

### ISSUE THREAD

**Issue by iljarogoff** [thundernest/quicktext#220]
Hi,
me wondering if it is possible to replace the from-field automatically when replying. With TheBat or Claws-Mail this is easy to handle via templates.
Example: me having my own email domain (e.g. ilja@rogoff.net). But I use for every correspondant an own mailadress (amazon@rogoff.net, shop1@rogoff.net and so on). Now I get an email from shop1@rogoff.net. With thunderbird replying to this mail, my sender email would be ilja@rogoff.net. But I want to reply via shop1@rogoff.net because the origin mail was sent to this address. Creating identities in thunderbird is not an option, because you have to select them manually on reply and I cannot maintain hundreds of identities... :) My hope is, Quicktext can make that for me?!

**Comment by weksupport** [comment]
Good idea!

TB has something :




Op 03-01-2021 om 15:45 schreef iljarogoff:

**Comment by SamuelPlentz** [comment]
Perhaps it would be possible to implement selecting existing from-profiles by Quicktext.

But using nonexisting from-profiles is IMO not feasible or planned to implement by Quicktext.

Perhaps this script can help you by creating a reply-to header from the previous to header:

``` Javascript
[[HEADER=reply-to|[[ORGHEADER=to|\n]]]]
```

**Comment by iljarogoff** [comment]
no clue of what you are talking about, sry...

**Comment by SamuelPlentz** [comment]
What do you want?
1. Do you want to select existing from-profiles you created in Thunderbird itself? (In this case you can currently select the different from-addresses when composing a new email) I think this could be possible to implement in Quicktext.
2. Do you want to select nonexisting from-profiles that do not exist in Thunderbird yet? (There is currently no way to manually select this from-addresses manually in Thunderbird) I think this should not be implemented in Quicktext.

I think a [reply to-header](https://help.returnpath.com/hc/en-us/articles/220568427-What-is-a-Reply-To-address-) could help you, as a workaround. You can create a [quicktext script](https://github.com/jobisoft/quicktext/wiki/Script-support) with the content above. In this case a `reply to`-header is automatically added. (from the `to`-address of the original email)

**Comment by jobisoft** [comment]
Quicktext is the wrong add-on for that, out of scope.
