### ISSUE TITLE
Error Message / wzQuicktext.jsm / 

### ISSUE THREAD

**Issue by orloff34** [thundernest/quicktext#222]
I have installed Quicktext 2.15 Addon with Thunderbird 68.10.0 (64-Bit) on Ubuntu 20.04.1 LTS. After installation, I found the following error message in the error console:

[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://quicktext/content/modules/wzQuicktext.jsm :: loadSettings :: line 271"  data: no] wzQuicktext.jsm:271:18
    loadSettings chrome://quicktext/content/modules/wzQuicktext.jsm:271
    <anonym> chrome://quicktext/content/main.js:24
    loadScript resource:///modules/Overlays.jsm:573
    load resource:///modules/Overlays.jsm:231
    load resource:///modules/Overlays.jsm:48
    observe chrome://messenger/content/parent/ext-legacy.js:229

**Comment by jobisoft** [comment]
That version of TB is no longer supported.
