### ISSUE TITLE
For Community scripts i offer two useful scripts IfEmpty and IfCompare

### ISSUE THREAD

**Issue by sunwayru** [thundernest/quicktext#223]
IfCompare // IfCompare(value, comparableValue, trueResult, falseResult)
return this.mVariables[0] == this.mVariables[1] ? 
  this.mVariables[2]: 
  this.mVariables[3] || '';

ussage:
[[SCRIPT=IfCompare|[[INPUT=CardType?|select|VISA;MC]]|VISA|Thanks for selecting V.I.S.A!]]

-----

IfEmpty // IfEmpty(value, emptyResult, nonEmptyResult)
return this.mVariables[0] == '' ? 
  this.mVariables[1] : 
  this.mVariables[2] || '';

ussage:
[[SCRIPT=IfEmpty|[[INPUT=CardType?|select|;VISA;MC]]|Only cash!]]

**Comment by jobisoft** [comment]
You can just add them to the wiki, it is public isn't it?
