### ISSUE TITLE
Can't hide UI in mail compose

### ISSUE THREAD

**Issue by malte-timmermann** [thundernest/quicktext#225]
iirc it was different in older versions of Thunderbird.
Now I have UI in the mail compose window that I don't want/need.
Below the subject line, there are buttons for the signatures on the left, generic stuff (Variable and Other) on the right.
I don't need/want them, but couldn't find a way to hide them.

At least in the most current, they are no longer in the tab order, which already helps a lot, thanks for that!

**Comment by jobisoft** [comment]
![image](https://user-images.githubusercontent.com/5830621/104844049-1b551480-58ce-11eb-8bc5-7bcbbea307bc.png)

Untick that to remove the quicktext bar. Does that work for you?

**Comment by malte-timmermann** [comment]
You are right, that's it!

Sorry - I looked into the addon options, and even tried to use customize toolbar, but completely missed that.

So closing this issue, thanks for your quick response!
