### ISSUE TITLE
idea: add email adresses to chose from (also BC, CC)

### ISSUE THREAD

**Issue by sunshinebard** [thundernest/quicktext#227]
it would be great, if I could also select the email that quicktext is supposed to send texts to. for example, I give a status report once in a while to the same email. I´d love to just have von field just for the email adresses for that. also for blindcopy and copy. 
regards :)

**Comment by jobisoft** [comment]
https://github.com/jobisoft/quicktext/wiki/List-of-all-supported-tags#header

**Comment by SamuelPlentz** [comment]
Create a template like this:
```
[[HEADER=to|user1@example.com]]
[[HEADER=cc|user2@example.com]]
[[HEADER=bcc|user3@example.com]]
```

IMO: Should be closed.
