### ISSUE TITLE
not working on thunderbird verstion 86.0b1

### ISSUE THREAD

**Issue by bonbonbillo** [thundernest/quicktext#231]
not working on thunderbird verstion 86.0b1

**Comment by jobisoft** [comment]
it does not claim it can. so not a bug.

**Comment by blono** [comment]
The code is almost like a template, so I have the same problem with multiple add-ons :)
I've fixed it in the repository here for your reference!
https://github.com/protz/Manually-Sort-Folders/issues/140

**Comment by jobisoft** [comment]
I am the author of that fix. I merged it yesterday into the official addon-developer-support repo. I am working on another change and when that is done, I will make a public announcement on discuss.thunderbird.net, that add-on developers should update.

**Comment by blono** [comment]
Oh my god!
There are many developers who are saved by you, thank you.
