### ISSUE TITLE
Feature Request: Update "import on startup" templates only if the remote file is reachable 

### ISSUE THREAD

**Issue by sandros87** [thundernest/quicktext#232]
Hello,
I like the feature where you can centralized templates and update them to all users if the file is stored remotely (http server). However I found a very disappointing behavior: if the http server is down or the file cannot be found the import on startup deletes the previous imported templates which doesn't make sense to me why it would be programmed like this.
Isn't it more obvious to import only if the remote xml is found?

**Comment by jobisoft** [comment]
sure, can you fix it?

**Comment by sandros87** [comment]
I'm not sure, could you point me to the part of the code where the remote import is?

**Comment by jobisoft** [comment]
https://github.com/jobisoft/quicktext/blob/TB78/chrome/content/modules/wzQuicktext.jsm#L203-L223

**Comment by sandros87** [comment]
Thanks, wow should I handle multiple import?
Since you can't really differentiate between what has been imported before and from what source it's difficult to stop a single import while following with the other(s). It will still reset everything. Does it make sense to just cancel the entire import if one URL fails to response?

**Comment by jobisoft** [comment]
What would you want? As a user? 

But I think there is a misconception: Imported files are always temporary. I do not think I actually add them to the local storage, do I? So on next restart, QT starts empty and if it cannot download the import, it has nothing to fall back to. To solve this, you would need a local sync mechanism (owncloud or something) that is keeping a local copy of the remote file and QT always uses the local copy to read from and thus does not fail on HTTP errors (which is then handled by the sync app).

**Comment by sandros87** [comment]
You are right, imported files are always temporary.
Your idea could work as a workaround, I'm considering that idea.

I'm not sure how QT works but from your explanation it would be pretty difficult to implement. As a user (as a web company we have hundreds of customers you can call "users") I would want that the URL is "stored" in QT (just the URL of the xml, not the content) and it's updated at every startup but if the import doesn't work it needs to stay stored with the previous version.
Probably it's the whole idea of "import on startup" doesn't work with my idea of "local storage from remote storage".

**Comment by jobisoft** [comment]
Something I wanted to add, but had no time, is to implement a webDav Interface, so that QT could link directly to a webDav server to read/write its templates. The permission setting of the server would then define, who can only read and who can actually change templates.

If you have resources for that, I would help to guide. I think there are webdav javascript impl one could use. I would add the needed UI for username/URL and stuff, but cannot spend much time on it.

**Comment by sandros87** [comment]
I understand, I'll think about it. Thank you.
