### ISSUE TITLE
Communiti Script -

### ISSUE THREAD

**Issue by gstummhoefer** [thundernest/quicktext#235]
Dear John Bieling, the add-on "Quicktext" is well implemented. I am currently working on scripts. I use the scripts from your wiki as orientation. I am not able to reproduce the complex scripts from 'Community Script'. Saving the originals and importing them is also unsuccessful. An XML format is required. Can you create an example in the wiki there? Thank you.

J.B. wrote: No need to import. Just create a new empty script in the UI and copy paste the script from the wiki.

Thank you for the quick reply. I tried that with the script "SignatureByFrom". It is displayed as it says in the script including ' "\n" + ' . Therefore something seems not to work.
![Screenshot 2021-02-22 160906](https://user-images.githubusercontent.com/79464452/108727179-8e365880-7528-11eb-8de2-d60a8f30f0b3.png)

**Comment by SamuelPlentz** [comment]
Have a try to insert the code into a script on the page "Scripts" (or "Skripte" in German).
You currently insert the code into a template on the page "Template" (or "Vorlagen" in German).

To access the script from a template write something like
`
[[SCRIPT=SignatureByFrom]]
`
