### ISSUE TITLE
TypeError when using FROM tokens on Thunderbird 78.7.1

### ISSUE THREAD

**Issue by matthijs-va** [thundernest/quicktext#236]
Thanks for this great plugin, but unfortunately I'm experiencing following TypeError after upgrading to Thunderbird 78.7.1:

```
Uncaught (in promise) TypeError: manager.escapedVCardToAbCard is not a function wzQuicktextVar.jsm:785:24
    getcarddata_from chrome://quicktext/content/modules/wzQuicktextVar.jsm:785
    process_from chrome://quicktext/content/modules/wzQuicktextVar.jsm:816
    get_from chrome://quicktext/content/modules/wzQuicktextVar.jsm:367
    parseText chrome://quicktext/content/modules/wzQuicktextVar.jsm:170
    parse chrome://quicktext/content/modules/wzQuicktextVar.jsm:112
    insertBody chrome://quicktext/content/quicktext.js:527
    insertTemplate chrome://quicktext/content/quicktext.js:372
    updateGUI chrome://quicktext/content/quicktext.js:278
```

This appears to affect all templates that use FROM tokens like `[[FROM=firstname]]`.

**Comment by jobisoft** [comment]
Confirmed. Reason:
https://phabricator.services.mozilla.com/D62393

**Comment by jobisoft** [comment]
[quicktext_3.6b3.zip](https://github.com/jobisoft/quicktext/files/6055480/quicktext_3.6b3.zip)
Is it fixed in this version? This version also moves the options from the tools_menu into the add-on manager.

**Comment by matthijs-va** [comment]
Yes, the new version fixes this issue. Thanks!

**Comment by SamuelPlentz** [comment]
IMO should be closed.
