### ISSUE TITLE
insert html code via script

### ISSUE THREAD

**Issue by userQAY** [thundernest/quicktext#239]
i have a script for signature selected by the account: 
__
var account = this.mQuicktext.get_from(["email",","]);
if (account == "abc@qwe.cz") 
  return "[[TEXT=GHF|**ABC podpis MAIN**]]";
else if (account == "bcd@qwe.cz")
  return "[[TEXT=KMC|S pozdravem]]";
else if (account == "drt@qwe.cz" | account == "info@abc.cz") 
  return "[[TEXT=Překlady|S pozdravem]]";
else 
  return "[[TEXT=Privat|user]]";`
__
and the bold template (ABC podpis MAIN) is in html. 
I want to insert it as HTML not as TEXT.

Please any advice

**Comment by SamuelPlentz** [comment]
Currently a template (that executes the script) can only be of type "Text" or "HTML". You can specify this by using the dropdown "Insert as Text/HTML" below the template text.

So in my opinion set that option to HTML and convert the other signatures also to HTML files. Most text signatures can be converted to HTML only by adding `<br>` to the end of the line. Probably you have to handle special chars like converting `<` to `&lt;`.

**Comment by jobisoft** [comment]
Correct. Thanks @SamuelPlentz
