### ISSUE TITLE
Feature request: Mark templates with keyword or shortcut with tag/color

### ISSUE THREAD

**Issue by userQAY** [thundernest/quicktext#240]
I have a lot of templates ...
when I manage keywords and shortcuts, I have to manually go through all the templates and check if they contain keywords / shortcuts.
It would be easier if each template had an asterisk or a different tag (or color, etc. ) if it contained keywords / shortcuts
Or 
one tag for a keyword and another for a shortcut or to display them exactly

**Comment by jobisoft** [comment]
Shortcuts are already displayed in the template list (in the quicktext settings window). Is it there that you want to see the keywords as well?

**Comment by userQAY** [comment]
I dont see it. see picture.
<img width="258" alt="quick" src="https://user-images.githubusercontent.com/62791675/140335649-c4ffbce1-54df-4b0e-ae00-9b2c40009d4d.png">

**Comment by userQAY** [comment]
<img width="233" alt="quick2" src="https://user-images.githubusercontent.com/62791675/140335943-0feb101a-d743-4664-8f0a-c16929708ac1.png">
