### ISSUE TITLE
please, how can i work with INPUT output in scripts ? 

### ISSUE THREAD

**Issue by userQAY** [thundernest/quicktext#241]
please, how can i work with INPUT output in scripts ? 

script process INPUT at the end (with return)
I would like to use the INPUT tag as input for variables for further processing . Is it possible? 
Please help.

**Comment by SamuelPlentz** [comment]
You can do it like this:

Template "InputTest":
```
[[SCRIPT=InputProcessing|[[INPUT=Amount|select|12 $;14 $;22 $]]]]
```

Script "InputProcessing":
``` Javascript
return mVariables[0].replace(' $', '');
```

In this case the selected amount of the INPUT Tag (for example "14 $") is given to the script "InputProcessing". The script currently only replaces a " $" there. So only "14" is added to the email.

**Comment by jobisoft** [comment]
Correct. Thanks @SamuelPlentz
