### ISSUE TITLE
wrong **i18n** in Russian locale

### ISSUE THREAD

**Issue by ashed** [thundernest/quicktext#242]
You paste wrong **i18n** in Russian locale in messages.json
I fixed this below
en: {
  "extensionDescription": {
    "message": "Adds a toolbar with unlimited number of text to quickly insert. It is also possible to use variables like [[TO=firstname]]. With settings for everything."
  }
}
{
  "extensionDescription": {
Добавляет панель инструментов с неограниченным количеством текста для быстрой вставки. Также можно использовать такие переменные, как [[TO=firstname]]. С настройками для всего.
  }
{
}

**Comment by ashed** [comment]
And I fixed i18n in chrome Russian locale
add in attachement:
quicktext.dtd
quicktext.properties

Add it please

[chrome.zip](https://github.com/jobisoft/quicktext/files/6272127/chrome.zip)

**Comment by jobisoft** [comment]
Can you turn that into a pull request please?
