### ISSUE TITLE
Comment in [[FILE=C:\file.txt]]

### ISSUE THREAD

**Issue by CamielBouchier** [thundernest/quicktext#243]
First of all: This is a *great* add-on to thunderbird!

I tend to use a lot of times [[FILE=...]] in templates (it allows me to maintain html snippets in standard editors).

I was wondering if there is any combination that works as comment delimiter, such that it is actually not introduced in the html. 
(now I use , but that ends up in the final mail. It doesn't show of course, but it is not nice either when finding it in the source).

Camiel B.

**Comment by CamielBouchier** [comment]
Now I use was meant to read as the html commenting pair, but it is, uh, reduced to html comment ;)

**Comment by SamuelPlentz** [comment]
Currently only `<!-- comment -->` works, but this way it ends up in the final mail as you already mentioned. (for geeks that really care - usually no one should notice it; IMO if you do not disclose sensitive information's like passwords this should work well)

Probably I would create one big file to gather comments for all files:
`comments.txt`:
```
file.txt
comment1
comment2
comment3

file2.txt
comment1
```

or create a comment file for each file:
`file - comments.txt`:
```
comment1
comment2
comment3
```

Whats the use case of having comments in the file?

If it is only a short description of the used HTML tags it should be a short separate document like this:
```
<b>text</b> - makes text bold
<i>text</i> - makes text italic
```

**Comment by CamielBouchier** [comment]
@SamuelPlentz ,

Thanks for your feedback. As  you say, this is not the biggest deal but still not nice. If it were to avoid I would like to have following comments not propagating to the mail. It explains my 'use cases':


```
<!--
Notes for Outlook:
  - margin is not supported.
  - border-radius is not supported. (hence the png in 'round' format rather than css).
  - Float width and position CSS styles applied to div's do not work in Outlook => Hence table to make the division :(
-->

```

or

```

<!--
vim: syntax=html ts=4 sw=4 sts=4 sr et columns=160
-->
```

Camiel B.

**Comment by jobisoft** [comment]
I added an optional parameter to the FILE tag, using

 [[FILE=path/to/file.html|strip_html_comments]]

should do what you need now. Unreleased, need to build from source to test.
