### ISSUE TITLE
Does not work tag [[HEADER = name | value]] 

### ISSUE THREAD

**Issue by SergeKasperovich** [thundernest/quicktext#247]
Hello,
does not work tag [[HEADER = name | value]].
I cannot figure out if I am using it correctly. Or is the tag no longer supported? 

Quiqtext 0.9.11.7 
![изображение](https://user-images.githubusercontent.com/82955693/115825617-5c4f4e80-a412-11eb-803e-7978e8bc9490.png)

**Comment by SamuelPlentz** [comment]
Works fine here.

Make sure you use QuickText version 3.6. There should be a additional tab named "scripts" on the settings page. So your version is outdated.

**Comment by SergeKasperovich** [comment]
Thank you. 
My company uses an old version of Thunderbird, so the old version of Quicktext was installed.

**Comment by SergeKasperovich** [comment]
Your answer helped me.
