### ISSUE TITLE
TB 78 - CC field obscured

### ISSUE THREAD

**Issue by everette00** [thundernest/quicktext#249]
Hi,

When the CC field is active in TB 78, and you make a modification to either the TO or CC recipients, the viewport containing the fields shrinks and obscures the field.

![tb](https://user-images.githubusercontent.com/10836772/117165768-c9100480-ad93-11eb-8015-bc4a2e1e088a.png)

**Comment by daelrum** [comment]
not happening to me on w10 and TB 78.10

**Comment by everette00** [comment]
> not happening to me on w10 and TB 78.10

As far as I know this problem exists in the W8 version, as this is what I'm using. Without plugin that viewport does shrink ever so slightly when the CC field is available and you add a pill to either fields. Not sure if that impacts this bug hunt at all.

Thanks!

**Comment by jobisoft** [comment]
Reopen if it still happens in 78.11.
