### ISSUE TITLE
Bug: Does not properly encode UTF8 files

### ISSUE THREAD

**Issue by aflinta** [thundernest/quicktext#25]
When inserting signature (TXT or HTML) form properly formatted file in UTF8 standard, all accented characters are replaced by garbage. So instead of "zażółć gęślą jaźń" I'm receiving "zaÅ¼Ã³ÅÄ gÄÅlÄ jaÅºÅ". This makes this addon unusable in my language.

**Comment by kicktipp** [comment]
I can confirm it. When I loaded my UTF-8 file it does not show "Umlaute" like "ä". I converted the file to iso   `xmllint --encode ISO-8859-1 qt.xml > qt.iso.xml`
Then it worked again.

**Comment by aflinta** [comment]
> I can confirm it. When I loaded my UTF-8 file it does not show "Umlaute" like "ä". I converted the file to iso `xmllint --encode ISO-8859-1 qt.xml > qt.iso.xml`
> Then it worked again.

Thanks, unfortunately my characters are covered by ISO-8859-2 which is also not supported like UTF. Seems western encoding is hard coded...

**Comment by jobisoft** [comment]
Can you check this:
https://github.com/thundernest/quicktext/issues/22#issuecomment-448261928

**Comment by jobisoft** [comment]
It took a while to get behind this issue and it is not related to the changes in #22 (that just changes the encoding of the quicktext config files from utf-16 to utf-8).

The issue does not arise during read of XML files (like quicktext config files), as they are piped through an XML parser, which takes care of the encoding: If no encoding field is present in the XML header - as with quicktext config files - it is interpreted as utf-8. You can actually change the encoding of the (new) quicktext config files, if you also add the correct encoding header. But I do not see any reason to do so.

*Edit: I am no longer sure about the above statement.*

The problem described in this issue arises, if the user is using the FILE or the URL tag or manually imports a text or html file.

So I propose the following fix strategy:
1. Add encoding attribute to the FILE and URL tags, so the user can specify the correct encoding
2. Prompt the user for the correct encoding in case of manually adding text (maybe try to detect utf-8 and skip the prompt in that case)

Would that solve the problem?

**Comment by jobisoft** [comment]
I dropped the idea of the additional encoding attribute but try to detect wether the file is UTF-8 or not. If not, I fallback to the hardcoded ISO-Latin-1 decoding as before.

Please try the release candidate of quicktext 1.2:
[quicktext-1.2-RC.xpi](https://github.com/thundernest/quicktext/files/2722370/quicktext.zip)

**Comment by jobisoft** [comment]
No negative feedback -> Released
https://addons.thunderbird.net/addon/quicktext/

**Comment by leonardoferro** [comment]
I used Notepad++ to convert de xml file frum UTC-8 to  **UCS-2 Little Endian** and imported to Quicktext.

**Comment by jobisoft** [comment]
Quicktext now only supports UTF8 or - if  that does not work - falls back to ISO-Latin-1. There is no support for any other Encoding.
