### ISSUE TITLE
[Community-Scripts Feature Request] Script to change spellchecker language

### ISSUE THREAD

**Issue by mMuck** [thundernest/quicktext#251]
Hi.
I'm using QuickText for years now and are very happy! Thanks.

I was wondering if it would be possible for a script to change the spellchecker language. I write in three different languages and it always needs some clicks to change the input language. If I/users could use a keyword for this, would be very helpful.
The scripts have that scope or are they isolated from this specific actions at the compose dialog?

Greetings

**Comment by jobisoft** [comment]
Scripts would be able to do that. I currently do not have the resources to add this.

**Comment by mMuck** [comment]
This was a question about the script scope and ability. So thanks for that answer. Question solved.

Where could be placed an open issue with a "help wanted"/"good first issue" tag? Would this be related to the quicktext issues? Or do you want as much as possible issues closed? Sorry, I have the same resources problem 😉.

**Comment by jobisoft** [comment]
Since scripts can do that, this is not an "issue" for Quicktext and I think I do not want out of scope issues sitting around. But on the other hand, where should you post it? So if you give it a title which clearly identifies it as a request to the community to come up with a script to do what you seek, you can create on here in the issue tracker. I may create a special label for that.

**Comment by jobisoft** [comment]
I created a Commuity Script label, do not know if you can pick that or if I have to do that later, lets see...

**Comment by mMuck** [comment]
The scripts are in the wiki of the same repo. To avoid the work of dividing them to a different repo with separate issue tracker, this would be the easiest solution. Thanks.

@SamuelPlentz @weber-s You were involved with some scripts. Would this be a topic for you?

**Comment by SamuelPlentz** [comment]
This should work: https://github.com/jobisoft/quicktext/wiki/Script:-SpellChecker
Could be closed now.

**Comment by jobisoft** [comment]
Thanks. Samuel At one point you will have to give me your paypal donation url :-)

**Comment by mMuck** [comment]
Sorry for the late reply. Some minutes ago I found some time to check this out.
@SamuelPlentz THIS IS GREAT. YOU are great. Fettes Lob!!! 😀
@jobisoft You can mention this as a great example in the store description. And you are right, he should mention a donation URL. Hopefully he has an account. If not now he has a reason. 😉

**Comment by SamuelPlentz** [comment]
@mMuck: Lieber Markus, thanks a lot for the donation. Nice that you know my Father! Have a nice day. Greetings.
@jobisoft: Markus forced me to have a paypal account 😉 - I added a link to my profile "organisation".
