### ISSUE TITLE
HTML Conditional Comments Messed Up

### ISSUE THREAD

**Issue by hegdesaspect** [thundernest/quicktext#253]
Consider the following content:

```html
<!--[if mso]>
<table style="width: 648px;" border="0">
      <tbody>
        <tr>
          <td>
<![endif]-->

<div style="font-family: &quot;Consolas&quot;; max-width: 648px;">TEST</div>

<!--[if mso]>
          </td>
        </tr>
      </tbody>
    </table>
<![endif]-->
```

The above HTML template gets inserted as:

```html
<!--[if mso]>
<table style="width: 648px;" border="0">
      <tbody>
        <tr>
          <td>
<![endif]--><!--[if mso]>
          </td>
        </tr>
      </tbody>
    </table>
<![endif]-->
    <div style="font-family: &quot;Consolas&quot;; max-width: 648px;">TEST</div>
```

Looks like a bug, unless I am missing something.

**Comment by jobisoft** [comment]
That is strange. Do you want it to evaluate the conditional html comments? Is it an included FILE= or the template itself?

**Comment by hegdesaspect** [comment]
On 03-Jun-2021 07:50 pm, John Bieling wrote:
> That is strange. 

Indeed!

> Do you want it to evaluate the conditional html
> comments? 

No. All I expect Quicktext is to insert the HTML as it is. Instead,
Quicktext is re-ordering, nullifying the logical flow.

Do not evaluate. Just insert as it is. I want the destination e-Mail
client to process it conditionally while rendering the HTML.

> Is it an included FILE= or the template itself?

Its the template itself. Nit an included file.

Let me know if you need more information.

--
Supra

**Comment by SamuelPlentz** [comment]
Could confirm that scrambled text gets inserted.

The problem shouldn't be inside of Quicktext, but in the Mozilla source instead:
I added an `console.log(aStr);` directly in front of `editor.insertHTML(aStr);`. There is still the unchanged text in the log entry.

So `editor.insertHTML(aStr);` this is the root of the scrambling.

https://github.com/jobisoft/quicktext/blob/187d0f463b4da2daa1583f3d9a3e60da13101495/chrome/content/quicktext.js#L539-L547

**Comment by jobisoft** [comment]
I do not see how I can fix that :-(

**Comment by SamuelPlentz** [comment]
Do you know the source of `editor.insertHTML(aStr);`?
If yes, one could look at it and possibly find a workaround.

Tried to search `searchfox.org`, but haven't been successful.

**Comment by hegdesaspect** [comment]
Hmm. Thanks so much for triaging this. You are right. I tested this using the "Insert HTML" native feature of Thunderbird. The resulting HTML is again scrambled. I shall file a bug on Thunderbird to fix `insertHTML`. Or at least understand their philosophy of what can be expected out of `insertHTML`. May be they meant only pure HTML tags and no scripts, and they may have a different API to insert scripts?

Lets close this bug for now. I now have a clear reproducer independent of Quicktext.

**Comment by SamuelPlentz** [comment]
How do you insert HTML using native Thunderbird? I am not aware of that feature?
Can you insert a link here if you file a bug in Thunderbird? I am curious about what triggers the behavior.

**Comment by hegdesaspect** [comment]
> How do you insert HTML using native Thunderbird? I am not aware of that feature?

When you write message in HTML mode, under the `Insert` menu, there is `HTML...`. See below:

![Insert HTML Menu](https://user-images.githubusercontent.com/84836773/139635368-2bc04202-62fa-4115-b9c3-b5ec0247572d.png)

And then click on `HTML...`, following window opens:

![Insert HTML Tool](https://user-images.githubusercontent.com/84836773/139635599-82187b74-b07f-447c-a1ee-584efb5a7441.png)

> Can you insert a link here if you file a bug in Thunderbird? I am curious about what triggers the behavior.

Sure. Stay tuned.
