### ISSUE TITLE
TB78: Keywords no longer work

### ISSUE THREAD

**Issue by ciderpunx** [thundernest/quicktext#254]
I use the keywords feature extensively, so I can type _r and get an outline reply of an email for example. 

This seems to have stopped working after an upgrade to TB78. 

You would make me very happy if you were able to fix.

**Comment by jobisoft** [comment]
This does not seem to be broken. This still works with the current version on ATN (3.6) as well as with the current development version (3.7b1)

Could you check if your keyword activation key is still what it used to be?

**Comment by ciderpunx** [comment]
Thanks - that was the problem, it had reverted to tab rather than space, all working as expected now :-)
