### ISSUE TITLE
Codepage of inserted html file

### ISSUE THREAD

**Issue by userQAY** [thundernest/quicktext#255]
I have a html file used as my signature, all works fine.
I want insert the same file with FILE tag 

[[FILE=d:\Dokumenty\work\Podpisy\filename.html]]

and there are 2 problems: 

1/ pictures are not inserted
2/ Codepage is "broken" = text isn unreadable  (especially  "ěščřžýáí"  chars)

Please, what can i Do to fix it? 

<img width="458" alt="htmlfileQ" src="https://user-images.githubusercontent.com/62791675/123069415-0ba8a180-d413-11eb-9ace-638854a419f9.png">

**Comment by jobisoft** [comment]
Change the file to be utf8.

**Comment by userQAY** [comment]
Thanks, it works fine.  What can i do with blank frames instead pictures? Is there any way? 
Thanks a lot.

**Comment by jobisoft** [comment]
I need more context. The images are data URLs or somewhere on your computer? I guess you have to convert them to data urls and include them directly in the src tag, so no external resources are needed.

There is the IMAGE tag, which does that for you, maybe it works even in an included file
https://github.com/jobisoft/quicktext/wiki/List-of-all-supported-tags#image

**Comment by userQAY** [comment]
yes, images are on computer. Code is: ` <img src="file:///D:\Dokumenty\0Práce\Podpisy/partnerslogonew.jpg" width="268" height= "76" border="0">`    
Pleasae what do you mean with  "convert them to **data urls** and include them directly in the src tag," this? 
I search a way to insert pictures without edit source code (insert IMAGE tag) , = use original html file

**Comment by jobisoft** [comment]
> I search a way to insert pictures without edit source code (insert IMAGE tag) , = use original html file

If you want to reuse the same file for your signature and your template, than you have to switch to using a data url. Infos here:
https://ezgif.com/image-to-datauri

**Comment by userQAY** [comment]
Thanks a lot!!
