### ISSUE TITLE
Feature request: Use one Template in another

### ISSUE THREAD

**Issue by dflox** [thundernest/quicktext#256]
Maybe I'm just missing something and this is already possible but it would be great if there was a tag to insert texts of other templates into a different template. There are some parts of templates I need to change on regular basis and therefore it would be great if i could only change it in one place. Maybe the possibility to define your own variables could also help there.

Propably this already works somehow with keywords. If thats the case I would be happy to learn how it works but from what I could find in the wiki thats not possible yet.
In any case: Thank you so much for this great add-on!

**Comment by SamuelPlentz** [comment]
Have a look at the [text tag](https://github.com/jobisoft/quicktext/wiki/List-of-all-supported-tags#text).

**Comment by dflox** [comment]
ok wow, I'm just blind - thanks a lot
