### ISSUE TITLE
Position of save button

### ISSUE THREAD

**Issue by ghost** [thundernest/quicktext#257]
I'd like to suggest to move the save button to the right below the configuration of a template or add another one there.

**Comment by SamuelPlentz** [comment]
Duplicate: #237.

**Comment by jobisoft** [comment]
@SamuelPlentz : Using this to contact you (github has no personal message support, right?) Sorry @benks-io for spamming your inbox.

Have you tested Quicktext in TB91? I updated it a few days ago and it should work as before. Negative feedback in a new issue would be nice.

QuickText 91: https://addons.thunderbird.net/addon/quicktext/versions/

You can get the beta of TB 91 on the bottom right of www.thunderbird.net.

If you want to check which add-ons will work BEFORE updating your profile to TB91, use this in Tb78:
https://addons.thunderbird.net/addon/addon-compatibility-check/

If you start thunderbird using the -p option, you can of course create a new profile just for TB91.

**Comment by SamuelPlentz** [comment]
@jobisoft : Thanks for providing a new version. I never used Thunderbird Betas and I don't plan to do so, sorry.
I am a first day updater (if a new final version is available) though. I will surely report back, if I had any problems.

Perhaps we should create a pinned issue for Thunderbird 91, that could be unpinned / closed 2 weeks after the final release.
It could contain all information you posted here.

**Comment by jobisoft** [comment]
I uploaded the new version to ATN, so you will get it automatically once you updated to TB91. We will handle any fallout in new issues.

John
