### ISSUE TITLE
Can't insert templates TB 78.13.0 (Ubuntu)

### ISSUE THREAD

**Issue by regenpfeifer** [thundernest/quicktext#258]
Hello,

unfortunately Quicktext doesn't work with TB 78.13.0 for Linux (Ubuntu).

When I'm trying to insert a template (by context menu or keyboard shortcut) **nothing happens** and I'm getting the following error messages from the console window:

```
uncaught exception: ParserError: invalid line (no token ";" or ":") "null" wzQuicktextVar.jsm:785:24
    getcarddata_from chrome://quicktext/content/modules/wzQuicktextVar.jsm:785
    process_from chrome://quicktext/content/modules/wzQuicktextVar.jsm:816
    get_from chrome://quicktext/content/modules/wzQuicktextVar.jsm:367
    parseText chrome://quicktext/content/modules/wzQuicktextVar.jsm:170
    parse chrome://quicktext/content/modules/wzQuicktextVar.jsm:112
    insertBody chrome://quicktext/content/quicktext.js:527
    insertTemplate chrome://quicktext/content/quicktext.js:372
    updateGUI chrome://quicktext/content/quicktext.js:278

Uncaught (in promise) 
Exception { name: "NS_ERROR_XPC_JS_THREW_JS_OBJECT", message: "ParserError: invalid line (no token \";\" or \":\") \"null\"'ParserError: invalid line (no token \";\" or \":\") \"null\"' when calling method: [nsIMsgVCardService::escapedVCardToAbCard]", result: 2153185308, filename: "chrome://quicktext/content/modules/wzQuicktextVar.jsm", lineNumber: 785, columnNumber: 0, data: null, stack: "getcarddata_from@chrome://quicktext/content/modules/wzQuicktextVar.jsm:785:24\nprocess_from@chrome://quicktext/content/modules/wzQuicktextVar.jsm:816:23\nget_from@chrome://quicktext/content/modules/wzQuicktextVar.jsm:367:20\nparseText@chrome://quicktext/content/modules/wzQuicktextVar.jsm:170:62\nparse@chrome://quicktext/content/modules/wzQuicktextVar.jsm:112:19\ninsertBody@chrome://quicktext/content/quicktext.js:527:28\ninsertTemplate@chrome://quicktext/content/quicktext.js:372:18\nupdateGUI/<@chrome://quicktext/content/quicktext.js:278:67\n", location: XPCWrappedNative_NoHelper }
wzQuicktextVar.jsm:785
```
Is there any way to fix these errors?

Thank you very much,
regenpfeifer

**Comment by jobisoft** [comment]
Which version of quicktext (version number) ?

**Comment by regenpfeifer** [comment]
Version 3.6, I have also deinstalled and reinstalled the addon.

**Comment by narcisgarcia** [comment]
I've tried two instances of M. Thunderbird (versions 78.12 and 78.13 respectively) in GNU/Linux and both don't allow to install current version of Quicktext because "version not compatible".

**Comment by jobisoft** [comment]
Did you try to install them from the recommended list? That is an ugly bug in TB:
https://github.com/thundernest/addons-server/issues/173

Just search for quicktext in the input field and install from the search results. That should work.

**Comment by jobisoft** [comment]
@regenpfeifer : What is your status? Does it work with QuickText 3.6 downloaded from addons.thunderbird.net?
https://addons.thunderbird.net/thunderbird/downloads/file/1018660/type:attachment/quicktext-3.6-tb.xpi?src=version-history

Have you moved to TB91 in the meantime?

Is this failing for *any* template (even a very simple one), or just a specific template?
