### ISSUE TITLE
Thunderbird 91 is out ... Quicktext is not working 👎 

### ISSUE THREAD

**Issue by TobiasHeuken** [thundernest/quicktext#261]
Thunderbird 91 is out ... Quicktext is not working 👎 

Can you upgrade it?

**Comment by jobisoft** [comment]
It is.

**Comment by ioweb-gr** [comment]
Hi @jobisoft  in my case it's not working correctly with the latest update. Version 4.1 of the addon on Thunderbird 91.0.3

![image](https://user-images.githubusercontent.com/20220341/131231262-3421b952-aaa5-4c04-b08e-dc26ad7800df.png)

I can see the icon on top right but it only opens for editing. There's no longer the quicktext dropdown inside the composition window.

**Comment by SamuelPlentz** [comment]
Do you see the Quicktext entry (and its subentries) in the context menu upon right clicking in the message part?
Could you activate the Quicktext bar by pressing "F10" > "View" > "Quicktext"?

**Comment by ioweb-gr** [comment]
On right click no

![Screenshot_2021-08-29-15-13-41-90_8404db57de60b5d3d1c69008b20f5296](https://user-images.githubusercontent.com/20220341/131249966-8901ad4d-5fd8-406a-87c6-5b1d75ef6c34.jpg)

On view, toolbar no

![Screenshot_2021-08-29-15-15-46-10_8404db57de60b5d3d1c69008b20f5296](https://user-images.githubusercontent.com/20220341/131250037-7e776b21-6e2a-4968-ac9d-abd14bab007d.jpg)

F10  doesn't seem to do anything

**Comment by SamuelPlentz** [comment]
Is there anything in the error console? (Ctrl+Shift+J)
Does it work with an empty Thunderbird profile, when only Quicktext is installed?

**Comment by ioweb-gr** [comment]
Ah nice thank you the error console showed a javascript error from another plugin and disabling that one fixed the issue :)

**Comment by jobisoft** [comment]
> 
> 
> Ah nice thank you the error console showed a javascript error from another plugin and disabling that one fixed the issue :)

Which one? I am Thunderbird's main add-on coordinator and would like to fix that, as such an error could cause issues with other add-ons as well.

Thanks!

**Comment by ioweb-gr** [comment]
It was ThunderHTMLedit

**Comment by jobisoft** [comment]
Did you Update ThunderHTMLedit? Because it does work for me. Strange

**Comment by ioweb-gr** [comment]
It said that no updates are found for any of my extensions so I think it's updated. Let me try and uninstall / reinstall

**Comment by ioweb-gr** [comment]
Uninstalling and reinstalling did the trick. Not sure why it didn't find any updates though

**Comment by catalizaweb** [comment]
Same problem, and it has been fixed disabling ThunderbirdHTMLedit addon.

**Comment by gresio64** [comment]
After the last update 91.0.3 does the module does not work, how can it be solved?
If uninstalling and reinstalling, I lose all my data from my configurations created?
