### ISSUE TITLE
shortcuts without numbers

### ISSUE THREAD

**Issue by garnajee** [thundernest/quicktext#262]
Hi,

can we use shortcuts without numbers? Or can you add this functionality?
For example: ALT+& instead of ALT+1, as I'm on a laptop with french keyboard, and to use the shortcuts I need to do ALT+shift+& to do ALT 1, so this is a little bit boring...

Thanks in advance

**Comment by jobisoft** [comment]
WebExtensions do not support single key shortcuts. This is not yet a full WebExtension, but I will not introduce a feature which I have to break when making the final switch.
