### ISSUE TITLE
Use the OneDrive variable in quicktext Import on startup.

### ISSUE THREAD

**Issue by deef73** [thundernest/quicktext#264]
I want to use the %OneDrive% variable in to quicktext to Import the templates on startup.

I have succesfully exported a shared-template.xml

This template is loading when I open in explorer this file:
%OneDrive%\quicktekst\shared-template.xml

When I use this variable in to import on startup, the templates are not loaded in to quicktext.   When I use the hard path like:
C:\Users\Deef\OneDrive\quicktekst\shared-template.xml

The templates are loaded, but it is not loaded with other users among the company.

Thank you, 

Deef

**Comment by jobisoft** [comment]
I have no idea how to do that. You have to specify the full path.
