### ISSUE TITLE
TypeError: this.mWindow.getCurrentIdentity is not a function

### ISSUE THREAD

**Issue by x011** [thundernest/quicktext#265]
Hi,
I'm use quicktext extensively for my work, but since TB 91.2.0 (updated last night)  I'm getting a JavaScript error:

Window title: "`[Javascript Application]`"

```
There was an error in your Quicktext script: get_domain
TypeError: this.mWindow.getCurrentIdentity is not a function
Line 223: undefined
```

`get_domain` script:

```
var to = this.mQuicktext.get_from(["email"]);
var mailArr = to.split('@');
var mailHost = mailArr[1];
return mailHost ;
```

Any idea how to solve this?
Thank you.

PS: To continue working normally, I've downgraded TB to 91.0

**Comment by jobisoft** [comment]
The line `this.mWindow.getCurrentIdentity` is not present in the quicktext add-on. It is also not present in the script you showed. It works for me in 91.2.0.

I have no idea.

**Comment by x011** [comment]
If you've no idea, imagine me.
Thanks anyway.

**Comment by SamuelPlentz** [comment]
Works fine here.

Have a look here: https://github.com/jobisoft/quicktext/wiki/Troubleshooting
Especially: Are you using the latest Quicktext version?

**Comment by SamuelPlentz** [comment]
Seems to be fixed here:
https://github.com/jobisoft/quicktext/commit/e1658b6ae21700cd8575cd3e6d1249bf824c0891#diff-c0742cccd7e45d256c412f4ff41ed921d55e8bc2c23854679edb6dab29753bf1

**Comment by x011** [comment]
@SamuelPlentz:

```
Version
4.1
Last Updated
October 7, 2021
```

**Comment by x011** [comment]
I've updated TB to the latest version (again) and it now works normally, go figure...
Tks for the support.
