### ISSUE TITLE
New Feature in Community Script 

### ISSUE THREAD

**Issue by Black4Killer** [thundernest/quicktext#266]
Is it possible to make a script so that when you click it, it changes our account with the email to the other account? Example:
I have a added 2 accounts in Thunderbird Private and Office.
After that im click Write button from my Private account but when i click a button from QuickText addon then i want to switch to my Office account in this window and automatically type a topic and words.

**Comment by SamuelPlentz** [comment]
This should work: https://github.com/jobisoft/quicktext/wiki/Script:-Identity
Could be closed now.
