### ISSUE TITLE
Template with variable in 91.2.1

### ISSUE THREAD

**Issue by radeks11** [thundernest/quicktext#267]
Today my TH has been updated to version 91.2.1 (64bit). I noticed templates with variable (eq. [[TO=firstname]]) stopped to work.

**Comment by ch-sander** [comment]
same here

**Comment by SamuelPlentz** [comment]
Cannot reproduce. Can you have a look here: https://github.com/jobisoft/quicktext/wiki/Troubleshooting

**Comment by ch-sander** [comment]
Works again! I did not change anything though.

**Comment by SamuelPlentz** [comment]
@jobisoft: These "work again without changes" messages are stacking up. Any idea what the cause of it could be?

**Comment by jobisoft** [comment]
I have no real idea, maybe the add-on did not update during the upgrade but only a day later, when the usual update check was performed? Another thing I see is that some add-ons fail to start, if the user has offline mode enabled.

**Comment by kennethvistabee** [comment]
Same issue here, templates without variable works fine, but not with. TB 91.2.1 on mac.
Edit: Idiot me forgot to update the addon.

**Comment by jobisoft** [comment]
@SamuelPlentz : Thanks for that great Troubleshoot page. Awesome!
