### ISSUE TITLE
problems since 91.2.1 (64-Bit)

### ISSUE THREAD

**Issue by coderfls** [thundernest/quicktext#268]
Since the new version there are some problems.
I Click on SAVE in the config dialog did not work. the dialog will not be closed and nothing is saved.
Some old setting are set to default: for example: I set RETURN for activating key word and this is now empty
The first time of a windows-session the TB-session the quicktext bar is not shownin the editor windows. I must close the window and open it again. After I reopen TB all is fine

**Comment by SamuelPlentz** [comment]
Can you have a look here: https://github.com/jobisoft/quicktext/wiki/Troubleshooting

**Comment by hubbi959** [comment]
Same here. Also the templates are not shown when I open Quicktext in the main window of TB, but are shown when opening in a message editor. Saving of options also do not work. I do not want to set up a new TB profile, because it has many accounts, calenders and addons installed.

**Comment by jobisoft** [comment]
But could you *test* if it works in a new profile?

**Comment by hubbi959** [comment]
Sorry, I didn't find the time to create a new profile. But from a review on TBs Add-On page a user (KidLark, in German) recommended to downgrade to 4.0. I've done this and it works fine again. 👍

**Comment by SamuelPlentz** [comment]
Are you really sure that version 4.1 is bad and 4.0 is fine?
The only change made was [this one](https://github.com/jobisoft/quicktext/commit/62da80424f1d28f8215b660809acaa846c0fe4d9). And this doesn't look related to saving options.

@hubbi959: You don't even need to create a fresh profile. Try disabling other addons (see [step 2 here](https://github.com/jobisoft/quicktext/wiki/Troubleshooting))

BTW: TB 91.2.1 and QT 4.1 working fine here.

**Comment by jobisoft** [comment]
I assume, if you remove 4.0 again and install 4.1 again, then it will work again. There is *something* happening on the initial update from TB78 to TB91, which is not completing the add-on update but puts it into some limbo state.
