### ISSUE TITLE
QuictText Toolbar not showing in New Message Window in Thunderbird 91.3.0

### ISSUE THREAD

**Issue by joaquinbarranco** [thundernest/quicktext#269]
QuickText option is displayed in main window / Tools / Quicktext, but QuickText Toolbar is not shown in the New Message Window in TB last realease.

**Comment by jobisoft** [comment]
Do you have the online-offline prompt enabled during Thunderbird start? That is currently killing a lot of add-ons.

**Comment by joaquinbarranco** [comment]
Thanks for answering.

No, I always have Thunderbird working online. I get to see the QuickText icon next to the Attach button on the right of the New Message window, but if I click it, it opens up the QuickText options window, but QuickText toolbar is missing and can't find anywhere in Thunderbird to visualize it.

**Comment by joaquinbarranco** [comment]
I just updated QuickText extension and it works again !!! Thanks !!!

**Comment by joaquinbarranco** [comment]
I just updated QuickText extension and it works again !!! Thanks !!!
