### ISSUE TITLE
Bug: [CURSOR] tag not working in TB 60.0

### ISSUE THREAD

**Issue by jobisoft** [thundernest/quicktext#27]
The CURSOR tag is not working in TB 60.0, on windows, on mac and probably also not on linux

**Comment by pjzzzz** [comment]
Not working on TB 60.2.1 (32-bits) either.

**Comment by ssdf1** [comment]
The code responsible for this functionality is here:

https://github.com/thundernest/quicktext/blob/73ff720353ce1e408047a50db9915ceb46761a0c/chrome/content/quicktext.js#L559

What is strange is that when you place a Breakpoint at this very line and run under Debugging tools then Quicktext works perfectly fine ([[CURSOR]] text is removed and caret is placed in correct place). If you place the breakpoint **inside** while() clause then it is never hit. So the code looks correct, but apparently there is some race condition that causes Find() not to find anything if it is run at "full speed" without being stopped by debugger.

**Comment by jobisoft** [comment]
Jorg has pointed out some changes toFind(): https://github.com/thundernest/quicktext/pull/26#issuecomment-415209093

Maybe that helps to fix this?

**Comment by ssdf1** [comment]
Yes I have seen that. Since it works under debugger, when single stepping, to me it looks like TB60 bug, not quicktext bug.

**Comment by jobisoft** [comment]
Thanks for spending time on this. The test suite seems to work, maybe it would be helpful to start from there? Maybe it is due to searching inside the editor? If this is a Thunderbird bug, would you be able to write a test which fails, so it can be filed es a bug?

**Comment by dartcafe** [comment]
I notice a strange behavior of this feature. If I enter the key word (hi) followed by ab TAB following text is inserted
```
Hi Joe,

[[CURSOR]]

regards

(caret stands here)
```

When I enter some text and insert the key word on top of the mail text in front of the already entered text, it works.

```
Hi Joe,

(caret stands here)

regards
some senseless text
```

Maybe that helps

**Comment by ssdf1** [comment]
Yes it seems that finder.Find is using some old (pre-insert) content of the buffer. That is why it is able to find [[CURSOR]] in the OLD text, but not able to find it in newly inserted text. 
Some kind of "update buffer" or "flush" would need to be called before finder.Find so it uses new buffer content.  

Maybe just calling      
```
if (aHandleTransaction) editor.endTransaction();
```

BEFORE finder.Find would fix the issue?

**Comment by jobisoft** [comment]
can you post a linenumber, where this Needs to be added, I would like to try...

**Comment by jobisoft** [comment]
I did some more research and I can confirm that if I step through the code using the build in debugger of TB60, the tag is found. This is a simplified version of the code in question:

```
var editor = GetCurrentEditor();

editor.beginTransaction();
editor.insertText("Test [[CURSOR]] Test");
editor.endTransaction();

if (editor.selection.rangeCount > 0) {
  var newRange = editor.document.createRange();
  newRange.selectNodeContents(editor.document.getElementsByTagName("BODY")[0]);
  var startPt = newRange;
  var endPt = newRange;
  Services.console.logStringMessage("[Content] " + newRange.toString());

  var finder = Components.classes["@mozilla.org/embedcomp/rangefind;1"].createInstance().QueryInterface(Components.interfaces.nsIFind);
  finder.caseSensitive = true;
  finder.findBackwards = false;

  let foundRange = finder.Find("[[CURSOR]]", newRange, startPt, endPt);
  if (foundRange === null) {
      Services.console.logStringMessage("[Found] " + " --- ");
  } else {
      Services.console.logStringMessage("[Found] " + foundRange.toString());
  }
}
```

Observations:
1. the [Content] console dump always returns the current value of the editor + "Test [[CURSOR]] Test", so the tag is added and it is there!
2. if the editor was empty before calling this code, the tag is not found and " --- " is logged
3. if the editor was not empty before calling this code and already contained the search tag, it is found
4. if debugging is used and the code gets single-stepped, observation 2 changes and the tag is found.

So this is some sort of race condition between editor.insertText() and the finder actually being able to find the inserted text.

Environment: TB 60.2.1 (32bit) on Windows 10 (64bit)

@jorgk3 Any idea?

**Comment by jorgk3** [comment]
Nice job :-) - With this result you could refer the matter to the Core::Editor team, but that won't get you a quick fix. So I suggest to add some wait, like we always do in similar situations. Wrap the finder stuff in

setTimeout(function () {
  var finder = ...
  finder.caseSensitive = true;
  finder.findBackwards = false;
  let foundRange = finder.Find("[[CURSOR]]", newRange, startPt, endPt);
}, 0);

You can change 0 to some other value. If 0 works, you can omit it since it is the default.

**Comment by ssdf1** [comment]
In line 524 https://github.com/thundernest/quicktext/blob/73ff720353ce1e408047a50db9915ceb46761a0c/chrome/content/quicktext.js#L524 you can try to add these lines
```
if (aHandleTransaction) 
{
  editor.endTransaction(); /* end previous transaction to "flush buffer" */
  editor.beginTransaction(); /* reopen transaction */
}
```

**Comment by jobisoft** [comment]
@ssdf1 It looks like that does not help :-( The code above already ends the transaction before searching. I added another begin/endTransaction around the find code, but it does not work.

**Comment by ftoledo** [comment]
TB 63.0 (amd64) on Debian GNU/Linux also affected.

**Comment by vexillia** [comment]
Confirmed on Ubuntu 18.04 with TB64.  64 bit.

**Comment by vexillia** [comment]
Do you have any avenues of approach to solving this problem?  Seems that everyone is a bit stuck.

**Comment by jobisoft** [comment]
I think we need to follow [Jorgs suggestions](https://github.com/thundernest/quicktext/issues/27#issuecomment-429149693), but I have not had the time to get started with any of them.

**Comment by qbnm** [comment]
Confirmed on macOS Mojave 10.14 (18A391) and Thunderbird 60.3.3 (64-Bit).

I'd buy a 🍺for a fix!

**Comment by bgeiring** [comment]
as @jorgk3 wrote the solution is to use setTimeout around the cursor find in `chrome/content/quicktext.js`

I tested it with serveral timing values but to use setTimeout() without the timing parameter is sufficient 
that the code is executed after the [[CURSOR]] text is placed and the cursor can be moved to that
location.

```javascript
parseCursorTag: function(aEditor, aSearchRange)
  {
    var startRange = aEditor.document.createRange();
    startRange.setStart(aSearchRange.startContainer, aSearchRange.startOffset);
    startRange.setEnd(aSearchRange.startContainer, aSearchRange.startOffset);
    var endRange = aEditor.document.createRange();
    endRange.setStart(aSearchRange.endContainer, aSearchRange.endOffset);
    endRange.setEnd(aSearchRange.endContainer, aSearchRange.endOffset);

    var finder = Components.classes["@mozilla.org/embedcomp/rangefind;1"].createInstance().QueryInterface(Components.interfaces.nsIFind);
    finder.caseSensitive = true;
    finder.findBackwards = false;
    setTimeout(function() {
      var found = false;
      while ((foundRange = finder.Find("[[CURSOR]]", aSearchRange, startRange, endRange)) != null)
      {
        found = true;
        aEditor.selection.removeAllRanges();
        aEditor.selection.addRange(foundRange);
        aEditor.selection.deleteFromDocument();
        startRange.setEnd(foundRange.endContainer, foundRange.endOffset);
        startRange.setStart(foundRange.endContainer, foundRange.endOffset);
      }

      if (!found)
      {
        aEditor.selection.removeAllRanges();
        aEditor.selection.addRange(endRange);
      }
    });
  }
```

**Comment by jobisoft** [comment]
nice, can you turn that into a pull request?

**Comment by ssdf1** [comment]
Funnily the [[CURSOR]] works with existing quicktext.js, if only you add a single space 
in the email before you call it. 

So the problem can also be fixed by adding that space programmatically. For example the following lines can be added in insertBody, right after line 497 call to GetCurrentEditor: https://github.com/thundernest/quicktext/blob/73ff720353ce1e408047a50db9915ceb46761a0c/chrome/content/quicktext.js#L497

```
         // BEGIN: quick and dirty hack to make [[CURSOR]] work
          var keepRange = editor.selection.getRangeAt(0).cloneRange();

          editor.insertText( " " ); // insert single space at the end
       
          editor.selection.removeAllRanges();
          editor.selection.addRange(keepRange);
          // END: of hack
```

I've been using it for a while and although it is ugly it works.

**Comment by bome** [comment]
@bgeiring: I can confirm that it works -- when the text editor is current focused. If the cursor is, e.g. on the TO field, [[CURSOR]] is still not found.

**Comment by ssdf1** [comment]
But [my hack](https://github.com/thundernest/quicktext/issues/27#issuecomment-446745452) works even if cursor is in the "TO:" field :-)

**Comment by bome** [comment]
@ssdf1 : I can confirm that your hack works (even without @bgeiring's fix), but it also does not work for me when the TO: field is focused :(

**Comment by ssdf1** [comment]
Should work - [[CURSOR]] text is removed from text area and although focus obviously stays at TO: field, when you TAB to get to text edit the cursor is positioned in correct place.

**Comment by jobisoft** [comment]
I tried both and I have the same results as @bome : If I actively set focus to "subject" or "to" and than select a template, the [[CURSOR]] is not replaced. But PR #42 is the best solution we have yet! 

@bgeiring Could you programmatically set focus to the edit area before inserting the text? If a CURSOR field is present, the user actually WANTS to switch focus I think. Objections?

**Comment by bgeiring** [comment]
@jobisoft I updated the PR #43 to include a focus switch to the edit area.

**Comment by bome** [comment]
@bgeiring this addition (to move focus) works like a charm! Thanks!

**Comment by jobisoft** [comment]
This is quicktext 1.2-RC:
[quicktext-1.2-RC.xpi](https://github.com/thundernest/quicktext/files/2722370/quicktext.zip)

It includes the patch from @bgeiring (#43). Please test it on your systems and report back if it does NOT work. (Please do not flood the issue with "it works" posts, use the silent emoticons for that please)

@bgeiring Thanks!

**Comment by jobisoft** [comment]
No negative feedback -> Released
https://addons.thunderbird.net/addon/quicktext/
