### ISSUE TITLE
Feature Request: Support for async scripts

### ISSUE THREAD

**Issue by FrankHuxol** [thundernest/quicktext#271]
I am currently trying to create a template to support me with the following process:
* I'll copy the address of a particular issue tracker (JIRA). This adress might look like: {host}/browse/{project}-{number}
* The template should then paste something like this into my browser: &lt;a href="{copiedUrl}"&gt;{project}-{number}: {summary of the ticket}&lt;/a&gt;

The summary is not part of the URL, but there is a REST API I can use to retrieve that information (inside a JSON response).

I had the idea to use scripting for that purpose and came up with the following:
The template just uses my script:
`[[SCRIPT=Jira2Link]]`
And the script should ideally do something like this:
```
fullLink = this.mQuicktext.get_clipboard();
// TODO: check for sanity
splitByPath = fullLink.split('/');
issue = splitByPath[splitByPath.length-1]

// prepare an API request to get all fields in JSON format
restApiRequestUrl = fullLink.replace('browse','rest/api/latest/issue')

// await requires the calling method to be async, so this will not work right now
response = await this.mQuicktext.get_url(restApiRequestUrl);
// probably do something with converting the response to a JavaScript object - untested
// responseAsObject = JSON.parse()

return '<a href="' + fullLink + '">' + issue + ': ' + responseAsObject.summary + '</a>'

```

Sadly, I've not been able to deal with the "await" part. Without the await, I only get a promise (since the request is not yet finished), but with await, I get the error:
`SyntaxError: await is only valid in async functions, async generators and modules`

Any hints on a different approach are welcome, too.

Btw: I tried to split overall approach up into two scripts combined by one template, but that did not work either - something like this:
[[SCRIPT=InsertAsLink|[[URL=[[ConvertBrowserUrlToApiRequest]]]]]]

**Comment by jobisoft** [comment]
Why do you need to await the string.replace()?

**Comment by FrankHuxol** [comment]
Sorry, I put my await in the wrong line. Of course, the result of get_url needs to be awaited. I changed the pseudecode above respectively

**Comment by FrankHuxol** [comment]
By the way: I noticed another issue in my plan. I'd need to be able to send authentication information via the get_url - and I did not find any info about if or how that could be done (BasicAuth should be supported by the ticket system I want to query). However, that would be another feature request.

That said: This somehow lowers the priority of that request, since even if you find the time to implement this feature request, it would not work for me. So in conclusion: I'll try to figure out a work around, possibly using two or more [[Input]]s and having to copy the data I need from the ticketing system manually.

**Comment by jobisoft** [comment]
You could include the auth data in the request as https://user:pass@your.endpoint.server

**Comment by FrankHuxol** [comment]
Of course! Thanks for the hint. I tried this approach right now. Interestingly this works in Postman, but neither in Chrome nor in Firefox. A quick test in Quicktext via `[[URL=https://{username}:{password}@{host}/rest/api/latest/issue/{issue}|data]]` also did not return anything (nothing was inserted). Chrome and Firefox return here a 401 with data "Login Required" (and some more JSON things around that message).

When testing the regular browsing URL `[[URL=https://{username}:{password}@{host}/browse/{issue}]]`, at least there is something inserted, but I was not authenticated. The login-page was returned. Same for Chrome and Firefox. It appears, that the server does not support preemptive auth via this method. However, I've been able to use the REST-API as well as the "browser-API" via manually providing the "Authorization"-Header (`Authorization: {Base64-Encoded username and password}`). So it might be, that - theoretically speaking - this might also work from Thunderbird/Quicktext, if there would be a way to somehow specify headers to be used during a request.

**Comment by jobisoft** [comment]
Ah, Mozilla removed support for inline auth for sec reasons.

I think you have to go the full length and use fetch() to connect your REST API endpoint and provide the headers. But that returns you to the req to support await.

**Comment by FrankHuxol** [comment]
In case anyone comes by later and wonders on how to call fetch from within Quicktext: That's how it could be done `mWindow.fetch('url', params)`. (Of course, right now you don't get the actual data back due to asynchronisity of the request).

**Comment by jobisoft** [comment]
Looks like you know what you are doing. This is where the change must happen, I guess:
https://github.com/jobisoft/quicktext/blob/TB91/chrome/content/modules/wzQuicktextVar.jsm#L587

In the evaled string you need to define the run function async, which should make the return value a Promsie. If that happens, you need to await the call to evalInSandbox and follow the chain upwards and make process_script and all of its parents in the execution chain async as well and await each call.

If you get that going, please file a pull request.

**Comment by FrankHuxol** [comment]
I've never worked on a thunderbird plugin yet, but I'll give it a go - if time permits.

**Comment by FrankHuxol** [comment]
Took me quite some time to fiddle around with all those promise + async stuff - but I've got a reviewable piece here: #272

A subtle change might be, that if you do not provide any return value, you now get "undefined". Previously, I think it was at least an empty string.

Update: Actually, I think with the second changelist that behaviour is restored.

**Comment by FrankHuxol** [comment]
Actually, that behavior could be kind of obfuscating a not-so-obvious user error. Would you mind, if instead of just returning nothing we would return something like 'no return statement in script'? I updated the pull request respectively. If you don't like that, just mention it

**Comment by SamuelPlentz** [comment]
Probably its better discussed here - Sorry for my crosspost.

Regarding: `return 'no return statement in script';`
IMO we should not break backward compatibility. So I would prefer `return '';` instead.

If we stick to the new error message, we should localize it like here:
https://github.com/jobisoft/quicktext/blob/187d0f463b4da2daa1583f3d9a3e60da13101495/chrome/content/modules/wzQuicktextVar.jsm#L598

**Comment by FrankHuxol** [comment]
Same here: reverted the code to `return ''`

Providing a reasonable error message in case "nothing happens when I execute my script" could be handled as a different feature request

**Comment by FrankHuxol** [comment]
I've been using the code from the pull request #272 for a few weeks now without issues with my templates (but I don't have that many templates).

Any news on this request (objections, questions, etc)?

**Comment by jobisoft** [comment]
I will review it this week.

**Comment by SamuelPlentz** [comment]
IMO this should be pushed.

**Comment by SamuelPlentz** [comment]
One of my scripts returned `[object Promise]` in Quicktext 5.2 due to this issue.
It looks like this:
``` javascript
              this.mQuicktext.get_script(["CleanSubject"])
var output1 = this.mQuicktext.get_script(["customScript1"])
var output2 = this.mQuicktext.get_script(["customScript2"])

return ausgabe1 + ausgabe2;
```

Had to change it like this:
``` javascript
              await this.mQuicktext.get_script(["CleanSubject"])
var output1 = await this.mQuicktext.get_script(["customScript1"])
var output2 = await this.mQuicktext.get_script(["customScript2"])

return ausgabe1 + ausgabe2;
```

**Comment by jobisoft** [comment]
Should I back out the patch?

**Comment by SamuelPlentz** [comment]
No, I think it is fine.

I think not much people use something like this and there is an easy fix.

Or do you think there is anything possible to support async and non async scripts at the same time?

Otherwise we have to stick with the patch and fix upcoming problems.

**Comment by jobisoft** [comment]
so script includes now always have to be awaited, if you have time, could you update the wiki?

**Comment by SamuelPlentz** [comment]
Added it to the bottom of this page:
https://github.com/jobisoft/quicktext/wiki/Script-support

This issue can be closed now.

**Comment by SamuelPlentz** [comment]
IMO close.
