### ISSUE TITLE
Embedded HTML Image is not working

### ISSUE THREAD

**Issue by Krishna5907** [thundernest/quicktext#273]
Embedded HTML Image is not working

**Comment by SamuelPlentz** [comment]
Should work like this:
`[[IMAGE=C:\Images\Test.png]]`

Make sure to change the template type to `insert as: HTML`

See documentation here:
https://github.com/jobisoft/quicktext/wiki/List-of-all-supported-tags#image

**Comment by SamuelPlentz** [comment]
Close as solved.
