### ISSUE TITLE
Template categories not visible TBird 91.3

### ISSUE THREAD

**Issue by karlbu** [thundernest/quicktext#274]
This morning I realized that the Quicktext categories, that normally display when creating a new email, are not visible in Thunderbird 91.2 (32-bit).  See attached screen shot.

[](ur
![Quicktext screen shot](https://user-images.githubusercontent.com/12497047/142442760-12a29d4e-4a95-4d23-b918-33e548543b7f.jpg)
l)

I re-installed QT 4.1, and also rebooted my Windows PC, to no avail.
Windows 11 (64-bit).

**Comment by jobisoft** [comment]
Is it enabled?
![grafik](https://user-images.githubusercontent.com/5830621/142443753-d0fb92f5-ab2f-45b2-b8a6-bd93312d4b1d.png)

**Comment by karlbu** [comment]
Oops.  Somehow it got disabled.  I apologize.
Karl Buhl
