### ISSUE TITLE
Replace TO field (e-mail address) from template

### ISSUE THREAD

**Issue by Feri-6** [thundernest/quicktext#275]
How can I **replace** TO field from a template. If I use [[HEADER=to|xxx@gmail.com]] variable it adds the e-mail address into the TO field, but not replaces it (when I answer to an e-mail).

Earlier I use the following script:
this.mWindow.document.getElementById('addressCol2#1').value="xxxx@gmail.com";
this.mWindow.document.getElementById('addressCol2#1').onchange();

But it does not work since TB v78.

**Comment by SamuelPlentz** [comment]
Have a look here:
https://github.com/jobisoft/quicktext/issues/178#issuecomment-719816541

**Comment by SamuelPlentz** [comment]
Added the community scripts: [AddRecipients](https://github.com/jobisoft/quicktext/wiki/Script:-AddRecipients) and [RemoveRecipients](https://github.com/jobisoft/quicktext/wiki/Script:-RemoveRecipients).

Should be closed now.

**Comment by jobisoft** [comment]
Is RemoveRecipients TB102 only, or does it work in TB91 as well?

**Comment by SamuelPlentz** [comment]
The old version `pill.remove();` worked for TB 91. Not sure if the new `win.addressRowClearPills(toRow);` does.

**Comment by SamuelPlentz** [comment]
Seemed to have changed:
https://phabricator.services.mozilla.com/D122620
I will change the wiki.

**Comment by SamuelPlentz** [comment]
Can be closed now.
