### ISSUE TITLE
QuickText 4.1 not working on Thunderbird 91.4

### ISSUE THREAD

**Issue by tanograsa** [thundernest/quicktext#282]
I can create groups and templates and they also appear where they should do, that is on any new message window and by right clicking on any spot and selecting "QuickText". But clicking on a template has no effect: the text is not inserted, nothing happens.
Things I tried so far (not in this order):
- Uninstalling and reinstalling QuickText
- Uninstalling and reinstalling Thunderbird
- Deleting the main profile and creating a fresh one
- Deactivating all other extensions (safe mode, anyway I only have one more extension installed: Quick Folders)
Any help would be much appreciated.

**Comment by SamuelPlentz** [comment]
There is no problem for me with TB 91.4.1 and QT 4.1.

Thats our [Troubleshooting](https://github.com/jobisoft/quicktext/wiki/Troubleshooting) site, but you already tried many points of it. Could you check the error console? Could you report your OS?

How exactly did you create the fresh profile?
Could you create a fresh profile and only install the quicktext addon and only add one template inserting `Test`. If that would fail, it really would puzzle me.

**Comment by tanograsa** [comment]
Thank you very much for you reply. I'm attaching the errors found in my error console. My OS is Win7 64bit. I created a fresh profile when asked to at the beginning of the new TB installation. And I did forgot to say that when I re-installed TB I did not installt any other externsion but QT at first.
![Senza titolo-1](https://user-images.githubusercontent.com/78316834/147356066-108c5941-a90e-41d9-92e9-473bc9f41e89.jpg)

**Comment by tanograsa** [comment]
I installed the latest portable version of TB (91.4.1) and created a fresh profile with an e-mail ccount I never used before with TB. I installed only QT as an addon, created just a "test" template and... the problem persists. I'm attaching the errors log. I really don't know what is going on.
![Senza titolo-1](https://user-images.githubusercontent.com/78316834/147362487-bbab6abe-e010-4dbe-bc10-d9df197a805b.jpg)

**Comment by jobisoft** [comment]
The portable TB is not an official release. Can you test an official release from thunderbird.net?

**Comment by tanograsa** [comment]
Hello jobisoft, thank you very much for your answer. I forgot to mention that installing TB portable was just an additional test, As you can easily find out by reading the first posts, the problem started with an official release. An error log following the test with the official release is also attached.

**Comment by Kunzol** [comment]
Maybe this helps ...

I tested QuickText 4.1 with the following Thunderbird versions and it works for me:

- Linux Thunderbird 91.5 
- Windows Thunderbird 91.6.1 (64-bit)

**Comment by jobisoft** [comment]
There is a bug on fresh profiles, which prevents add-ons to start if no account has been created. Did you skip the account setup wizard, or is your new profile fully setup?

**Comment by SamuelPlentz** [comment]
Quicktext works fine with TB 102. Close?

**Comment by jobisoft** [comment]
Given that the reporter went silent, yes.
