### ISSUE TITLE
QuickText 4.1 not working on Thunderbird 97.0+

### ISSUE THREAD

**Issue by ThePirat91** [thundernest/quicktext#283]
Hello, please update the addon to be compatible with the next beta branch of Thunderbird (97.0+).
Thank you

![image](https://user-images.githubusercontent.com/17300013/149292783-06b24ea7-01ad-45f1-bddc-040008e597ac.png)

**Comment by VictimAlex** [comment]
I have the same problem :(

**Comment by SamuelPlentz** [comment]
Should be possible now - close.
