### ISSUE TITLE
Variables - [[TO=firstname]] does not work if only one name.

### ISSUE THREAD

**Issue by bmartinsen** [thundernest/quicktext#284]
When an email comes with only one name in the senders address, the [[TO=firstname]] does not add any name to the Quicktext reply. QuickHack - you can instead use [[TO=fullname]] and the name will work in the reply. But if the sender has first and last name in their address and you only want the first name in your reply... you have to manually select and delete the last. Kinda annoying :0(

**Comment by SamuelPlentz** [comment]
IMO this behavior is intended.
First it tries to get the values from the adressbook. As a workaround you should fill in the firstname and the lastname in the contact there.
If that not is possible it tries to parse the mailaddress. It has to decide if a standalone name is a firstname or lastname. I think it would be wrong to use the entry as firstname and as lastname as well. There are several problems if it tries to parse the sending adress.

**Comment by bmartinsen** [comment]
Thank you for your clarification on how Quicktext sees things Samuel.

As is typical - user needs are likely a challenging variable. In this instance, the sender is replying to a form so they don't exist in an address book. I am fine with this simple hack tho. Quicktest is a very cool extension.
Q: When you say, it tries to parse the "mailaddress," do you mean the address in the email's header or from a filled-in form? I'm wondering if it's possible to parse other form fields, specifically their "city." And I cannot find info about how to set up custom parameters. Any advice you could offer would be very welcome ;0)

Thank you again Samuel,
I hope you enjoy an interesting day!

**Comment by SamuelPlentz** [comment]
Could you show an example what such an email looks like?
Is the city embedded in the message text?

The asked behaviour above (combining firstname and lastname) and also the parsing of the city could probably be solved with community scripts. Have a look here:
https://github.com/jobisoft/quicktext/wiki/Community-scripts
https://github.com/jobisoft/quicktext/wiki/Script:-ToNickname
https://github.com/jobisoft/quicktext/wiki/Script:-GetMailBody

I don't know how much you are into programming.

**Comment by bmartinsen** [comment]
Thank you Samuel!

Unfortunately, the script examples don't look like they will work for this issue.
Here is an example. I'd like to pull the "City" from it for the reply.

Name: Jabba Hutt
Email: Jba@yahoo.com
City: Viera
StateProv: Florida

BTW. I am not a real programmer. Just a simple web coder :0)

Thanks again Samuel.

**Comment by SamuelPlentz** [comment]
The first script can be adjusted like that to use the lastname if the firstname is not set:
```
var data = this.mQuicktext.process_to(mVariables);

// use lastname if firstname is not available
if(typeof data['firstname'] == 'undefined') {
  data['firstname'] = [];
}
for(var i = 0; i < data['lastname'].length; i++) {
  if(typeof data['firstname'][i] == 'undefined' || data['firstname'][i] == '') {
    data['firstname'][i] = data['lastname'][i];
  }
}

if(typeof data['firstname'] != 'undefined') {
  if(mVariables.length < 1) mVariables[0] = ", ";
  return data['firstname'].join(mVariables[0].replace(/\\n/g, "\n").replace(/\\t/g, "\t"));
} else return "";
```
Save this skript as `ToFirstOrLastname`
Use it in a template like this:
```
Hello [[SCRIPT=ToFirstOrLastname]]
```

The second script could be used like this:
```
var editor = this.mWindow.gMsgCompose.editor;
var text = editor.outputToString('text/plain', 0);

var city = text.match(/City: (.*)/);

if(city != null) return city[1];
return '';
```
Save this skript as `GetCity`
Use it in a template like this:
```
You are from [[SCRIPT=GetCity]].
```

**Comment by jobisoft** [comment]
Thanks @SamuelPlentz for helping out!

**Comment by bmartinsen** [comment]
OMG -
You are THE KING OF THE WORLD Samuel!
Your scripts are perfect and work like a treat.
THANK YOU for your super-expertise and kind help.
Be well -

**Comment by SamuelPlentz** [comment]
Added the community scripts: [GetLinepart](https://github.com/jobisoft/quicktext/wiki/Script:-GetLinepart) and [ToFirstOrLastname](https://github.com/jobisoft/quicktext/wiki/Script:-ToFirstOrLastname).

Should be closed now.
