### ISSUE TITLE
Switching templates

### ISSUE THREAD

**Issue by ramarrone** [thundernest/quicktext#285]
If I once use a template, e.g., with additional information. I can't switch back to a template with no additional information.
I think because the additional text cannot be deleted by the add-on. This would be a nice feature.

**Comment by SamuelPlentz** [comment]
What do you mean with additional information?
Could you give an example how your template looks like?

Can't you just use undo (ctrl+z)?

**Comment by SamuelPlentz** [comment]
Close as there is no feedback for 4 Months?
