### ISSUE TITLE
get Computername

### ISSUE THREAD

**Issue by MurphyBerlin** [thundernest/quicktext#286]
hey,

Is it somehow possible to get the username from the computer via script?

Regards

**Comment by SamuelPlentz** [comment]
Have a look here: #162

**Comment by MurphyBerlin** [comment]
sry i dont understand this :S

**Comment by SamuelPlentz** [comment]
No it's not possible, for a workaround see the linked post.

**Comment by jobisoft** [comment]
@MurphyBerlin : The `computername` script is a custom script, which is added to each of your Thunderbird installations, which has the name of "that" computer hardcoded. You can then use 

```
var computername = this.mQuicktext.process_script(['computername']);
```

in other scripts to get that information. This way, complex scripts can be shared without the need to change the hardcoded computer name on each system.

**Comment by Alfred-Peters** [comment]
As long as the username is stored in the environment variable USERNAME, you can read it (according to [this Comment](https://github.com/jobisoft/quicktext/issues/162#issuecomment-1120410064)) with this script:

```
function getEnv(name) {
  try {
    var environment = Cc["@mozilla.org/process/environment;1"].getService(
      Ci.nsIEnvironment
    );
    return environment.get(name);
  } catch (e) {
    return("Error getEnv(): "+ e);
  }
  return undefined;
}
var myUsername = getEnv( "USERNAME" );
return myUsername;
```

**Comment by SamuelPlentz** [comment]
Can confirm the code working within a community skript. Should be closed.

**Comment by SamuelPlentz** [comment]
Added the community script: [GetEnvironmentVariable](https://github.com/jobisoft/quicktext/wiki/Script:-GetEnvironmentVariable). Thanks Alfred Peters.
