### ISSUE TITLE
Feature Request: access browser.*/messenger.* inside template script

### ISSUE THREAD

**Issue by endedasende** [thundernest/quicktext#289]
Greetings,
firstly many thanks to author and to maintainer of quicktext!

I am using this extension for simple but effective ticket managment. 
I respond to new email with a template, that calls script, which adds ticket number to subject and also opens new compose window with ticket number in subject.

This worked just fine, but now i cannot open new compose window anymore...

```
var url = encodeURI('mailto:?Subject='+s[0]);

//this no longer works
this.mWindow.open(url, '_self');

//this no longer works
var messenger = Components.classes["@mozilla.org/messenger;1"].createInstance();
messenger = messenger.QueryInterface(Components.interfaces.nsIMessenger);
messenger.launchExternalURL(url, '_self');
```

After some searching i see 2 solutions, either `browser.windows.openDefaultBrowser(url)` or `browser.compose.beginNew()`
but i cannot access `browser.*` from inside template scripts.

I have naively tried adding quicktext.js as background script and adding browser via init function, but this is not ok...
```
  "background": {
    "scripts": [
      "/chrome/content/scripts/preferences.js", 
      "background.js",
      "/chrome/content/quicktext.js"
    ]
  },

//add browser var
gQuicktextVar.init(window,browser);

```

So how do i tackle this problem?

Having full `browser.*` (or restricted) support available from template scripts would be great.

**Comment by Alfred-Peters** [comment]
> This worked just fine, but now i cannot open new compose window anymore...
> 
> ```
> var url = encodeURI('mailto:?Subject='+s[0]);
> 
> //this no longer works
> this.mWindow.open(url, '_self');
> ```

It seems that only one parameter is missing there. This one works here:
```
var url = encodeURI('mailto:?Subject='+this.mVariables[0]);
this.mWindow.open(url,'_self',
    "chrome,extrachrome,menubar,resizable,scrollbars,status,toolbar");
```

**Comment by SamuelPlentz** [comment]
Can confirm the code working within a community skript. Should be closed.

**Comment by jobisoft** [comment]
I keep it open, because using webExt API is indeed something which could be useful, as it is easier.

**Comment by SamuelPlentz** [comment]
Added the community script: [OpenComposeWindow](https://github.com/jobisoft/quicktext/wiki/Script:-OpenComposeWindow).

**Comment by endedasende** [comment]
Wow time flies...
Thanks everyone for support, open compose window works again!

**Comment by jobisoft** [comment]
Closing in favor of https://github.com/jobisoft/quicktext/issues/371.
Please give feedback regarding the planned modifications for script support.

**Comment by jobisoft** [comment]
FYI: The pre-release version of Quicktext v6 support WebExtemsion APIs in scripts.
https://github.com/jobisoft/quicktext/issues/439
