### ISSUE TITLE
name of template appears on emails?

### ISSUE THREAD

**Issue by xpseudonym** [thundernest/quicktext#291]
Hello
I've had it reported and it appears when I view my sent emails via my mobile, that the name of the template I'm using on a sent email is appearing at the head of the email.
So, for instance, if I use my 'default' template, then the word 'default' appears at the head of the email - which is disconcerting and off putting for recipients.
See, attached screenshots - first of my quicktext templates window:
![Screenshot from 2022-03-30 15-45-30](https://user-images.githubusercontent.com/5032475/160869253-849245b5-605c-4cff-9c91-1997397f3a0a.png)
Then, of the sent email from my mobile with offending 'default' template name circled in red:
![Screenshot_20220329-113122_FairEmail](https://user-images.githubusercontent.com/5032475/160870727-19964d46-a723-4675-b321-1d7c2783d8fd.png)
How do I make the template name go away?
Thanks

**Comment by xpseudonym** [comment]
bump...
Anyone with any idea how to fix this bug?

**Comment by xpseudonym** [comment]
I think I discovered 'default' defined in the html head as a title element - but now, deleting that element causes W3C validator to cry foul:
'Error: Element [head](https://html.spec.whatwg.org/multipage/#the-head-element) is missing a required instance of child element title.'
Thanks

**Comment by SamuelPlentz** [comment]
Could not reproduce that on Windows 10. What OS do you use?

Try to reduce your templates as far as possible, while you are still able to reproduce the problem.
Could you paste the remaining template text here? (remove personal informations)
Could you also paste the email source code here? (remove personal informations)

**Comment by xpseudonym** [comment]
Hmm, Windows 10 is difficult for me - I've been using gnu/linux for the past 20 years - I really wouldn't know where to start...
I'll get on to the rest soon.  Thx

**Comment by SamuelPlentz** [comment]
IMO close until there is new feedback.
