### ISSUE TITLE
quicktext linux append the subject line to a file

### ISSUE THREAD

**Issue by otrebor4** [thundernest/quicktext#296]
Hi all, 
i'm using quicktext and must say it's a fine piece of software.
Now i need to collect some SUbject lines from my mails into an external file to be sorted: can this be done with quicktext?
Thanks in advance.

**Comment by SamuelPlentz** [comment]
Quicktext only works from within only one email. So IMO this is not intended to be solved by Quicktext and therefore be closed.

This may help:
https://support.mozilla.org/en-US/questions/1075090
https://superuser.com/questions/330458/export-list-of-mails-in-thunderbird
