### ISSUE TITLE
position of calling up menu template already changed by some versions beta TB

### ISSUE THREAD

**Issue by Renato-sainformatica** [thundernest/quicktext#297]
very kind gentlemen, I use now TB 101.0b3 (64 bit);
it is from several beta versions that quick text is no longer displayed in the position of the message body (see image) but is displayed in conjunction with the right mouse button; (see image);
this is a inconvenient because before one click was enough to open the drop-down menu, now it takes three mouse clicks;
in the release version of TB it is fine; unfortunately I cannot go back to the release version from my beta version without having to reinstall and import everything I have in TB
there is some trick ?
thank you
![Screenshot_55](https://user-images.githubusercontent.com/101258373/168822568-17603960-22d5-4988-9a34-773f5fcb95bf.png)
![Screenshot_54](https://user-images.githubusercontent.com/101258373/168823407-2aca20c3-d877-4393-ae53-4e0af8e12c5c.png)

**Comment by jobisoft** [comment]
I have no idea how you got QT working in 101. I did not release a version for it.
https://addons.thunderbird.net/de/thunderbird/addon/quicktext/versions/

Expect one end of July.

**Comment by Renato-sainformatica** [comment]
some time ago, I simply tried to install the component through the file quicktext-4.1-tb.xpi (06 October 2021);
when I installed it the menus were ok;
at some point after a few TB beta updates, the menus disappeared and went to the right mouse button
thank uou

**Comment by jobisoft** [comment]
fixed

**Comment by Renato-sainformatica** [comment]
Thank you very much.

**Comment by Renato-sainformatica** [comment]
good morning Jhon after your kind quicktext correction I used this component until today I had version 102.0b8 (64bit);
today I installed the 103.0b1 (64bit) version and TB disabled the quicktext component and unfortunately I can't go back to the 102.0b8 (64bit) version; do you have a kind idea how I can solve?
![immagine](https://user-images.githubusercontent.com/101258373/176686181-30528d13-3547-47db-adc3-4eaf684f68b8.png)

thank you

**Comment by Renato-sainformatica** [comment]
I managed to reinstall quicktext, installing the previous version 4.1 that I had aside; obviously but now I no longer have your correction that you did in 4.2 because 4.2 does NOT install to me
![immagine](https://user-images.githubusercontent.com/101258373/176688760-b1f46419-ff88-47ad-b6d1-0193de7720e8.png)

**Comment by Renato-sainformatica** [comment]
at the moment I found this solution which I hope will last for version 4.2 of quicktext; I created in the thunderbird editor the boolean variable extensions.checkCompatibility.103.0 with FALSE assignment
so I was able to install it even if it is reported to me , it works
![immagine](https://user-images.githubusercontent.com/101258373/176706802-48474e9f-5584-402c-87f9-e1878f395aed.png)
![immagine](https://user-images.githubusercontent.com/101258373/176706991-07018bd7-926d-4525-8816-38a16c202ec9.png)
