### ISSUE TITLE
Uncaught (in promise) SyntaxError: nothing to repeat

### ISSUE THREAD

**Issue by epescol** [thundernest/quicktext#298]
On some templates I get this error message on Windows 10 Home:
Uncaught (in promise) SyntaxError: nothing to repeat
    replaceText chrome://quicktext/content/modules/wzQuicktextVar.jsm:1187
    parseText chrome://quicktext/content/modules/wzQuicktextVar.jsm:175
[wzQuicktextVar.jsm:1187:22](chrome://quicktext/content/modules/wzQuicktextVar.jsm)
Adding attribute 'OS' = 'WINNT' to settings dialog element. 2 [settings.js:25:15](chrome://quicktext/content/settings.js)

Thunderbird 91.9.0 (64 bit)
QT 4.1

No errors on Miscrosoft Windows 11 Pro.

Any idea how to fix it?

Tks

**Comment by SamuelPlentz** [comment]
Try to reduce your templates as far as possible, while you are still able to reproduce the problem.
Could you paste the remaining text here? (remove personal informations)

**Comment by SamuelPlentz** [comment]
IMO close until there is new feedback.
