### ISSUE TITLE
Quicktext toolbar disappeard

### ISSUE THREAD

**Issue by HoLue** [thundernest/quicktext#299]
Suddenly, the Quicktext toolbar disappeard. Maybe due to an update? My last update of Quicktext was today.... I have version 4.2.

**Comment by jobisoft** [comment]
yep, fixed.

**Comment by mbeck65** [comment]
what does this mean? how to fix?

**Comment by jobisoft** [comment]
I read your statement wrong. I released 4.2 to fix the toolbar in 102, apparently I borked it for 91.

**Comment by jobisoft** [comment]
Download 4.1 from ATN and install it over, you will not be updated to 4.2 again
https://addons.thunderbird.net/thunderbird/downloads/file/1019456/quicktext-4.1-tb.xpi

**Comment by mbeck65** [comment]
great! it works, thanks

**Comment by HoLue** [comment]
> Download 4.1 from ATN and install it over, you will not be updated to 4.2 again https://addons.thunderbird.net/thunderbird/downloads/file/1019456/quicktext-4.1-tb.xpi

Perfect! Thanks! Great support! Immediately! Thanks!
