### ISSUE TITLE
Setting keyboard shortcut breaks numpad numeric character input

### ISSUE THREAD

**Issue by ite-jankl** [thundernest/quicktext#30]
I regularly use the numpad to enter some useful characters like the correct apostrophe `’` (ALT+0146) rather than the incorrect `'`, or `…` (ALT+0133) rather than `...`, or other quotation marks `“”` and `„“` rather than `""`.

Quicktext allows using number keyboard shortcuts to insert text templates, for example CTRL+0.

This breaks the numpad character input method.

What I would expect, how I want to suggest it to behave is: Only trigger on the normal number line keys, but not the numpad. Providing alternatives to the ALT key would also be a reasonable alternative/workaround. (What's the reasoning to limiting it to ALT?)

This is on Windows.

**Comment by jobisoft** [comment]
You can change the Shortcut key from ALT to CTRL and see if that solves your issue?

![grafik](https://user-images.githubusercontent.com/5830621/66073638-c1ed9880-e557-11e9-87b0-2e05095e324f.png)
