### ISSUE TITLE
Toolbar disappeared today [fix inside]

### ISSUE THREAD

**Issue by quchevalier** [thundernest/quicktext#300]
Hi,

it seems there was an automatic update today (19/05/2022).

**Since then, the quicktext toolbar has disappeared in my New Message window.**

I tried Affichage > tick "Quicktext" (it was already selected)

I tried to reinstall Quicktext.

I would like to downgrade to the previous version, how can I do ?

Thanks a lot.
Q

**Comment by jobisoft** [comment]
I released 4.2 to fix the toolbar in 102, apparently I borked it for 91. 

Download 4.1 from ATN and install it over, you will not be updated to 4.2 again
https://addons.thunderbird.net/thunderbird/downloads/file/1019456/quicktext-4.1-tb.xpi

**Comment by quchevalier** [comment]
It works perfectly.

Many thanks !

**Comment by cotus78** [comment]
> It works perfectly.
> 
> Many thanks !

I confirm as well

Thanks

**Comment by mbeck65** [comment]
thanks to let us know how to make a donation for this great support!!!

**Comment by SamuelPlentz** [comment]
AFAIK jobisoft works for Thunderbird itself. So IMO donating to Thunderbird would help here.

**Comment by mbeck65** [comment]
> AFAIK jobisoft works for Thunderbird itself. So IMO donating to Thunderbird would help here.

ok

**Comment by CamielBouchier** [comment]
Does the trick. Back in business. Thx!
Camiel B

**Comment by SamuelPlentz** [comment]
This issue should stay open for a while to prevent duplicates.

**Comment by mad99** [comment]
Thank you @SamuelPlentz for your answer, help and redirection.
All works fine with 4.1-tb.xpi

Great - Thank you very much.
