### ISSUE TITLE
QuickText bar disappeared?

### ISSUE THREAD

**Issue by CamielBouchier** [thundernest/quicktext#301]
It looks like today the quicktext toolbar disappeared (I still can introduce the quicktext through the right mouseclick). Is this a generic issue or did something go wrong at my end? How to find out about?

Camiel B.

**Comment by cotus78** [comment]
Same for me.
Tried to disable/enable , change interface etc but without luck

Cotus

**Comment by SamuelPlentz** [comment]
Have a look here: #300

**Comment by cotus78** [comment]
> Have a look here: #300

It works,
Thanks!

**Comment by CamielBouchier** [comment]
> 

Works now. Thanks.
