### ISSUE TITLE
Quicktext 4.2 was automatically installed into the wrong Thunderbird v91.6 

### ISSUE THREAD

**Issue by mad99** [thundernest/quicktext#302]
Hi,
Quicktext is a really great and helpfull Addon!

Today it seams the Quicktext 4.2 was updated on my System.

### Effect/Problem
Since this moment the **_QuickText Menu is no longer visible._**

### System
Mac OS Big Sur : 11.6.5 (20G527)
Thunderbird : 91.9.0 (64-Bit)

### Problem/Trigger
Altough this version is set defined for 

```
[Version 4.2](https://addons.thunderbird.net/en-US/thunderbird/addon/quicktext/versions/4.2)
Released May 19, 2022  137.7 KiB
Works with Thunderbird 92.0 - 102.*
Source code released under [Mozilla Public License, version 2.0](http://www.mozilla.org/MPL/2.0/)
```

and 92.0 from Thunderbird is defined still as Beta, so the Addon and installed Thunderbird is not compatible I guess.

#### Bug?

- Is there maybe a error-seting in the code? (Or should the addon for Beta 92 also compatible with installed in the 91.9 Version)
- Is it possible to change this behaviour (undo it of not compatible 91.9 Versions) so the Thunderbird will redo the update and reinstall the last addon for this version 4.1?

OR
#### Install Old-Version?

- 1. Should I export/backup all stuff?
- 2. uninstall the wrong addon 4.2?
- 3. Install the older QuickText 4.1?
- 4. UNCHECK the «enable auto-updates»?

OR 
#### Change 4.2[.1] so it will be compatible with 91.6?

- Is there a way to make the 4.2 Quicktext (maybe 4.2.1) for Thunderbird 91.6 so the Quicktext-Menu will displayed again as in the past?

Best regards
Martin

**Comment by SamuelPlentz** [comment]
Have a look here: #300

**Comment by jobisoft** [comment]
After I released 4.2 I saw it borked TB91, so I changed the min version to TB92 to prevent further updates for TB91 users. But some did get it, and now it looks as if TB pulled an incompatible update. Sorry for the inconvenience.

**Comment by tbertels** [comment]
You may want to release a new version to automatically fix all TB91 users stuck on 4.2 without having to wait for 92.
Many users didn't install it themselves and even some of them don't know how to install a previous version.

**Comment by jobisoft** [comment]
Yeah, I probably have to do that. It was enabled for only 10 Minutes, and I hoped I only have a handful of cases. I wanted to wait for the user stats of 4.2 to make a final decision.

**Comment by tbertels** [comment]
Based on the number of users, 123000 / 144 = 854 users on average.
If that 10 minutes interval happened at a high update check time, it may be higher.

**Comment by jobisoft** [comment]
4.3 has been pushed.
