### ISSUE TITLE
Toolbar disappeared in version 4.1

### ISSUE THREAD

**Issue by sju10544** [thundernest/quicktext#303]
I have overwritten from 4.3 to version 4.1 as recommended here: https://github.com/jobisoft/quicktext/issues/300 but still missing the toolbar... (and yes, deleted 4.3, re-start, installation 4.1 etc.) Have TB 91.9.1

**Comment by jobisoft** [comment]
I think it is something different. Version 4.3 is identical to 4.1. But I have no idea what is happening for you.

**Comment by sju10544** [comment]
O.K. Thanks for the reply. Any ideas what I can / should do to investigate this further?

**Comment by sju10544** [comment]
When switching off / on the addon I got this line in the error console:
Error: Missing host permission for the tab

**Comment by sju10544** [comment]
And this one: sendRemoveListener on closed conduit {8845E3B3-E8FB-40E2-95E9-EC40294818C4}.137438954109

**Comment by sju10544** [comment]
No idea? BTW: Quicktext Arrow is there. Also all the stored signatures on a NAS.

**Comment by jobisoft** [comment]
Not really. Except: Are you sure the toolbar is enabled?

![image](https://user-images.githubusercontent.com/5830621/170973131-29be5dbc-7593-4337-8775-14b1e0efdad5.png)

**Comment by sju10544** [comment]
That's embarrassing! Yes, you're right. Just enable the toolbar and magic on: everything works like before. Thanks a lot!
