### ISSUE TITLE
Import on startup not working

### ISSUE THREAD

**Issue by therealrobster** [thundernest/quicktext#304]
Hi there,

LOVE this extension, so thank you first of all.

We've noted the last year or more than import on startup is not working.

The path is correct by all accounts.  We literally copy and paste.  But on load it does not import the file.  

So we manually have to delete all the Templates and import them again.  I wonder if this is a known issue or something we can be doing.

Here is an example path:
`/home/username/Sync/Thunderbird Quicktext/thunderbird_quicktext.xml`

Were using a range of linux machines from Pop_OS! to Debian.  All debian / ubuntu based though.

I hope the above helps, maybe we're doing something wrong?

Thank you.

Quicktext 4.3
Last Updated 21 May 2022
Thunderbird 91.9.0 (64-bit)

**Comment by ShirtlessWebmaster** [comment]
I'm having this problem too. Any updates on potential workaround would be appreciated. Thanks.

**Comment by therealrobster** [comment]
No luck here, stil the same issue

**Comment by jobisoft** [comment]
Closing in favor of https://github.com/jobisoft/quicktext/issues/371.
Please report there if the proposed solutions will work for you
