### ISSUE TITLE
Quicktext item replacing email subject line

### ISSUE THREAD

**Issue by ghost** [thundernest/quicktext#306]
When I use my item of quicktext, the subject of the email changes to the name of the quicktext.

There seems to be a previous ticket that is similar, but as an relatively ignorant newbie, I'd appreciate a way to stop this happening or at least to find out if it is a known bug.

Please let me know if you need more details.

**Comment by weksupport** [comment]
![image](https://user-images.githubusercontent.com/16732699/176613215-b2e07b92-bf29-45f6-a432-2e016c402198.png)
Is Subject empty ?

**Comment by ghost** [comment]
No, I had already entered the text into the subject line. When I click on the quicktext item, it in inserted into the email (as designed) and the title of it replaces the other text in the Subject. This has happened several times. I can change the subject back and it will stick, but I didn't realise it was happening  for a while, so several emails were sent with strange subject lines.

**Comment by jobisoft** [comment]
@Feejaybee : weksupport was referring to the subject line of your used template, as seen in the screenshot.

**Comment by ghost** [comment]
Sorry for misunderstanding. The Subject line (as in the screenshot) contains the name of the quicktext item. I presume this is the problem - it should be blank?
When setting up the quicktext I didn't realise that this was referring to the email subject. I thought it meant the subject of the quicktext.

**Comment by jobisoft** [comment]
That Subject field replaces the email subject, yes. So I close the issue as solved. Feel free to ping back if you need further help. Thanks for everyone involved!
