### ISSUE TITLE
[[HEADER=to

### ISSUE THREAD

**Issue by weksupport** [thundernest/quicktext#307]
It seems that [[HEADER=to and =reply-to doesn't work in the new 102 and 103Beta version with QuickText 5.0

**Comment by Alfred-Peters** [comment]
I can confirm this.

Error Console says:
```
15:58:27.925 Uncaught (in promise) ReferenceError: awAddRecipientsArray is not defined
    insertHeaders chrome://quicktext/content/quicktext.js:489
    insertTemplate chrome://quicktext/content/quicktext.js:375
    updateGUI chrome://quicktext/content/quicktext.js:278
    updateGUI chrome://quicktext/content/quicktext.js:278
    observe chrome://quicktext/content/quicktext.js:806
    notifyObservers chrome://quicktext/content/modules/wzQuicktext.jsm:1048
    saveSettings chrome://quicktext/content/modules/wzQuicktext.jsm:250
    save chrome://quicktext/content/settings.js:135
    oncommand chrome://quicktext/content/settings.xhtml:1
```

`awAddRecipientsArray ` was changed in [Bug 1721352](https://bugzilla.mozilla.org/show_bug.cgi?id=1721352)

<https://phabricator.services.mozilla.com/D122620>

**Comment by jobisoft** [comment]
Great research, that will help. Thanks!

**Comment by downlaw** [comment]
"[[HEADER=cc|*]]" doesn't work too in the new 102 (64-bit) version with QuickText 5.0.

**Comment by SamuelPlentz** [comment]
I didn't use the header tag, but the following code in a custom script:
``` javascript
win.awAddRecipientsArray("addr_to", ["John Doe <john.doe@example.com>", "Jane Doe <jane.doe@example.com>"]);
```
had the same error message: `win.awAddRecipientsArray is not a function`

Could fix that by this code:
``` javascript
let toRow = win.document.getElementById("addressRowTo");
let ccRow = win.document.getElementById("addressRowCc");
let bccRow = win.document.getElementById("addressRowBcc");
let replyRow = win.document.getElementById("addressRowReply");
win.addressRowAddRecipientsArray(toRow, ["John Doe <john.doe@example.com>", "Jane Doe <jane.doe@example.com>"]);
```

**Comment by SamuelPlentz** [comment]
I fixed also the `HEADER` in Quicktext now.
Could you try this: [quicktext-5.1b-tb.zip](https://github.com/jobisoft/quicktext/files/9033081/quicktext-5.1b-tb.zip) (drag the file to Thunderbird addons)

**Comment by SamuelPlentz** [comment]
Created PR #311.

**Comment by Alfred-Peters** [comment]
Tested Quicktext5.1.2 with TB102.0 and TB103.0b2.
Works fine.

**Comment by downlaw** [comment]
> I fixed also the `HEADER` in Quicktext now. Could you try this: [quicktext-5.1b-tb.zip](https://github.com/jobisoft/quicktext/files/9033081/quicktext-5.1b-tb.zip) (drag the file to Thunderbird addons)

Works fine with this fix on 102 (64-bit) version.
Thanks a lot!

**Comment by jobisoft** [comment]
Thanks goes to @SamuelPlentz . Thanks!

**Comment by SamuelPlentz** [comment]
And to @Alfred-Peters for pointing to the right direction!

**Comment by jobisoft** [comment]
An updated version 5.2 has been released and should be shipped automatically to users soon.
