### ISSUE TITLE
QT stop on TB (beta) 103.0b1 (64bit) 

### ISSUE THREAD

**Issue by Renato-sainformatica** [thundernest/quicktext#308]
good morning Jhon after your kind quicktext correction (with 4.2) I used this component until today I had version 102.0b8 (64bit);
today I installed the 103.0b1 (64bit) version and TB disabled the quicktext component and unfortunately I can't go back to the 102.0b8 (64bit) version; do you have a kind idea how I can solve?
![immagine](https://user-images.githubusercontent.com/101258373/176844536-35e78428-57e2-44d3-9be9-3d729d0df174.png)

update1:
I managed to reinstall quicktext, installing the previous version 4.1 that I had aside; obviously but now I no longer have your correction that you did in 4.2 because 4.2 does NOT install to me

![immagine](https://user-images.githubusercontent.com/101258373/176844588-f64b5a8e-4432-4bbd-924a-d070fcf07315.png)

update2:
at the moment I found this solution which I hope will last for version 4.2 of quicktext; I created in the thunderbird editor the boolean variable extensions.checkCompatibility.103.0 with FALSE assignment

so I was able to install it even if it is reported to me , it works
thank you for your attention

![immagine](https://user-images.githubusercontent.com/101258373/176844645-555f2b5c-7c8d-4940-be61-ccb56f1d3ce6.png)
![immagine](https://user-images.githubusercontent.com/101258373/176844656-95fff8de-ea89-4cab-8dcb-fe35b32d14ff.png)
![immagine](https://user-images.githubusercontent.com/101258373/176845479-f50ce1f5-f44b-45cc-89f1-959510051571.png)

**Comment by jobisoft** [comment]
5.2 has been tested with 104 and I updated the value. But you are living on the edge there!
