### ISSUE TITLE
[[HEADER=to|...]] (or HEADER=cc) does not work

### ISSUE THREAD

**Issue by yimir0** [thundernest/quicktext#314]
Since last 2 updates of thunderbird, those variables does not work anymore: the email I configured does not shows in the TO, CC or BCC fields.
Thanks in advance for any help

**Comment by SamuelPlentz** [comment]
Duplicate of: #307 (Solution inside.)

**Comment by jobisoft** [comment]
An updated version 5.2 has been released and should be shipped automatically to users soon.
