### ISSUE TITLE
Templates Dropdown missing in compose window

### ISSUE THREAD

**Issue by sebthom** [thundernest/quicktext#315]
After Upgrading to TB 102 and QuickText 5.2 I am missing the dropdown with the templates in the compose window.

The one that is visible in the screenshot here https://github.com/jobisoft/quicktext/wiki/Installation-and-creating-a-template#usage

Looks like this for me:
![image](https://user-images.githubusercontent.com/426959/177202720-35f36965-5fac-4765-94d7-3da0d4bce8ca.png)

I can still open the quicktext settings, which means the plugin itself loads:
![image](https://user-images.githubusercontent.com/426959/177202866-8b571a92-c194-4e2f-b966-6a169bf36bee.png)

**Comment by jobisoft** [comment]
Do you have the Quicktext bar enabled? View -> Quicktext?

**Comment by sebthom** [comment]
There is no entry for Quicktext.

![image](https://user-images.githubusercontent.com/426959/177205974-f6607086-9378-436b-93f8-ae2d7cf5149e.png)

**Comment by jobisoft** [comment]
It is at the very bottom: 
![image](https://user-images.githubusercontent.com/5830621/177211462-36a7d959-2c57-4c58-a4da-60d85d54a906.png)

**Comment by sebthom** [comment]
Ah ok, now I see :-) Must have gotten disabled during the upgrade somehow. Thanks!!!
