### ISSUE TITLE
Feature request: Per-account templates profiles

### ISSUE THREAD

**Issue by narcisgarcia** [thundernest/quicktext#318]
My request is to Quicktext template editor have account selector for each template:
A) This template is for only X e-mail account
B) This template is common to all accounts

Then, depending on what e-mail account is being used to write a letter from, Quicktext expose specific & common templates to be used in mail composer.

**Comment by SamuelPlentz** [comment]
Could you give an example of a template that is only relevant to use in one account?

If you only want to tweak a template like this:
```
Dear Ladies and Gentlemen,

Kind regards
John Doe
```

```
Dear Ladies and Gentlemen,

Kind regards
John Doe from Initech

Try out our new product!!!1!
```

This script can probably help as a workaround: https://github.com/jobisoft/quicktext/wiki/Script:-SignatureByFrom

IMO one should always try to only have one set of templates.

**Comment by narcisgarcia** [comment]
Template "Appointment" From: porthuron@example.net
```
Hello #Name, you have an appointment for #friday #15th at #00:00pm
Place: Society office at Garfield street 45, in front of Palmer park
Phone contact: 123 456 789 (John) only from 9:00 to 11:00 AM.
```
Template "Appointment" From: sarnia@example.net
```
Hello #Name, you have an appointment for #friday #15th at #00:00pm
Place: Society office at Exmouth street 223, next to petrol station
Phone contact: 456 789 012 (Mary)
```

**Comment by SamuelPlentz** [comment]
This should work:

Template Text:
```
Hello #Name, you have an appointment for #friday #15th at #00:00pm
[[SCRIPT=SignatureByFrom|[[FROM=email]]]]
```

Script SignatureByFrom:
```javascript
// Read the e-mailaddress in FROM header to variable emailaddress
var emailaddress = this.mVariables[0];

// Depending on e-mailaddress return signature
switch (emailaddress) {
    case "porthuron@example.net":
        return
            "Place: Society office at Garfield street 45, in front of Palmer park\n" + 
            "Phone contact: 123 456 789 (John) only from 9:00 to 11:00 AM."
        break;

    case "sarnia@example.net":
        return
            "Place: Society office at Exmouth street 223, next to petrol station\n" +
            "Phone contact: 456 789 012 (Mary)";
        break;
}
```

**Comment by narcisgarcia** [comment]
Good to know. but: What about unexperienced user that wants to edit or expand this information?

**Comment by SamuelPlentz** [comment]
Just wanted to give you a quick workaround, working right now.

I think it would be good to implement something like you suggested.

**Comment by narcisgarcia** [comment]
To organize files for this feature, I suggest quicktext folder in M.Thunderbird profile has this files names:
```
accountprofile1.tpl.xml
accountprofile2.tpl.xml
_common.tpl.xml
accountprofile1.scr.xml
accountprofile2.scr.xml
_common.scr.xml
```

**Comment by jobisoft** [comment]
The feature you are requesting is probably covered by SmartTemplates:
https://addons.thunderbird.net/smarttemplate4/

I currently do not have the time to add this feature.
