### ISSUE TITLE
Add event + add task buttons aren't working

### ISSUE THREAD

**Issue by AK-CCM** [thundernest/quicktext#319]
W10 Pro 21H2 / TB 102.1.0 64-bit / Quicktext 5.2

In the calendar the two buttons [+Event] and [+Task] nor the corresponding menu items don't work.

[EDIT] Also the tabs don't work. [/EDIT]

![grafik](https://user-images.githubusercontent.com/33413085/183249093-a76bd677-dddf-4072-b652-23ada48d5e5c.png)

If I started TB with "thunderbird -safe-mode" or uninstalled quicktext the buttons and menu items work fine.

Could anyone reproduce this issue?

**Comment by SamuelPlentz** [comment]
Windows 10 Home 21H2 / Thunderbird 102.1.2 (64-Bit) / Quicktext 5.2
Cannot reproduce.

You could try: https://github.com/jobisoft/quicktext/wiki/Troubleshooting
2. Disable other add-ons
4. Fresh profile
6. Isolate errors in existing profiles

**Comment by AK-CCM** [comment]
Thank you in trying to reproduce my issue.
I think it's a problem with my profile.
