### ISSUE TITLE
pb with prompt command

### ISSUE THREAD

**Issue by titigafr** [thundernest/quicktext#32]
Hi,
are there any solution to use Prompt method in a script ?

Thanks,

**Comment by jobisoft** [comment]
https://www.w3schools.com/jsref/met_win_prompt.asp

**Comment by titigafr** [comment]
I'm obtain this error message : 

> You have an error in your script: requestSLR
> ReferenceError: prompt is not defined

**Comment by jobisoft** [comment]
window.prompt().

If window is not avail, it does not work or you need to get the window object by some other means. 

But this is not an issue with quicktext, we cannot provide general support for coding questions here. Sorry.
