### ISSUE TITLE
TypeError: text.indexOf is not a function

### ISSUE THREAD

**Issue by ShargAA** [thundernest/quicktext#320]
After installing the version Thunderbird Version 102.1.2
Quicktext ver 5.2
Help me fix the error!

GetMailBody()
var editor = this.mWindow.gMsgCompose.editor;
var textBody = editor.outputToString('text/plain', 8); 
return textBody;
======
Test()
text = this.mQuicktext.get_script(["GetMailBody"]);
poz1 = text.indexOf("22");
return poz1;
======
==> TypeError: text.indexOf is not a function
====

**Comment by SamuelPlentz** [comment]
This is related to: #271

Try to add an ```await``` like this:

# GetMailBody()

``` javascript
var editor = this.mWindow.gMsgCompose.editor;
var textBody = editor.outputToString('text/plain', 8);
return textBody;
```

# Test()

``` javascript
text = await this.mQuicktext.get_script(["GetMailBody"]);
poz1 = text.indexOf("22");
return poz1;
```

**Comment by ShargAA** [comment]
Hurray! 
Thank you very much!
