### ISSUE TITLE
QT templates do not work for emails not in the address book

### ISSUE THREAD

**Issue by fvogelmann** [thundernest/quicktext#321]
W10 Pro 21H2 / TB 102.1.2 64-bit / Quicktext 5.2

I have a very simple tempate with the first line 

Dear [[CURSOR]] [[TO=lastname]]

So far, it always worked, regardless whether the subject the email is send to is in my address book or not. Recently, that has changed. I cannot use the template on emails to email addresses which are not in my address book. Neither selecting the template from the QT-menue nor using the keyboard shortcut works. 
Is this a general problem due to the changed address book in TB 102? Can anyone reproduce the problem?

**Comment by fvogelmann** [comment]
I acutally tracked down the problem to a broken startup cache. Clearing it seems to solve the issue, so I will close it.

**Comment by fvogelmann** [comment]
Seems I spoke too soon - the problem seems connected to the error message (from the console)

NS_ERROR_FILE_CORRUPTED: Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [mozIStorageStatement.executeStep] [SQLiteDirectory.jsm:440](resource:///modules/SQLiteDirectory.jsm)
    getCardFromProperty resource:///modules/SQLiteDirectory.jsm:440
    cardForEmailAddress resource:///modules/AddrBookDirectory.jsm:450
    getCardForEmail chrome://quicktext/content/modules/wzQuicktextVar.jsm:1260
    getcarddata_to chrome://quicktext/content/modules/wzQuicktextVar.jsm:893
    process_to chrome://quicktext/content/modules/wzQuicktextVar.jsm:956
    get_to chrome://quicktext/content/modules/wzQuicktextVar.jsm:383
    parseText chrome://quicktext/content/modules/wzQuicktextVar.jsm:176
    parse chrome://quicktext/content/modules/wzQuicktextVar.jsm:117
    insertBody chrome://quicktext/content/quicktext.js:532
    insertTemplate chrome://quicktext/content/quicktext.js:372
    InterpretGeneratorResume self-hosted:1422
    AsyncFunctionNext self-hosted:632

But the address book files are all fine and deleting the startup cache does not help.

**Comment by SamuelPlentz** [comment]
IMO it looks like the address book SQLite Database file is corrupted.

Could you try if it works in a ```4. Fresh profile```? - see [Troubleshooting](https://github.com/jobisoft/quicktext/wiki/Troubleshooting)

Also you could try to ```6. Isolate errors in existing profiles``` - see [Troubleshooting](https://github.com/jobisoft/quicktext/wiki/Troubleshooting)

Perhaps exporting every entry in the address book, deleting the address book SQLite Database file and reimporting the entries after a Thunderbird restart works.

**Comment by fvogelmann** [comment]
Thanks, exporting everything, deleting the address book and importing all contacts again finally worked, everything else I tried was in vain.
