### ISSUE TITLE
Disabled on 105.0b1

### ISSUE THREAD

**Issue by NLLAPPS** [thundernest/quicktext#322]
Hi, just updated to Thunderbird 105.0b1 without checking compatibility and saw that Quicktext is not compatible with 105.

**Comment by NLLAPPS** [comment]
Well, started working again, No updates. Not sure what happened. Perhaps Thunderbird bug.

**Comment by jobisoft** [comment]
I checked it and increased the compatibility range. If you find something not working, please open a new issue. Thanks!
