### ISSUE TITLE
Font size ignored

### ISSUE THREAD

**Issue by Feri-6** [thundernest/quicktext#323]
I upgraded TB to 102 and composition HTML font size setting is ignored when I use QT.
I mean I use a template as HTML. There is not any font size tag in the template but after insert, it uses medium size font although my setting in TB is small for HTML Style. If I insert the template after typing something the size of the template text is is correct (small), so this bug only occurs if the e-mail text is empty and I start with a template.

**Comment by SamuelPlentz** [comment]
Could you provide more information?

1) Could you post a minimal Quicktext template where that happens? (reduce personal information)
2) Could you post the HTML (source code) that gets created if you use the Quicktext template?
3) Could you post the HTML (source code) that gets created if you manually write the same text the template inserts?
4) Could you provide a screenshot of the font size option? AFAIK there are more than one font size options.

**Comment by Feri-6** [comment]
Of course, but how can I get the HTML source code of the created, but not sent e-mail?

**Comment by SamuelPlentz** [comment]
Save email as draft, go to drafts folder, select email, press ```more``` button, show source code.

**Comment by Feri-6** [comment]
**Template:**
```
Kedves [[TO=lastname]],<br>
<br>
Köszönöm a megkeresést.<br>
<br>
[[CURSOR]]<br>
<br>
Üdvözlettel,<br>
<i>John Doe</i><br>
```

**E-mail with wrong text size:**
```
<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
    Kedves,<br>
    <br>
    Köszönöm a megkeresést.<br>
    <br>
    <br>
    <br>
    Üdvözlettel,<br>
    <i>John Doe</i><br>
```

**E-mail with good text size:**
```
<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <font size="2"> Kedves,<br>
      <br>
      Köszönöm a megkeresést.<br>
      <br>
      <br>
      <br>
      Üdvözlettel,<br>
      <i>John Doe</i><br>
```

Setting:
![Screenshot_6](https://user-images.githubusercontent.com/78416694/187664762-8575084f-d1db-42bb-910b-9c92c5c73bc3.jpg)

**Comment by SamuelPlentz** [comment]
I would adjust the template like this:
```
<font size="2">Kedves [[TO=lastname]],<br>
<br>
Köszönöm a megkeresést.<br>
<br>
[[CURSOR]]<br>
<br>
Üdvözlettel,<br>
<i>John Doe</i><br></font>
```

I don't know if quicktext should improve the HTML on its own. I would prefer if it didn't.

**Comment by SamuelPlentz** [comment]
IMO close as won't change.
