### ISSUE TITLE
Not working with 91.13.0 / Quicktext is not compatible with Thunderbird 91.13.0.

### ISSUE THREAD

**Issue by bracewGitHub** [thundernest/quicktext#325]
![grafik](https://user-images.githubusercontent.com/95138371/188413112-58ee24a3-ec29-4d3d-92cc-b7bc279da803.png)

**Comment by jobisoft** [comment]
I assume you downgraded your profile from 102 to 91. Version 5.2 is for 100+. Install v 4.3.

https://addons.thunderbird.net//addon/quicktext/versions/

**Comment by bracewGitHub** [comment]
Ok, thanks. Its working with 4.3
