### ISSUE TITLE
Make data of selected identity available to templates/scripts

### ISSUE THREAD

**Issue by alie2n** [thundernest/quicktext#33]
Hi,
I just want to insert the fullname of the selected identity into the compose window. When using the "from" variables quicktext looks up the Fullname with the adress book. In my context this does not work.
I tried to access these information snippets using the script support. But somehow I cannot access any useful objects from within the scripting engine.

**Comment by jobisoft** [comment]
Can you show, what commands you tried to get the identiy? Do you have a know-to-be-working example?

**Comment by alie2n** [comment]
I have no working example as everything I tried resulted in a ReferenceError.
As fas as I know and the irc channel #maildev on irc.mozilla.org is regarded there should be a object/function called gCurrentIdentity that contains all information. But from the scripting engine I cannot access this object/function.
It seems that the complete scripting environment is emptied before running the scripts. Even basic calls like the window object are not available.

**Comment by jobisoft** [comment]
the window opject is exposed via

this.mWindow

does that help?

var person = this.mWindow.prompt("Please enter your name", "Harry Potter");

worked in a script for me...

**Comment by alie2n** [comment]
Yeah this does help me a lot. Now I was able to achieve what I wanted. Is there any reference (besides source code) what objects are available?

**Comment by alie2n** [comment]
Thanks by the way for the fast support. :) :+1:

**Comment by jobisoft** [comment]
Besides the original doc:
http://extensions.hesslow.se/text/1/Script+Support/

There is only the source :-)

**Comment by jobisoft** [comment]
Can you post your script, so others can benefit from it as well?

**Comment by alie2n** [comment]
In order to get the full name of the current identity I wrote the following script:
```
var currentIdentity;
currentIdentity = this.mWindow.gCurrentIdentity;
GetFullName() {
fullname = currentIdentity.fullName;
fullname = fullname.replace(/,.*/i,''); // our format it First Last, Organisation
return fullname;
}
```

I did something similar to get only the first or the last name.
```
GetLastName () {
var currentIdentity;
currentIdentity = this.mWindow.gCurrentIdentity;

fullname = currentIdentity.fullName;
fullname = fullname.replace(/,.*/i,'');
lastname = fullname.replace(/.* /i,'');
return lastname;
}
```

```
GetFirstName() {
var currentIdentity;
currentIdentity = this.mWindow.gCurrentIdentity;

fullname = currentIdentity.fullName;
//fullname = fullname.replace(/,.*/i,'');
firstname = fullname.replace(/ .*/i,'');
return firstname;
}
```

**Comment by jobisoft** [comment]
Thanks, I will probably add it to the wiki or add a new [[identity]] tag which does that.
