### ISSUE TITLE
Config: too easy to quit without saving

### ISSUE THREAD

**Issue by matttbe** [thundernest/quicktext#330]
Hello,

First, thank you for developing and maintaining this extension!

I'm currently only doing basic stuff with it, e.g. adding one line when reviewing patches.

One suggestion from my side regarding the config window: it took me a bit of time to realise there is a `Save` button I need to press before closing the window. It might be helpful to have a warning if we close the window and there are unsaved modifications. Or an "autosave" and no more `Save` button. Or move the `Save` next to the `Close` one?

Just some ideas ;-)

**Comment by SamuelPlentz** [comment]
Duplicate of #237.

**Comment by matttbe** [comment]
Indeed, sorry for the duplication!
