### ISSUE TITLE
Return and Enter are not the same

### ISSUE THREAD

**Issue by coderfls** [thundernest/quicktext#333]
Great tool! Thank you
On issue: The key word is recognized if I enter Return but not if I press Enter. It will be fine if pressing Enter will work the same way

DE: Ein Schlüsselwort für eine Vorlage wird durch die Vorlage ersetzt, wenn man Return drückt, nicht aber bei Enter. Beides sollte IMHO gleich funktionieren

**Comment by SamuelPlentz** [comment]
I can confirm the ```Enter```-key working while the ```NumpadEnter```-key doesn't work.

Here is the List of keys definied:

https://github.com/jobisoft/quicktext/blob/29627538f6603675bd5cac3ca63b2ac1078a3ae9/chrome/content/settings.xhtml#L108-L124

Here it is used:

https://github.com/jobisoft/quicktext/blob/29627538f6603675bd5cac3ca63b2ac1078a3ae9/chrome/content/quicktext.js#L716-L721

To fix it this:

``` javascript
if (e.code == gQuicktext.keywordKey)
```

can be changed to this:
``` javascript
if (e.code == gQuicktext.keywordKey || (e.code == "NumpadEnter" && gQuicktext.keywordKey == "Enter"))
```

**Comment by jobisoft** [comment]
Thanks to everyone involved!
