### ISSUE TITLE
To field as text

### ISSUE THREAD

**Issue by jonrox** [thundernest/quicktext#334]
I tried to insert `[[HEADER=to|"test"]]` but the field is not filled, it only accepts @ addresses, but I only need to enter one text. How can I solve?
Thanks

**Comment by SamuelPlentz** [comment]
Try this community script: [AddRecipients](https://github.com/jobisoft/quicktext/wiki/Script:-AddRecipients)

```[[SCRIPT=AddRecipients|to|test]]```

**Comment by jonrox** [comment]
Thanks work
