### ISSUE TITLE
Quicktext, mailto-Link

### ISSUE THREAD

**Issue by schabau** [thundernest/quicktext#337]
Hello,

Quicktext is inactive when clicking a mailto-Link from the Browser if TB/BB was not started.
If I start TB or BB and then click on a mailto-Link, Quicktext also works.

Many greetings
schabau

**Comment by SamuelPlentz** [comment]
Can confirm that behaviour.

**Comment by Alfred-Peters** [comment]
See also:
[Bug 1800423 - QuickText add-on works only in a case, when the full main Thunderbird window is opened and running before](https://bugzilla.mozilla.org/show_bug.cgi?id=1800423)

**Comment by jobisoft** [comment]
Currently working on other things, but this has to be fixed in core eventually. Hope to get it done soon.

**Comment by jobisoft** [comment]
The bug is being worked on and the mentioned mailto link should work in daily already.
