### ISSUE TITLE
Feature request: change sending Account

### ISSUE THREAD

**Issue by holdinghausen** [thundernest/quicktext#341]
I don't know if this is possible / accessible, but: I am using quicktext for my business e-mails. Certain mails (like rfq, purchase orders, order confirmations) shall be sent by a defined account, but sometimes I mess this up.

I'd love to have quicktext "select" the right account. E.g. when i click the po-template, quicktext ensures that this e-mail will be sent from my purchase@company-account.

Possible? :-)

**Comment by SamuelPlentz** [comment]
Have a look at the community script [Identity](https://github.com/jobisoft/quicktext/wiki/Script:-Identity)

**Comment by SamuelPlentz** [comment]
Close, as it is possible to use the community script?
