### ISSUE TITLE
Settings will be not saved

### ISSUE THREAD

**Issue by orcas-mgleich** [thundernest/quicktext#343]
After changing the settings, saving via the button, closing and reopening, the settings are as before. Unchanged.

Thunderbird: 102.9.1 (64-Bit)
Quicktext: 5.3
OS: Windows 11
Rights: Full rights

**Comment by SamuelPlentz** [comment]
Cannot reproduce.

Can you try the [Steps mentioned here](https://github.com/jobisoft/quicktext/wiki/Troubleshooting) - especially ```4. Fresh profile```.

**Comment by SamuelPlentz** [comment]
What setting is changed here?
Is Thunderbird closed or only the Quicktext window?

**Comment by orcas-mgleich** [comment]
With new profile the settings are saved. After closing quicktext and also after closing thunderbird.

I will be also testing with new profile, import of old templates before I change the settings.

An other behavior is, that in the version with error, no keys are configured, if I open the settings.

**Comment by SamuelPlentz** [comment]
You could [try to](https://github.com/jobisoft/quicktext/wiki/Troubleshooting) ```6. Isolate errors in existing profiles```.

**Comment by SamuelPlentz** [comment]
IMO should be closed, as there is no bug in Quicktext itself.
