### ISSUE TITLE
Right click no longer possible

### ISSUE THREAD

**Issue by theodor63** [thundernest/quicktext#345]
Dear Samuel,

after a hard disk crash I reinstalled Linux, Thunderbird and Quicktext. Unfortunately, the right-click to paste no longer works. Is this on purpose? 

I miss the function, I got used to it in many years.

Regards
Theodor

Thunderbird 102.10.0
Quicktext 5.3
Linux Mint 21.1 Cinnamon

**Comment by SamuelPlentz** [comment]
Here in windows it works. So its not on purpose. Does it work in an new profile: https://github.com/jobisoft/quicktext/wiki/Troubleshooting

**Comment by jobisoft** [comment]
Nothing I can do. Te right-click / context-click is an OS feature. Quicktext is not involved.

**Comment by RayCulp** [comment]
@theodor63 Did you activate the right-click option in the settings? Don't forget to click Save after you activate the option, or it will not work.

![image](https://github.com/jobisoft/quicktext/assets/7621330/045a5c1b-64da-4e1b-9702-d656da044816)
