### ISSUE TITLE
Please make QuickText available on Trunk/Daily (Tb 115,0a1)

### ISSUE THREAD

**Issue by PeterLairo** [thundernest/quicktext#347]
I love and depend on your great Add-on QuickText. I also couldn't wait to try out Thunderbird's new UI, so I installed the Daily/Trunk version.

Could you please make QuickText available on the current Daily/Trunk releases?

Perhaps just create an *unofficial unsupported test version* with the max. Tb-version bumped up to 115.0aX. :-)

![Tb-daily-version](https://github.com/jobisoft/quicktext/assets/6554639/760dbdd2-045c-4d65-9dd1-9f45ef8050b8)

**Comment by jobisoft** [comment]
https://github.com/jobisoft/quicktext/releases/tag/v5.5

**Comment by jobisoft** [comment]
v5.4 has hit addons.thunderbird.net already, but has a small bug. v5.5 will get there soon as well.
