### ISSUE TITLE
Input type select do not support multi select

### ISSUE THREAD

**Issue by nicolaslegruiec** [thundernest/quicktext#349]
I have the impression that the select type of the INPUT variable does not support multiple selection. It also does not support empty choice.

For example :
You have access to the following share: 
- [[INPUT=share:|select|share1;share2;share3]]

![Capture d’écran 2023-05-30 à 17 19 33](https://github.com/jobisoft/quicktext/assets/80323217/88edb81d-ec20-46e7-bfce-286c5cb657dc)

I can't select nothing, and I can't select 2 shares

Thanks in advance !

**Comment by SamuelPlentz** [comment]
Duplicate: #281
