### ISSUE TITLE
Feature request: generate a password

### ISSUE THREAD

**Issue by isamuse2** [thundernest/quicktext#350]
I use QuickText to generate an email to invite participants to an event. My event is a videoconference and I need to generate a password to allow the access to this videoconference.

My email contains the link of the conference, its date and time (with DATE and TIME tags). I have also included an INPUT tag in order to specify a password.

It would be great if QuickText could automatically generate the password, so that I do not even have to specify a password.

**Comment by SamuelPlentz** [comment]
Have a look at the community script [GeneratePassword](https://github.com/jobisoft/quicktext/wiki/Script:-GeneratePassword).

**Comment by isamuse2** [comment]
Brilliant! Many thanks.
