### ISSUE TITLE
Lines of text pile on top of each other

### ISSUE THREAD

**Issue by ThunderBirdPractitioner** [thundernest/quicktext#354]
Hello, I find that when I am creating messages using my quiktext auto fill in headers, the text lines in the body of the emails I attempt to type pile on top of each other. I just tested trying the same thing (typing out a long line of text until the thunderbird moves to the next line beneath the first line of text) in a regular new message without any of my quiktext headers and it did not appear to have this issue. At the moment, it appears that my quiktext headers shift the format of the bodies of the emails, and I am at a loss because no matter how I attempt to edit the text the lines are still piled onto each other. I have attached an example of this issue as a photo where the messed up lines are visible. Any guidance is greatly appreciated.

![Capture](https://github.com/jobisoft/quicktext/assets/136463626/f3f5f0da-caf3-4628-a9a7-535c9faac1f0)

**Comment by SamuelPlentz** [comment]
I cannot reproduce it.

Could you please:
1. Send the full text of the template you are inserting as code.
2. Specify if your template is inserted as TEXT or HTML
3. Send the full sourcecode of the email before inserting the template
4. Send the full sourcecode of the email after inserting the template

When sending text ensure that these code-ticks ``` are above and below your Text.

**Comment by SamuelPlentz** [comment]
````
1. Full text of the template
```
Test this is a test email for a reddit post on the subreddit thunderbird, I am trying to display my issue, where once one line of text is full, the automatic line, that fills in underneath is scrunched up and beneath the first line.
```

2. The template is inserted as text.

3. Sourcecode of the email before inserting the template
```
<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <font face="Times New Roman, Times, serif"><font size="2"><b>Example
          header</b></font><br>
      <br>
      <font size="4"><b>Example slogan</b></font><br>
      <b>Example Address</b><br>
      <br>
      <br>
    </font>
  </body>
</html>
```

4. Sourcecode of the email after inserting the template
```
<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <font face="Times New Roman, Times, serif"><font size="2"><b>Example
          header</b></font><br>
      <br>
      <font size="4"><b>Example slogan</b></font><br>
      <b>Example Address</b><br>
      <br>
      Test this is a test email for a reddit post on the subreddit
      thunderbird, I am trying to display my issue, where once one line
      of text is full, the automatic line, that fills in underneath is
      scrunched up and beneath the first line.<br>
    </font>
  </body>
</html>
```
````

**Comment by SamuelPlentz** [comment]
I think you fiddled with your font settings here.

You should not be able to reproduce in a fresh profile. See: https://github.com/jobisoft/quicktext/wiki/Troubleshooting

**Comment by ThunderBirdPractitioner** [comment]
> I think you fiddled with your font settings here.
> 
> You should not be able to reproduce in a fresh profile. See: https://github.com/jobisoft/quicktext/wiki/Troubleshooting

Thank you so much for your help, it seems that somewhere along the way I the line spacing for the body text was altered to 50%, adjusting it to 100% has seemingly solved the issue.
