### ISSUE TITLE
 Please make QuickText available on Thunderbird trunk/daily builds (Tb 116,0a1)

### ISSUE THREAD

**Issue by PeterLairo** [thundernest/quicktext#356]
I love and depend on your great add-on **QuickText**. I also couldn't wait to try out Thunderbird's new UI, so I installed the **Daily/Trunk** version.

On 24 May 2023 you thankfully made QuickText compatible with the trunk/daily builds Tb 115,0a1 (see  #347).

For some reason, Thunderbird recently increased its trunk/daily version number from 115 to **116** (mine now is "116.0a1 (2023-06-26) (64-bit)"). Unfortunately, that made QuickText impossible to install. 

**Could you please make QuickText available on the current 116.0a1 Daily/Trunk releases... again?**

Perhaps just create an unofficial unsupported test version with the max. Tb-version bumped up to 116.0aX. :-)

![image](https://github.com/jobisoft/quicktext/assets/6554639/77c374f8-f7f0-4ed1-9ac3-34000bb7b4bb)

Thank you!

**Comment by jobisoft** [comment]
I currently do not have the resources to support Beta/Daily.

**Comment by PeterLairo** [comment]
> I currently do not have the resources to support Beta/Daily.

Hi @jobisoft 

I totally understand. No support needed. 

I'm just asking for a **_copy_** of the current version of QuickText that merely has its **max-version bumped** up to whatever the current trunk version is. 

If it works, great! If it doesn't, or even causes Thunderbird to crash and burn, just put a simple **disclaimer** by the download button (e.g. "Caution: Using this unsupported and experimental version of QuickText might cause Thunderbird to stop working. It might even cause the loss of your data."). As a Tb trunk user/tester, I (and likely many trunk users) am more than willing to live with that risk in order to be **able** to use your awesome add-on. ;-)

Either way, I thank you for this great add-on!

Sincerely,
Peter Lairo

**Comment by jobisoft** [comment]
Oh, you can do that on your own. Just take the most recent version (the xpi file) rename it to *.zip, unpack it, change the value, pack it again and rename it to *.xpi again. I will not do that to not at all give the impression I have tested it.

**Comment by PeterLairo** [comment]
> Oh, you can do that on your own. Just take [...]

Thanks you for taking the time to tell me how to change the max-version on my own. I also thank you for providing the most clear, comprehensive, and concise instructions I've seen in a very long time. Awesome!

**Comment by jobisoft** [comment]
You may have seen https://github.com/jobisoft/quicktext/issues/371, which will fix the root cause of this issue.

**Comment by SamuelPlentz** [comment]
I added a small information and instruction in the wiki here:
https://github.com/jobisoft/quicktext/wiki/Support-Thunderbird-non%E2%80%90ESR,-beta-or-daily-channel%3F
