### ISSUE TITLE
Quicktext disappeared

### ISSUE THREAD

**Issue by Muecke2000** [thundernest/quicktext#359]
Hello,

I am using the newst Thunderbird 102.12.0 and the newst Quicktext addon version 5.6.
But the Quicktext menu is completly disappeared. I cannot use this addon since more than 3 months.

How can I solve the problem?

Regards
Muecke

**Comment by SamuelPlentz** [comment]
Can you have a look here: https://github.com/jobisoft/quicktext/wiki/Troubleshooting
