### ISSUE TITLE
How to indicate Mr. or Mrs.

### ISSUE THREAD

**Issue by StephaneBRT** [thundernest/quicktext#360]
Hello,
I'm trying to find out how to indicate Mr or Mrs depending on the email recipient.
Ex:
Jane DOE = Mrs DOE
John DOE = Mr DOE
Is this possible?
Thank you,
Have a nice day.

**Comment by SamuelPlentz** [comment]
Without an address book, where you define a custom greeting for everyone this is not possible.

For ```Jane``` and ```John``` it might be clear, but for example the name ```Alex``` could be male or female. Beyond such ambiguous examples categorizing names is still a hard problem.

When using an address book you could for example use the field ```nickname``` and fill in ```Mrs Doe``` and ```Mr Doe```. You have to do this for every contact. Afterwards you could use the ```nickname``` variable in your greeting.

**Comment by StephaneBRT** [comment]
I understand that it's difficult to determine gender on the basis of a first name alone.
I like your solution with the nickname. I'll give it a try.
Thank you very much for your explanations.
Have a nice day.
