### ISSUE TITLE
Computability with latest Thunderbird Beta

### ISSUE THREAD

**Issue by Prashantsavaj3975** [thundernest/quicktext#365]
Dear Sir

I wanted to inform you that your Add-on Quicktext is Showing not Compatible for Thunderbird version 117 beta 1 released August 2, 2023.

Request to Please make to available & Help in Development of mozilla Thunderbird.

**Comment by jobisoft** [comment]
I currently do not have the resources to support Beta versions. I try my best, but cannot give you an ETA.
