### ISSUE TITLE
New Version....

### ISSUE THREAD

**Issue by pitm2000** [thundernest/quicktext#368]
Wann erscheint eine neue Verston für TB115..... aktuell mit FIX #363 ? 

danke schon mal fürs lesen

----------------------------------------------------------------------------------------------

When will a new Verston appear for TB115..... currently with FIX #363 ?

thank you for reading

thx

**Comment by jobisoft** [comment]
[quicktext_5_7.zip](https://github.com/jobisoft/quicktext/files/12333498/quicktext_5_7.zip)

Please check if this version fully works. If no negative feedback, I will publish it end of this week.

**Comment by pitm2000** [comment]
Bei Installation auf neue Version 5.7 werden die AKTUELLEN Einstellungen 
(Vorlagen und Skripte) nicht übernommen

Auch ein IMPORT einer Sicherungskopie 5.6 wird nicht eingespielt !

WINDOWS 10

TB 115.1.0 64 BIT

Auch werden beim Verfassen Neuer Mails die QuickText Vorlagen nicht 
Angezeigt siehe Bild1

-----------------------------------------------------------------------------------------------------------------------------------------

When installing on the new version 5.7, the CURRENT settings (templates 
and scripts) are not adopted Even an IMPORT of a backup copy 5.6 is not 
imported! WINDOWS 10 TB 115.1.0 64 BIT Also, when composing new mails, 
the QuickText templates are not displayed, see Figure 1







BILD1

--

**Comment by pitm2000** [comment]
Nach Neuinstalation TB115 und Quicktext 5.6 +1 gehts 
nun aber noch ein Fehler gefunden
der Zähler geht nicht .... 
es kommt << undefined >>
Skript :  [[COUNTER]]  

mfg
---------------------------------------------------------------------------------------------------------------------------------
After reinstalling TB115 and Quicktext 5.6 +1 it works
but now found an error
the counter doesn't work...
it comes << undefined >>
Script : [[COUNTER]]

Kind regards

**Comment by jobisoft** [comment]
I have not released a fix for your findings yet. What version did you install? What is "Quicktext 5.6 +1"? Thanks!

**Comment by pitm2000** [comment]
[quicktext_5_7.zip](https://github.com/jobisoft/quicktext/files/12333498/quicktext_5_7.zip)

**Comment by jobisoft** [comment]
I found the issue, why templates are not loaded. Please first revert back to v5.6 (official release version), check your settings and then update to this version:

[quicktext_v_5_8.zip](https://github.com/jobisoft/quicktext/files/12377069/quicktext_v_5_8.zip)

Does it work as expected?

**Comment by paleo74** [comment]
I've just updated quicktext on Mac OS TB 102.14, no change: CLIPBOARD still doesn't work.
