### ISSUE TITLE
[[CLIPBOARD]] in Thunderbird 102 not working after update to 5.8 

### ISSUE THREAD

**Issue by au7oma7** [thundernest/quicktext#372]
After auto update to QuickText 5.8 under Thunderbird 102 [[CLIPBOARD]] function ceased to work - output is empty. I reverted manually to ver 5.6 and it is working fine.

**Comment by jobisoft** [comment]
Could be that 5.8 only works in TB115. Could you check for us?

**Comment by au7oma7** [comment]
I can confirm this issue on multiple machines with Windows 10 and Thunderbird 102.
I don't have acces to any machine with Thunderbird 115, I tested it myself and dumped it as soon as I realized it sucks.

**Comment by ttcc-gh** [comment]
I can confirm, QT 5.8 [[CLIPBOARD]] does not work in TB 102 but in TB 115!

**Comment by Madydri** [comment]
I can confirm, QT 5.8 Last Updated 18 août 2023 [[CLIPBOARD]] does not work anymore in TB 102.14.0

**Comment by jobisoft** [comment]
This should again work in 102 and 115:
[quicktext_5_9.zip](https://github.com/jobisoft/quicktext/files/12462887/quicktext_5_9.zip)

Does it work for you?

**Comment by au7oma7** [comment]
Version 5.9 working fine here with 102. Thank you!

EDIT. Just tested with 115, also working as expected.

**Comment by jobisoft** [comment]
Submitted to ATN.
