### ISSUE TITLE
CTRL to insert QuickTexts not working

### ISSUE THREAD

**Issue by pietpetoors** [thundernest/quicktext#373]
We always could choose between ctrl and alt keys to setup shortcuts. Now in new version it only allow me to use Alt key.
It create problem for example where I had shortcut = ctrl 6, now it uses alt 6. But when I use a special character like ALT136 it activates the Quictext shortcut.

**Comment by jobisoft** [comment]
I just tried the following environment:
- QT 5.8
- Windows 10
- Thunderbird 102.14.0 (64-Bit) [German and US locale]

I can use CTRL and use it to insert a shortcut.

![image](https://github.com/jobisoft/quicktext/assets/5830621/719388e4-e695-40f6-a1a9-fdae4898f432)

Can you give a more detailed error description? What happens if you try to select CTRL as shortcut key?

**Comment by pietpetoors** [comment]
In my Thunderbird on my server which is on version 102.15.0 it works correctly. When I open the general tab it shows the ctrl option.
![QT1-1](https://github.com/jobisoft/quicktext/assets/53491710/1b2622aa-0d98-4c80-bdd8-5676b431a26f)

On my laptop which is on 115.2.0 it do not even show that option on the general tab. See screen shot below. 
I deleted all the templates in the problem QT, un installed the plugin and re installed it. Even before I could import new templates the ctrl option does not show like in screen shot below. I then imported the templates I exported from the installation which I know is working and it remains the same.  The latop is new and everything on the laptop have been freshly installed. Neither Thunderbird nor this plugin were on the laptop before. Running latest Win11.

![Qt1](https://github.com/jobisoft/quicktext/assets/53491710/abfc4f2e-1d52-4491-aab2-de602e0cb884)

**Comment by jobisoft** [comment]
What version of QuickText are you using on your Laptop?

**Comment by pietpetoors** [comment]
5.10

**Comment by jobisoft** [comment]
That is odd. Can you create a new profile and install Quicktext without importing your saved config? Does that change anything?
