### ISSUE TITLE
The wordwrap of a new mail triggers on plugin bar Quicktext

### ISSUE THREAD

**Issue by Patrickn1988** [thundernest/quicktext#374]
When you write an email in Thunderbird in a windowed screen, the text will go outside the screen, instead going to a new line. 
This is most likely because the wordwrapper triggers on the quickbar bar? 
This happens in version 115+ of Thunderbird. 

Not sure if this is a Quicktext or Thunderbird issue.. 
Also described @ Thunderbird support 
[The wordwrap of a new mail triggers on plugin bar Quicktext](https://support.mozilla.org/en-US/questions/1422447)

**Comment by jobisoft** [comment]
I will wrap the toolbar to fix this.

**Comment by Thijn** [comment]
This change has instead introduced this issue on versions older then 115 (I'm running 102.15.0):

![image](https://github.com/jobisoft/quicktext/assets/845552/8330949e-eb02-4ef8-9f6e-933037b42f9c)

Without plugin:

![image](https://github.com/jobisoft/quicktext/assets/845552/3375a5a5-1b89-4898-802d-5521b79bf2da)


The previous version still works fine on this version of thunderbird.

**Comment by jobisoft** [comment]
[quicktext_5_11.zip](https://github.com/jobisoft/quicktext/files/12487478/quicktext_5_11.zip)

This should revert the behavior in TB102 (proper line breaks in text, but no wrapping of toolbar as before) and use the new behavior in TB115 (proper line breaks in text and button wrapping in toolbar). Can you confirm both?

**Comment by Thijn** [comment]
I can confirm 5.11 works as expected on TB102. I've got no TB115 to test it on, maybe @Patrickn1988 can test?

**Comment by Patrickn1988** [comment]
I have tested Quicktext 5.11 in Thunderbird v115.0.  It does wrap, I think this is a good solution.
Thank you for the quick response


![2023-09-01_12h12_31](https://github.com/jobisoft/quicktext/assets/143510387/e2f7b002-9d15-482b-b282-5a0bf04496d0)
