### ISSUE TITLE
After upgrading from version 102 to Supernova 115 - quicktext 5.8 not working

### ISSUE THREAD

**Issue by lukasawi** [thundernest/quicktext#375]
I had version 102, and the latest plugin. After installing Supernova 115 plugin doesn't work. Plugin options not available
![image](https://github.com/jobisoft/quicktext/assets/143593162/7c8ee380-2ff8-4f45-ace0-1e3634fa18f6)

**Comment by jobisoft** [comment]
Restart Thunderbird. Your profile looks broken by the way, TB does not support incognito mode, which means you manually fiddled with about:config.
