### ISSUE TITLE
Need Info on making QuickText compatible with Thunderbird Daily/Nightly/Alpha/Beta

### ISSUE THREAD

**Issue by PeterLairo** [thundernest/quicktext#394]
### Make QuickText compatible with Thunderbird Daily/Nightly/Alpha/Beta

It would be great if you could make QuickText compatible with Thunderbird Daily/Nightly/Alpha/Beta.

You once provided **instructions** somewhere, but I cannot find them anymore.

It was something about unzipping the XPI installation file, and then editing the `manifest.json` by changing the `strict_max_version` to whatever version of Thunderbird you are using. The code is right at the beginning of the file:

```
{
  "manifest_version": 2,
  "applications": {
    "gecko": {
      "id": "{8845E3B3-E8FB-40E2-95E9-EC40294818C4}",
      "strict_min_version": "102.0",
      "strict_max_version": "125.*"                      <--------- This
    }
  },
  "name": "Quicktext",
  "version": "5.14 (bumped to TB ver 125.*)",    <---- I added the "(bumped to..." part
```

Is that correct?

Can you please **put the instructions somewhere easy to find**, e.g.:

- Mozilla add-ons page
- PIN this post
- The GitHub main page for QuickText

**Comment by jobisoft** [comment]
These instructions just paper over the internal safeguards. The add-on needs to be adjusted to internal changes of Thunderbird in order to work. Just making it *claim* to be compatible is not a solution.

The next version released in summer 2024 will be a pure WebExtension, which does not need updates anymore.

**Comment by SamuelPlentz** [comment]
https://github.com/jobisoft/quicktext/wiki/Support-Thunderbird-non%E2%80%90ESR,-beta-or-daily-channel%3F
