### ISSUE TITLE
QT doesn't work

### ISSUE THREAD

**Issue by Zygmunto** [thundernest/quicktext#397]
QT doesn't work with Thunderbird daily 115.6.1 (64-bit) on Debian proot distro. After installation the icon of a lightning appears, it's clickable but nothing happens when clicked. What's worse there is no option in tools to manage the add-on (add templates). Reinstalled the add-on several times, the issue persists.

**Comment by mstockin** [comment]
I have the same problem here at a Win11 Citrix VM with Thunderbird 115.8.0 (32-Bit). Lightning appears, but not working and the options icon in the addon settings is grayed out. I already started Thunderbird with a new profile without luck. At another Win10 Workstation Quicktext works fine.
I already used Quicktext for years, but with new TB Versions it doesn't work at all of my machines.

**Comment by jobisoft** [comment]
Anything on the error console, which could help identify the issue?

Hamburger menu -> Tools -> Developer Tools -> Console

**Comment by mstockin** [comment]
Sorry for the late response...
The output at the console was not helpfull for me. Perhaps for you:
Uncaught (in promise) Error: An unexpected error occurred 12 undefined
    <anonym> moz-extension://50ba90b2-a419-4b9d-b8bc-47a9940143c8/background.js:91
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    <anonym> moz-extension://50ba90b2-a419-4b9d-b8bc-47a9940143c8/background.js:91
![2024-03-11_01_15_19-000009](https://github.com/jobisoft/quicktext/assets/40394213/13503891-e413-47da-8b2a-0a3f50c7f108)

**Comment by jobisoft** [comment]
I have not received any other reports besides these two. I have no idea. Sorry.

**Comment by hfc2x** [comment]
QuickText is currently broken in Thunderbird 128 (snap version). I'm using Kubuntu 24.04, and using the developer tools console, gives the output below when I click on "Insert file as text". The symptoms are the same as described on the OP, as in trying to insert a text template does nothing, even though QuickText is enabled.

```
Uncaught (in promise) NS_ERROR_XPC_BAD_CONVERT_JS: Could not convert JavaScript argument arg 0 [nsIFilePicker.init]
    pickFile chrome://quicktext/content/modules/wzQuicktext.jsm:658
    insertContentFromFile chrome://quicktext/content/quicktext.js:626
    oncommand chrome://messenger/content/messengercompose/messengercompose.xhtml:1
    insertContentFromFile chrome://quicktext/content/quicktext.js:626
    AsyncFunctionThrow self-hosted:808
    (Async: async)
    oncommand chrome://messenger/content/messengercompose/messengercompose.xhtml:1
[wzQuicktext.jsm:658]
```
