### ISSUE TITLE
Feature Request: Fallback from TO=nickname to TO=firstname

### ISSUE THREAD

**Issue by MisterPit** [thundernest/quicktext#398]
Hello,

would it be possible to implement a fallback from TO=nickname to TO=firstname if no nickname is found in the address book?

Regards

Pit

**Comment by SamuelPlentz** [comment]
Have a look at this community script: https://github.com/jobisoft/quicktext/wiki/Script:-ToNickname

**Comment by MisterPit** [comment]
Thank you Samuel,

works like a charm!

Pit

**Comment by MisterPit** [comment]
Thank you Samuel,

works like a charm!

Pit
