### ISSUE TITLE
I want to help - reordering templates

### ISSUE THREAD

**Issue by David263** [thundernest/quicktext#40]
It seems like lots of other people want the ability to sort or reorder templates within groups, a feature I remember but which no longer works. I'm willing to look at the source code and try to fix this feature, if someone can help me get started, since I have not used github before to modify code (I have an account and I have posted my own code there to make it open source). I have looked at tutorials but find them too complicated. If you are experienced and willing to answer my questions about using github, please send a message directly using my contact us page at http://www.springtimesoftware.com/contact.php . Thank you! Let's work together to get this done!

**Comment by jobisoft** [comment]
I rather use this issue to answer your questions. Go ahead! In general, you first need to fork quicktext, which creates a local copy in your own account, which you can checkout and make modifications to. After you have finished your changes, you create a PullRequest which sends your changes back here and we can accept it, so it get merged.

What OS are you on? On Windows I use github desktop to checkout my repositories, bur any other git client will do as well.
