### ISSUE TITLE
Quicktext doesn't work anymore in Thunderbird 125

### ISSUE THREAD

**Issue by Houdoe** [thundernest/quicktext#407]
Probably you know this already. However I couldn't find this under issues. Hopefully you'll find the time to fix this.

Many thanks in advance!

**Comment by jobisoft** [comment]
See https://github.com/jobisoft/quicktext/issues/411#issuecomment-2241755350

**Comment by pvdhagen** [comment]
To quote: https://blog.thunderbird.net/2024/07/welcome-to-thunderbird-128-nebula/

> Even with QA and beta testing, any major software release may have issues exposed after significant public testing. That’s why we’ll wait to enable automatic updates until we’re confident no such issues exist. At present – Thunderbird version 128.0 is only offered as direct download from [thunderbird.net](http://thunderbird.net/) and not as an upgrade from Thunderbird version 115 or earlier.

So quite a lot of people are likely to still run 115. Disabling automatic upgrades and downgrading quicktext to 5.6 is the best option.

**Comment by jobisoft** [comment]
Can you explain what you mean by that? Quicktext has been updated for Thunderbird 128. And we still support Thunderbird 115. Independent of the release for TB128, there should be no reason to downgrade Quicktext.

**Comment by pvdhagen** [comment]
After automatic upgrade to quicktext 5.15 it stopped working on my TB 115, all groups and templates are gone, new groups/templates can't be added (no error message, but no success either). So I guess that's what Houdoe reported in the first place. Not a big issue, since the downgrade is simple, but it should be documented.

**Comment by jobisoft** [comment]
OK, thanks! That has not yet been reported anywhere, and this issue seems to be completely unrelated. 

I stopped roll-out of 5.15, until I understood what is going on.

**Comment by jobisoft** [comment]
@pvdhagen : I was not able to reproduce the issue. I would like to ask you to create a new issue, stating that 5.15 does not work in Thunderbird 115 and provide a few more details:
- OS
- Thunderbird version
- error messages on the error console (CTRL + J in the main window)

Thanks!

(I have re-enabled roll-out of 5.15)
