### ISSUE TITLE
TB 128 ESR

### ISSUE THREAD

**Issue by starik1968** [thundernest/quicktext#411]
Hello, Quicktext is deactivated due to incompatibilty, what can I do?
Thanks in advance
cu
F. :-)

**Comment by SamuelPlentz** [comment]
For now - have a look here: https://github.com/jobisoft/quicktext/wiki/Support-Thunderbird-non%E2%80%90ESR,-beta-or-daily-channel%3F

**Comment by starik1968** [comment]
Thanks! Is there an official release date in the Add-On-Store in sight?

**Comment by SamuelPlentz** [comment]
@jobisoft has to provide it.
Could you confirm that an adjusted quicktext version works with 128?

**Comment by starik1968** [comment]
Tried it, changed the max version, seems to run. So I will wait for the release, maybe it will be there soone

**Comment by SamuelPlentz** [comment]
Thanks for your feedback!

**Comment by jobisoft** [comment]
Will release QT for Thunderbird 128 during the next week.

**Comment by starik1968** [comment]
Great, use it constantly, great add on.

**Comment by Heliophob** [comment]
> For now - have a look here: https://github.com/jobisoft/quicktext/wiki/Support-Thunderbird-beta-or-daily-channel%3F

When I try it this way, I don't find an xpi file, only a zip file (https://github.com/jobisoft/quicktext/archive/refs/heads/Main.zip). When I modify the manifest in it accordingly and then repack it as a new archive, TB gives me the error message that the archive seems to be corrupted.

What could be the reason for this?

**Comment by SamuelPlentz** [comment]
You will find it here: https://addons.thunderbird.net/de/thunderbird/addon/quicktext/?src=userprofile

**Comment by doctorow** [comment]
> Will release QT for Thunderbird 128 during the next week.

Thank you for this. When Quicktext broke this week, it forcibly reminded me how much I rely on your code to get by! I made a $100 donation to your fund by way of thanks. Really looking forward to this plugin coming back into the T-bird store. Thank you for your hard work and enjoy your weekend!

**Comment by axb-lists** [comment]
I have also made a € 100 donation in hope to see an update soon.
Quicktext  has been a huge part of my daily work, for many years. 
Back in the day I even purchased the Pro version

**Comment by jobisoft** [comment]
I created a preliminary release of a version compatible with Thunderbird  128.
https://github.com/jobisoft/quicktext/releases/tag/v5.15

Could you test if it works as intended?

**Comment by Martin511** [comment]
> I created a preliminary release of a version compatible with Thunderbird 128. https://github.com/jobisoft/quicktext/releases/tag/v5.15
> 
> Could you test if it works as intended?

Works for me!
Thank you!

**Comment by axb-lists** [comment]
On 7/22/24 08:10, Martin511 wrote:
>> I created a preliminary release of a version compatible with Thunderbird 128. https://github.com/jobisoft/quicktext/releases/tag/v5.15
>>
>> Could you test if it works as intended?
> 
> Works for me!
> Thank you!
> 

YESSIR!
Footer added by Qwicktext 5.15
Huge Thanks

Alex

---
Wise man sez: Always code as if the guy who ends up maintaining your 
code will be
a violent psychopath who knows where you live.

**Comment by axb-lists** [comment]
> Hello, Quicktext is deactivated due to incompatibilty, what can I do? Thanks in advance cu F. :-)

make sure you update you addons frequently

**Comment by Bumble57** [comment]
> I created a preliminary release of a version compatible with Thunderbird 128. https://github.com/jobisoft/quicktext/releases/tag/v5.15
> 
> Could you test if it works as intended?

Thanks a lot, works great!
Best regards
Christian

**Comment by fmommeja** [comment]
> I created a preliminary release of a version compatible with Thunderbird 128. https://github.com/jobisoft/quicktext/releases/tag/v5.15
> 
> Could you test if it works as intended?

Thank you so much !
Works like a charm.
Kind regards
Fred

**Comment by WiredWonder** [comment]
> For now - have a look here: https://github.com/jobisoft/quicktext/wiki/Support-Thunderbird-beta-or-daily-channel%3F

Thanks for this workaround, this addon is essential.
