### ISSUE TITLE
Feature request: Add option to paste clipboard with formatting

### ISSUE THREAD

**Issue by drkui** [thundernest/quicktext#44]
Currently when I use the "Clipboard" variable, it pastes as plain text, which doesn't keep the formatting I want. So if possible, it would be nice to have an option to paste with the formatting intact.

**Comment by SamuelPlentz** [comment]
Created pull request #183 that would solve that issue.
Depending on the template type (plain text / html) [[CLIPBOARD]] (and [[SELECTION]]) is automatically inserted as plain text / html.

**Comment by jobisoft** [comment]
thanks to @SamuelPlentz 
[quicktext_3.4pre2.zip](https://github.com/jobisoft/quicktext/files/5484001/quicktext_3.4pre2.zip)
