### ISSUE TITLE
Set the Counter to zero

### ISSUE THREAD

**Issue by Carpspb** [thundernest/quicktext#47]
Hey Guys and Coding Gurus,
I former was anQuicktext Pro user and also now using the aktual version 1.1. I am using the COUNTER feature. Every year i reseted the counter to zero by alterning the code of the file wzQuicktextVar.js (this.mData['COUNTER'].data++;
this.mData['COUNTER'].data = 0; //insertet by spb on 08.01.2018). In the old versions i was able to cope with it setting to zero. In the actual version the code has changed a little bit, I tried and failed, sadly.
Is there a possibility?, can you provide me a trick to set the counter to zero. Perhaps it is possible from insite the programm by a special script, or another solution.
I would be glad if you could help me
Carpspb

**Comment by jobisoft** [comment]
extensions.quicktext.counter

You can simply change the value of the counter in the config editor in the advanced Thunderbird settings.

**Comment by Carpspb** [comment]
Happy New, year! hope you are fine!
like last year I tried to reset my counter to zero. In the advanced Thunderbird settings I could not find the entry you mentioned. 
I would be glad if you could help me this year too.
Carpspb

**Comment by SamuelPlentz** [comment]
This setting moved from a thunderbird advanced setting to a sqlite database setting. Its located in the file `storage-sync.sqlite` located directly in your thunderbird profile.

You can use a tool like [sqlitebrowser](https://sqlitebrowser.org) to edit the settings. Create a backup before editing anything.

Open the table `collection_data` and search for this entry:
Column `collection_name`: `default/{8845E3B3-E8FB-40E2-95E9-EC40294818C4}`
Column `record_id`: `key-userPrefs`

In the column `record` it should contain something like this:
`{"id":"key-userPrefs","key":"userPrefs","data":{"counter":12345,"menuCollapse":true,"toolbar":true,"popup":true,"keywordKey":"Tab","shortcutModifier":"alt","collapseState":"1;1;1;1;1;1;1;1;1;1","defaultImport":"","shortcutTypeAdv":false},"_status":"created"}`

Change the counter value (above it is 12345) to your needs.

A non geeky way might to just delete the file. This will revert settings of Quicktext and probably also settings from other programs. Also have a look here: [Community script: CaseNumber](https://github.com/jobisoft/quicktext/wiki/Script:-CaseNumber)

**Comment by SamuelPlentz** [comment]
Btw.: I tried to solve it with a script like this:

``` Javascript
this.mQuicktext.preferences.setPref("counter", 1);
```

But this didn't work, and I don't know why.

**Comment by jobisoft** [comment]
I will come up with something clever here. Should be made possible from within the UI.

**Comment by jobisoft** [comment]
[quicktext.zip](https://github.com/jobisoft/quicktext/files/5824151/quicktext.zip)
This is v3.6b1and it adds an entry to the settings window:

![image](https://user-images.githubusercontent.com/5830621/104808733-82000280-57e8-11eb-9b45-2c31c414eb8b.png)

Does it work?
