### ISSUE TITLE
[[cursor]] tag not works if the variable is NOT at the beginning of a line

### ISSUE THREAD

**Issue by Heliophob** [thundernest/quicktext#50]
Hello,

since the last update of Quicktext the tag "[[cursor]]" works again (Yeeehaaa!). Unfortunately only if the variable is at the beginning of a line. If the variable is somewhere in the middle it does not work unfortunately and it remains in use just "[[cursor]]" there.

Example 1 (it not works):
Hello [[cursor]]

Example 2 (it works):
Hello
[[cursor]]

my system:
TB 60.2.1 (64-Bit) @ XUbuntu 18.04.1 LTS (bionic)

Best Regards

**Comment by Heliophob** [comment]
Addendum: Unfortunately, it does not always work reliably at the beginning of the line. Sometimes it works and sometimes not.

**Comment by hdokit** [comment]
It only works for me if I don't put the focus into the mail body field, e.g. when "To:" has focus.

TB 60.5.1 (64-bit) @ macOS 10.14.3

**Comment by Heliophob** [comment]
I can not confirm that.

**Comment by Heliophob** [comment]
Hello John,
why was the topic closed? The problem persists, the bug is present!
Best Regards

**Comment by jobisoft** [comment]
Because no one was able to confirm it. Also support for TB60 is gone (from my side). If the issue still exists in TB68, please create a new issue.
