### ISSUE TITLE
Add option to insert an inline image

### ISSUE THREAD

**Issue by multiwebinc** [thundernest/quicktext#52]
Original issue
~~I have an HTML template. When I go to Variables > Other > File, then select a file, which then adds, for example, `[[FILE=/path/to/kittens/fluffles.jpg]]` to the template. However instead of inserting the image into the email, it inserts the text `ÿØÿà` (the text is the same no matter what image I choose).~~

~~Tested on Thunderbird 60.2.1 (64-bit) on Ubuntu Linux with Quicktext 1.2.~~

I was mistaken about the above functionality. I assumed it would insert images inline, but I just noticed in the wiki that it only inserts the contents of a text file. Therefore, as a feature request, I suggest adding the option to add an inline image. This would be useful, for example, when making a business signature and including your company's logo and your photo. I can add an attachment, which would kind of work, however I don't know how to reference the `Content-ID` header for that attached file in the template.

**Comment by multiwebinc** [comment]
For anyone reading, here is a work-around, however it requires the image be stored directly in the quicktext XML file, which may not be ideal since the file size will grow if the images are large, however will make the XML file including the images portable:

1.    Compose a new email (must be new, not a reply).
2.    Click Insert > Image and choose the image you want to insert.
3.    Format the message how you want the template to be.
4.    Push Ctrl-A to highlight all text.
5.    Click Insert > HTML.
6.    Copy everything in that box. To select all push Ctrl-A. Close that window.
7.    Click Tools > Quicktext and go to the template you want to edit or add a new template. (Note: the template must be set to insert HTML, not plain text.)
8.    Paste what you copied.
9.    Save and close

**Comment by jobisoft** [comment]
Thanks for providing a work around. This issue is now pinned.

**Comment by IgitBuh** [comment]
May I suggest to make this functionality more accessible to users?
Variables > Other > Image
Opens up a dialog where a jpg/jpeg/png/gif file can be selected and is then inserted as a base64 encoded img tag into the editor.

**Comment by jobisoft** [comment]
Can you contribute code?

**Comment by IgitBuh** [comment]
Not for now, but maybe in the near future.
I'm currently moving to Thunderbird and trying to set up everything as I need it. Quicktext is actually a really great help, so I'm honestly interested in contributing something here. I've never written code for TB or FF, but I don't think this will hold me back.
But for the moment, I'd simply like to document the issues I stumble across.

**Comment by jobisoft** [comment]
This is now possible with the new IMAGE tag.
