### ISSUE TITLE
Customize Toolbar missing Quicktext icon 

### ISSUE THREAD

**Issue by ovari** [thundernest/quicktext#55]
Quicktext icon not showing in 'Customize Toolbar'. Please see image below

![image](https://user-images.githubusercontent.com/17465872/53006281-06c13500-3489-11e9-897c-7fde2faa4ab3.png)

If pointers are required, perhaps the author of the Mail Redirect add-on can assist as this situation has since been fixed.

Linux Mint 19.1 Cinnamon 64-bit
Thunderbird 60.5.1

Thank you

**Comment by jobisoft** [comment]
Fixed by Christian Schneider. Will be released as v1.5

**Comment by jobisoft** [comment]
released:
https://addons.thunderbird.net/de/thunderbird/addon/quicktext/

**Comment by ovari** [comment]
Thank you for fixing this issue.

![image](https://user-images.githubusercontent.com/17465872/57131560-18577f00-6de0-11e9-9994-f4aaf0553ee2.png)

Will the icon be changed from color to no color, for consistency with Thunderbird?

Thank you once again.
