### ISSUE TITLE
Please enable Quicktext Statistics Dashboard on ATN

### ISSUE THREAD

**Issue by ovari** [thundernest/quicktext#56]
Please enable Quicktext Statistics Dashboard on ATN
https://addons.thunderbird.net/en-US/thunderbird/addon/quicktext/statistics/?last=30

What do you think @jobisoft?

Thank you

**Comment by jobisoft** [comment]
@lieser 

Am I allowed to do that? Do we want that?

**Comment by lieser** [comment]
Allowing all to view on ATN the consolidated statistics of the add-on should not have any negative effect on the privacy of add-on users. So from my side there is nothing speaking against enabling it.

**Comment by jobisoft** [comment]
Done.
