### ISSUE TITLE
Feature request: Add keyboard shortcuts (accessKey)

### ISSUE THREAD

**Issue by ovari** [thundernest/quicktext#57]
1. Add accessKey to items in the menu bar, i.e. File, Help. Also extend this to the sub-menus
1. Add accessKey to the buttons, eg Export, Import, Close
1. Add accessKey to the checkboxes, eg View Quicktext-menu on right-click
1. Add accessKey to the text box, eg Import on startup

![image](https://user-images.githubusercontent.com/17465872/53155721-c17c3f00-3611-11e9-8284-6c1a3c9412fa.png)

What do you think?

Thank you

**Comment by jobisoft** [comment]
Can you contribute?

**Comment by ovari** [comment]
> Can you contribute?

Unfortunately not.

**Comment by chrisschnei** [comment]
Looking at the attribute opens up two implementation options.
1. Hardcoding the access keys into the xhtml code. This would result in a common access key assignment for all languages.
2. By moving the access keys to each language specific DTD file there is the possiblity to define application language dependent access keys.
What are your thoughts regarding the two options? Which one should be chosen?
I would propose the second language specific option to be implemented.

**Comment by ovari** [comment]
> I would propose the second language specific option to be implemented.

Yes,  some examples of the conversion en → hu
1. _Save → _Mentés
2. _Help → _Sugó
