### ISSUE TITLE
“Mail Merge” add-on support

### ISSUE THREAD

**Issue by ovari** [thundernest/quicktext#60]
What is the best way forward to enable the Quicktext add-on to support the “Mail Merge” add-on?
https://addons.thunderbird.net/addon/mail-merge/

Thank you

**Comment by jobisoft** [comment]
As MailMerge is the sending party it must check if quicktext is installed before creating the final emails from the draft. If quicktext is installed, it must invoke its replacement methods. With upcoming TB78 next summer and strict enforcement of sandboxed WebExtensions, I do not see how that will be possible.

Nothing I can do.
