### ISSUE TITLE
How to get the from email adres ?

### ISSUE THREAD

**Issue by deef73** [thundernest/quicktext#61]
Hi all,

Becausse I'm working with different users and domains I need a image depending on the from email adress.   I am not a scripter so I don't know anything about javascript.

I need the From email to get the domain 

I found this in the quicktekst script

`quicktext.insertVariable('FROM=email')`

So I'm googeling :)

`var email = this.mQuicktext.mData['FROM'].data[email];
return email;  // not working :(
quit;

if (email =="info@domain1.be") 
  var website_url = "domain1.be";
else if (email == "info@domain2.eu")
  var website_url = "domain2.eu";
else if (email == "info@domain3.com")
  var website_url = "domain3.com";

return (website_url.email);`

Can someone learn me some Javascript :)  Or help me out with this script please :)

Cheers,

Deef

**Comment by jobisoft** [comment]
what you need is
```
let email = this.mQuicktext.get_from(["email"]);
```
To dump it into a alert box for debug

```
this.mWindow.alert(this.mQuicktext.get_from(["email"]));
```

**Comment by jobisoft** [comment]
I also updated the wiki to provide this info:
https://github.com/thundernest/quicktext/wiki/Script-support#advanced-usage

**Comment by ShargAA** [comment]
I have a similar problem. 
How to write an email in the field: To?
Does not work: this.window.document.getElementById('msg TO').value = '123@df.ru';
Does not work: this.quicktext.get_to(["email"]).value =  '123@df.ru';

Please help!

**Comment by SamuelPlentz** [comment]
Please don't cross post your problems.
See the answer here: #178
