### ISSUE TITLE
Install QT1.5 under TB56

### ISSUE THREAD

**Issue by menych** [thundernest/quicktext#68]
I am trying to install QT1.5 under TB56. 
I have other addons that stopped running with TB57+, so upgrading TB is out of the question.
I'm not even mentioning how ugly the latest versions of FF/TB are.
I tried to rename xpi to zip and replaced 60. with <em:minVersion>52.0</em:minVersion> in the install.rdf, and then zipped it back and renamed to back to xpi. 
Unfortunately, I'm getting the "This add-on could not be installed because it appears to be corrupt."
Is there a way to get the newer versions of QT to work with older versions of TB?
Thanks,

**Comment by jobisoft** [comment]
TB56 is unsupported and we strongly encourage you to not use such an old version. I know that the Add-On situation is difficult but many Add-Ons did receive an update or have been superceeded by a replacement Add-On.

We do not have the resources to backport QT. Sorry.

**Comment by menych** [comment]
56 is a massive upgrade for me. I've been sitting on 42 for years—until today, when I realized that there was some development in QT. I had issues adding a gmail account so I temporarily upgraded to the new version. And then basically went back to the last one that could support my existing workflow. Truth be told, I can do with 42 or 56. If 67 were noticeable faster and didn't have the 30-second freezes all the time, I would have considered switching, but I see the same behavior regardless of the version. But I have close to 400,000 emails weighing over 55GB, so it's the price I pay. In fact, QuickText is the #1 reason why I stick with TB.

PS I'm still on FF56 as well because of the addons. I only use FF because of the addons. For everyday browsing, I use Chrome.

**Comment by jobisoft** [comment]
It may be worth setting up a new profile in TB60 and setup up everything again instead of using an old profile, in case you did that. I think the mail storage Format has improved and is faster now.

Do not use TB beta for production work.

**Comment by epsso** [comment]
I have a similar amount of email, both numbers and size and experienced the freezes that you are talking about and other major issues.  To alleviate these issues I archive my mail off-line by year and try to keep less than 10K messages in any one imap folder.  Once I started that approach, the issues disappeared.  I am on TB60 and use QT every day.  Searching for very old emails can be a pain if I don't know what year it was sent it but I don't have to do that very often.  Archiving is easy in that I create a saved search for mail that is older than a year and then use the archive function to move all the old messages to a local folder structure.

**Comment by jobisoft** [comment]
I also use the internal archive function to move old emails out of imap. For me the internal global search also searches the archives and I do not need to know the year. That does not work for you?

**Comment by epsso** [comment]
The global search works for me but when searching the full body is it very slow when searching over large volumes of email.  Therefore, if I know the year the email was sent/received, I can speed up the search significantly.
