### ISSUE TITLE
Want offer the new function: Language Detect

### ISSUE THREAD

**Issue by DENLOK** [thundernest/quicktext#69]
Hello
I have finished one addition for QuickText: very useful function for international mailing. But sorry, I am a newbie on GitHub, not understand how to add my version of QuickText to the existing project here. If anyone will be interested and can add this update to the GitHub main project, I will be glad.
I marked this QuickText version as "1.5d".
The function is analogue of TheBat addon "LangSelector" that working very poor in TheBat.

[QuickText + LangDetect v1.5d.zip](https://github.com/thundernest/quicktext/files/3293256/QuickText.%2B.LangDetect.v1.5d.zip)

This function can search in the original sender's message the local language symbols and detect the message as "English or Not (only) English", then inserts from your template only the PART (half) of text according with the language detected.

This function works for next already preSetted "local" LangCodes and their languages:
CH - Czech, Slovak, and Slovenian
DE - Deutch
ES - Spain
FR - France
GR - Greece
PL - Poland
RO - Romanian
RU - Russian
TR - Turkish

FORMAT OF TEMPLATE:
Your Template must be formatted as 2 parts of text: 
part 1 (always upper half of template) - your text translated on International language (ENGLISH) - normal for international messaging.
part 2 (always lower half) - your original text writed on your local language.
Between of these 2 parts must be placed a special strong sequence of symbols named Separator:
`***[xx]***`
- where "xx" is your language Code for proper detect the language of original sender's message.
If you don't see your language in this list, you can add your language by yourself. 
Just put your local language symbols between the '[' and ']' of Separator signature. 
Example: 
for German lang, the Separator may looks as `***[DE]***  or  ***[öäüÖÄÜß]***`
or for Greek lang the Separator may looks as: `***[GR]***  or  ***[α-ωΑ-Ω]***`

Example for QuickText template by the Editor window:

Hello
This is your text translated to the International Language, it is always ENGLISH.
Bla-bla-bla here is yor text on English.

Here is your End Sign: 
With best regards, forever yours.
`***[RU]***`
Здравствуйте

Это ваш исходный текст письма на русском или другом локальном языке.
Здесь продолжение вашего текста, бла-бла-бла.

Здесь Ваша подпись:
Всего наилучшего, всегда Ваш.

Method of detectoion:
The function prepare the text of answer message visible in the window of editor. It remove all empty strings, then delete 1st string with info "2019/05/11 ... you wrote:", just because this string is not by original source message of sender. Then it leave only first 500 symbols of message body because the message may have very long "history" and contains other non actual symbols. If will be found 10 or more symbols by charset of "Separator" language, the function inserts the BOTTOM half (with local language) of text by your template. In other cases will be inserted the upper half of your template (default English).

After this update of QuickText, I am is glad to DROP MY "TheBAT!" to Trash Can and start using again the Thunderbird Mail.
Hope, it will be useful for anyone too!

**Comment by jobisoft** [comment]
Hi Denlok,

I would need to ask you, to send in a Pull Request. I do not have the time to manually pick the changes from your file.

However, I just updated Quicktext for Thunderbird 68 and those changes are still pending review. It would probably result in merge conflicts, if you send in your changes now. So I would like to ask you to wait until this Pull Request has been accepted by the Thunderbird Council.

https://github.com/thundernest/quicktext/pull/70

Now how do these Pull Request work? You first need to fork the Quicktext repository:
https://help.github.com/en/articles/fork-a-repo

Then you have your own copy of Quicktext in your github account, where you can make any change you want. When you are done, you need to send the changes back to us, which is called a "Pull Request":
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

To reduce the possibility of so called merge conflicts, I would suggest to fork the Quicktext repository only after the currently pending Pull Request has been merged.
