### ISSUE TITLE
Feature request: Add links to template text

### ISSUE THREAD

**Issue by MLyons10** [thundernest/quicktext#71]
It would be incredibly helpful if we could add links to text so that this populates automatically.

This would actually save a TON of time...

Thank you for an awesome add-on and I hope this is a feature that would be doable!  :)

**Comment by jobisoft** [comment]
Isn't this what you are looking for?
https://github.com/thundernest/quicktext/wiki/List-of-all-supported-tags#url

**Comment by jobisoft** [comment]
Can I close this?

**Comment by MLyons10** [comment]
I'm sorry that it took me so long to get back to you, I missed the response.

I tried using those tags for URL and it doesn't appear to do what I'm trying to do.  Unless I am completely missing something.

So, if I have a sentence like this:

"Please refer to OUR WEBSITE"

Where the words in CAPS would be a link to the website, I would do it like this?

"Please refer to [[URL=https://mywebsite|OUR WEBSITE]]"

Correct?  

When I try using this template however the link never shows up.

Sorry if I'm missing something.  But all I want to do is include links in the templates so that I don't have to do it every time.

Thank you again for all of the work you do on this awesome addon!

**Comment by jobisoft** [comment]
Hm, I have not understood your request. 

The URL tag is inserting content from a remote source, like a database lookup or something like that. 

Do you just want to have a "clickable" link in your template? So you want to add some text via quicktext to your email and in that text, there is a link and you want that link to be an actual link, not just plain text?

**Comment by jobisoft** [comment]
I think this boils down to a usability issue. You can simply add the url to the template as text. When such an url is part of an email text, the receiving email client will display it as a clickable link. Try it. Send yourself an email with some text and an url to your website. When you receive it, you can click on it.

**Comment by jobisoft** [comment]
Also, if you want to add a link whose displayed text differs from the link, you can do that as well by using html:

![grafik](https://user-images.githubusercontent.com/5830621/70067999-7acf6280-15ef-11ea-9821-754da62aa14c.png)
