### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by stepand76** [thundernest/quicktext#73]
There is an encoding issue in version 2.1. If I create a template with non-ascii characters (czech in my case) and reopen TB then these characters are broken. 

QuickText 2.1
Thunderbird 68.0b2, 32bit (czech).
Windows 10, 64bit (czech)

**Comment by johndoe7000** [comment]
I can confirm this issue with german umlauts also - screenshot attached.

Quicktext 2.1
TB 68.0, 32bit
Windows 8.1 Pro, 64bit

![grafik](https://user-images.githubusercontent.com/35802969/63846692-955cc480-c98c-11e9-86fd-066efc9ad1ff.png)

**Comment by BuzzDausBerlin** [comment]
same here
Quicktext 2.1
TB68.0, 32 bit
Windows 10

**Comment by jobisoft** [comment]
Being investigated.

**Comment by twobaker** [comment]
Same problem here, also import/export will break characters

**Comment by sbaum** [comment]
Same problem here (running TB68 on Kubuntu Linux). By looking at the code I think the problem could be located in the try-block after [line 625 of wzQuicktext.jsm](https://github.com/thundernest/quicktext/blob/pro/chrome/content/modules/wzQuicktext.jsm#L625). The comment at that line reads:

> //Try to interpret the file as UTF and convert it to a Javascript string.
> //If that failes, the file is probably not UTF and the ISO-Latin-1
> //fallback is used instead.

That could be the problem we are seeing here.

**Comment by jobisoft** [comment]
Can you send me your quicktext config files, so I can reproduce the issue here 1 to 1? My email address is listed on my main github page. Thanks!

**Comment by jobisoft** [comment]
@sbaum : Your observation is correct. If I add a ``Components.utils.reportError(e);`` into the catch (which I should do always) I get the following error, which was hidden before:

converter.convertFromByteArray is not a function

Investigating ...

**Comment by jobisoft** [comment]
Can you guys try this version:
[quicktext.zip](https://github.com/thundernest/quicktext/files/3560614/quicktext.zip)

**Comment by johndoe7000** [comment]
It works for me! Thank you very much.
I've also tested export/import successfully.

**Comment by BuzzDausBerlin** [comment]
works!

**Comment by jobisoft** [comment]
Sending it for review to ATN now.

**Comment by twobaker** [comment]
Thanks, perfect!

**Comment by jobisoft** [comment]
https://addons.thunderbird.net/de/thunderbird/addon/quicktext/versions/?page=1#version-2.3
