### ISSUE TITLE
Can't create template

### ISSUE THREAD

**Issue by charliegc4** [thundernest/quicktext#76]
With Thunderbird 69.0b2 (64bit) and QuickText 2.1 an old issue we had has resurfaced: you cannot create a template.

When you have finished editing and click Save, nothing happens.

Can't create Groups either.

**Comment by jobisoft** [comment]
Not compatible. I need to update max_version to 68.*. Once TB68 ESR is out, I will update quicktext for TB69

**Comment by charliegc4** [comment]
69 recognizes it a compatible and installs it. Would be good to have the max version sorted so it does not install then. Thanks John.

**Comment by jobisoft** [comment]
Max version is now 68.*
