### ISSUE TITLE
QuickText doesn't work on TB 69 Beta 1

### ISSUE THREAD

**Issue by stepand76** [thundernest/quicktext#77]
I use QuickText 2.1 but it is not compatible with TB 69 Beta 1. Could you please update it? Thanks.

**Comment by jobisoft** [comment]
I do not know yet, if I will update Quicktext for non ESR versions, as this will take a lot of time. Independent of that, I will not update Quicktext to anything beyond TB68 ESR, before that has been released.

**Comment by jobisoft** [comment]
I will not update to betas. No time.
