### ISSUE TITLE
standard xml import on startup broken

### ISSUE THREAD

**Issue by BuzzDausBerlin** [thundernest/quicktext#78]
Hi, I'm using a standard.xml that is imported on startup on all my machines.
Since I've updated to TB 68, this function appears to be broken.

Quicktext 2.1
TB68.0, 32 bit
Windows 10

**Comment by jobisoft** [comment]
Define broken: Doing nothing at all or wrong encoding? 

I fixed the encoding issue, can you try if this also fixes this issue?
https://github.com/thundernest/quicktext/issues/73#issuecomment-526650183

**Comment by BuzzDausBerlin** [comment]
Doing nothing at all. If I try to import my  original xml, automatically or manually, nothing happens. If I create a new set and export this, I can reimport it (but with broken encoding).

edit: shall I send you my xml for testing?

**Comment by jobisoft** [comment]
1. With the new version posted in my comment, is the encoding issue fixed?
2. Yes, please send me your file, which is not loaded properly.

**Comment by BuzzDausBerlin** [comment]
1. will check later
2. email sent

**Comment by BuzzDausBerlin** [comment]
works with the new version, thanks!
