### ISSUE TITLE
Problem with TB 68.0 and Quicktext 2.1

### ISSUE THREAD

**Issue by michael2024** [thundernest/quicktext#80]
After upgrading to TB 68.0 keywords often don't work after a line break. In case a space is inserted before the keyword, than the keyword will be replaced by the text.

**Comment by jobisoft** [comment]
Can you send me your quicktext config file, so I can reproduce your issue? Via email?

**Comment by shaunss** [comment]
I have the same problem (TB 68.0 running on MacOS 10.14.6). Keywords expand at the start of a line if they are in the first line of a new mail document or if there are only empty paragraphs above. But they do not expand at the beginning of a line if lines above contain text. In this case they only expand behind a space.

**Comment by jobisoft** [comment]
Can you send me your quicktext config file, so I can reproduce your issue? Via email?

**Comment by ximum** [comment]
Same here (TB 68.0 w. Quicktext 2.3 on Win10), keywords only work at the beginning of line only behind a space. 
- making new templates doesn't help
- changing activation key doesen't help

Do you still need the files for testing - which file should it be - template.xml?

**Comment by twobaker** [comment]
Same here. Interesting: When I change the activation key, it works sometimes for one shot.

**Comment by ghost** [comment]
same here (TB 68.0 on Mac 10.14.6).

**Comment by michael2024** [comment]
Hi John, 
is any solution to this already foreseeable? It would be great to get a fix soon. Your work on this is highly appreciated. Thanks

**Comment by alie2n** [comment]
I just want to chime in on this. Somehow the hotkey for replacing keywords does not work as expected.
I just tested the workaround with the space in front of the keyword and this does indeed work here.

**Comment by michael2024** [comment]
I think the problem is in quicktext.js, function editorKeyPress, line 748 where spaces are searched. After a line break there is no space between the last word of the previous line and the first word (= keyword) of the current line. Therefore keywords at line start are not replaced. 
A quick and dirty bug fix could be to copy lines 748 to 786 and paste after line 786. Line 748 should then be changed to "if ((foundRange = finder.Find("[[RETURN]]", wholeRange, startRange, endRange)) != null)". Hence, two searches are performed, which is an ugly solution but seems to work...

**Comment by michael2024** [comment]
Forgot to mention that the second "if ((foundRange..." should be an "else if"

**Comment by michael2024** [comment]
Forgot to mention that the second "if ((foundRange..." should be "else if" to avoid processing the keyword twice.

**Comment by jobisoft** [comment]
I am currently supporting Philippe to fix Cardbook to work with Nextcloud again with TB68 (Error 503). The fix I worked on last week seems to work (version 42) but it still needs some tweaks. After that is done, I will look at this.

@michael2024 : Thanks for your research!

**Comment by jobisoft** [comment]
ok, cardbook is fixed. 

Now, how do these keywords work? As no one has send me any template files, I need to create one by myself. What do I need to do?

**Comment by schoettl** [comment]
Wait, I send you one via mail.

**Comment by michael2024** [comment]
I also sent you a template file.

**Comment by jobisoft** [comment]
I was able to reproduce the issue now. Thanks. Looking into it.

**Comment by jobisoft** [comment]
What an ugly piece of code, but I think I fixed it. Wanna give it a try?

[quicktext_2.4.zip](https://github.com/thundernest/quicktext/files/3664413/quicktext_2.4.zip)

**Comment by schoettl** [comment]
Oh.. thanks for fixing it! It seems to work now.

**Comment by jobisoft** [comment]
Uploaded to ATN, waiting for review

**Comment by jobisoft** [comment]
Reviewed.

**Comment by twobaker** [comment]
Thanks a lot! It's working again
