### ISSUE TITLE
Where to set the [[COUNTER]]- Keyword -Startvalue?

### ISSUE THREAD

**Issue by Carpspb** [thundernest/quicktext#82]
Hey you,
I just installed my thunderbird on a new computer and of course again: Quicktext (proud user since 2013!!))
On my old computer i used the COUNTER in every email I sent.
I know from a older version of quicktext that it is somewhere possible to alter/set the COUNTER-Startvalue manually.
Please help me

Thank you
holzman

**Comment by jobisoft** [comment]
In the Thunderbird advanced setings:

`extensions.quicktext.counter`

if that key does not exists, create it as Integer value.
