### ISSUE TITLE
[Script]How do I set the TO email?

### ISSUE THREAD

**Issue by GermanCreator** [thundernest/quicktext#83]
Currently, I take the TO-Contents and use them in my email, like [[TO=email]]. But the email should not go to the TO-recipient, but to someone else. In fact, the TO-recipient should not even get a copy of the email.

How do I **set** the TO email?

**Comment by jobisoft** [comment]
https://github.com/thundernest/quicktext/issues/17#issue-332249175

I will try to add a general option to add headers, follow the other issue to be updated on this matter.
