### ISSUE TITLE
[[CURSOR]] does not work reliably

### ISSUE THREAD

**Issue by Heliophob** [thundernest/quicktext#85]
Hello,

The cursor function does not work as expected even after a Thunderbird Upate (68.1.1). The problem still exists. Here I had already described the problem once. It was closed, because the error in the current TB version allegedly no longer occurs...:

2019/01/18:
https://github.com/thundernest/quicktext/issues/50

Best Regards

**Comment by jobisoft** [comment]
Someone who has this bug needs to fix it. I cannot see it :-(

**Comment by Heliophob** [comment]
okay I understand!
Unfortunately I do not have the necessary knowledge :-/

**Comment by jobisoft** [comment]
[quicktext.zip](https://github.com/thundernest/quicktext/files/3752442/quicktext.zip)

This version of quicktext has debug output to the console. Open the console (CTRL+SHIFT+J) and set the filter to "CURSOR LOG". What do you get, when it works, and when it does not work?

![grafik](https://user-images.githubusercontent.com/5830621/67234393-56576680-f445-11e9-9126-50474aa1de96.png)

**Comment by Heliophob** [comment]
Unfortunately, I do not get "CURSOR LOG" output in the debug console.

**Comment by jobisoft** [comment]
To install the test version:
 - uninstall the current installed version
- restart
- check if the addon is really uninstalled
- restart again
- install test version

Just to make sure.

**Comment by Heliophob** [comment]
I proceeded as described and uninstalled QuickText and then reinstalled the latest version (2.4). Even now, I have no outputs in the debug console. A "test-version" is not available to me.

It all looks like searching for "[CURSOR]" before pasting. When first inserted, "[CURSOR]" remains in the text and will not be jumped to. If I insert the same text again, the first inserted "[CURSOR]" will be jumped on and also the tag removed. The last inserted "[CURSOR]" stands still.

**Comment by jobisoft** [comment]
You do use the test version I posted here:
https://github.com/thundernest/quicktext/issues/85#issuecomment-544657484

Right?

**Comment by Heliophob** [comment]
oh, sorry! I did not see that! Test version installed. Log is as follows:
![Bildschirmfoto_2019-10-23_08-51-11](https://user-images.githubusercontent.com/46809800/67366121-2a3a0380-f573-11e9-8fd3-c94582fc4391.png)

**Comment by jobisoft** [comment]
So there is no difference. Here you have a new test version, which reports debugs output at some later time. 

[quicktext.zip](https://github.com/thundernest/quicktext/files/3761555/quicktext.zip)

The console should look like this:

![grafik](https://user-images.githubusercontent.com/5830621/67380605-e652f880-f58a-11e9-959d-29844d452348.png)

**Comment by Heliophob** [comment]
With the new test version, the bug is now no longer present (while short testing). I'll try this and I'll report.

Many thanks!

**Comment by jobisoft** [comment]
what? I did not change anything. Or at least i think so. I still need the debug output to understand the issue and I still need your help with further test versions to understand this :-)

**Comment by Heliophob** [comment]
Naturally! I will continue to help. I just wanted to test for a few days if the problem is really gone or if it is temporary.
![Bildschirmfoto_2019-10-23_12-31-48](https://user-images.githubusercontent.com/46809800/67384314-39c84500-f591-11e9-854d-4d92b976ca26.png)

**Comment by Heliophob** [comment]
Hello John, 
With the test version provided the error has not recurred during intensive use until today.
Best Regards

**Comment by jobisoft** [comment]
Depending on debug strings being printed to delay the process is of course not the right way to fix this. 

I have a new version, where I actually retry to find the tag until it has been found. After each failed attempts, he will wait a bit longer: (failedAttempts*5)+1 ms. It will stop after 10 failed retries.

I had to change some internals for that to work, so I ask you to test this version a few weeks.

[quicktext.zip](https://github.com/thundernest/quicktext/files/3793491/quicktext.zip)

Please install this new version again as described here:
https://github.com/thundernest/quicktext/issues/85#issuecomment-544985447

**Comment by jobisoft** [comment]
That version also prints debug strings, but this version does not depend on them. You will see, how many retires where needed:

![grafik](https://user-images.githubusercontent.com/5830621/67943174-ca2e0780-fbd9-11e9-9415-815d119b70c6.png)

**Comment by Heliophob** [comment]
okay, installed! In a short test it was now evident that up to 3 attempts were required!

**Comment by jobisoft** [comment]
On my system it jumps between 1 and 2. Do you actually see the cursor tag for a split second, before it gets removed?

**Comment by Heliophob** [comment]
Yes it is. For a very short moment i can see the tag.

**Comment by jobisoft** [comment]
ok, here is another version, which reduces the delay to 2ms per retry, which should reduce the delay time to a minimum (and not wait longer than needed). 

[quicktext.zip](https://github.com/thundernest/quicktext/files/3797619/quicktext.zip)

How many retries does it need on your system?
Do you still see the tag before it gets removed?

**Comment by jobisoft** [comment]
And another version, this includes the fix for issue #84.

[quicktext.zip](https://github.com/thundernest/quicktext/files/3797842/quicktext.zip)

So now we have these questions:

How many retries does it need on your system?
Do you still see the tag before it gets removed?
Does Clipboard work again?

**Comment by Heliophob** [comment]
in most cases, only one attempt is required. Sometimes it takes two or three attempts. In one case, it was 4 attempts. The clipboard works again! 

Thank you very much!

**Comment by jobisoft** [comment]
ok, that version is avail at ATN already.
