### ISSUE TITLE
Javascript read .txt files and get output

### ISSUE THREAD

**Issue by kelzared** [thundernest/quicktext#86]
Hey,

i try maybe 1 week to get with Quicktext a text of a .txt file on E:/test.txt with "Hello" but i dont get a result after 30 scripts and trys... have an idea or a solution? I despair soon :S

and the next problem is, i cant calc with Javascript in Quicktext.. is not supported or ? :o

i hope anyone can help me :\

regards
Chris

**Comment by jobisoft** [comment]
show me your scripts

**Comment by jobisoft** [comment]
If you want help, you need to show me your scripts, otherwise I will close this.
