### ISSUE TITLE
TB70

### ISSUE THREAD

**Issue by Paroparo13** [thundernest/quicktext#87]
I would be appreciative if anybody could make Quicktext being compatible with TB70. Thank you very much for your help in advance.

**Comment by sclg** [comment]
... or even with TB68

**Comment by jobisoft** [comment]
TB68: It is. Why so mean?
https://addons.thunderbird.net/de/thunderbird/addon/quicktext/

TB70: not from my side.

**Comment by sclg** [comment]
Many thanks.
A manual update fixed it
