### ISSUE TITLE
provide 2 decimal places for attachment size in MB

### ISSUE THREAD

**Issue by Carpspb** [thundernest/quicktext#88]
Dear professionals,
I wondered years and months if the following is possible:

In Quicktext Menu: Variable--> Attachement-->filenameAndSize please provide 2 decimal places for attachments with MB sizes
I think it is in this file:
quicktext/chrome/content/modules/wzQuicktextVar.jsm 
In row 1016: niceFileSize: function(size)
In row 1025 please add Math.round/(size*100)/100.00;
dont know if it is right, you certainly know it better.

A secondt tweak could be that if there are more than one attachment file, the attachmentfiles could come in unter each other in new rows, or sseparated with commas an space

It would be nice, thank you.

**Comment by jobisoft** [comment]
[quicktext_2.5.zip](https://github.com/thundernest/quicktext/files/3746442/quicktext_2.5.zip)

Does that work as expected?

**Comment by Carpspb** [comment]
Hi John,

I tested your update with several files / filesizes. Here the result:
fenrn_2019.ics (2.41 kB), wzQuicktextTemplate.jsm (2.45 kB), wzQuicktextVar.jsm (34.49 kB), Fluarte.png (1008.24 kB), a.txt (1 B), Fleiscd.skp (4.07 MB), Fler EP.layout (11.61 MB) 
It seems to work perfect.
Thank you 🥇 -))

**Comment by jobisoft** [comment]
Avail on ATN.
