### ISSUE TITLE
Update for TB 68.1.2 - Linux, Kubuntu

### ISSUE THREAD

**Issue by Kozoroh74** [thundernest/quicktext#89]
Hi, thanks for plugin, after upgrade Kubuntu, resp. TB on 68.1.2 plugin is not working.
Is possible update it. 
Thank You very much.
K.

**Comment by jobisoft** [comment]
It works even with 68.2. What error do you get?

**Comment by Kozoroh74** [comment]
Hi, sorry, it was a mistake to reinstall thunderbird. Addons works. Thank you
