### ISSUE TITLE
Script Tab is missing

### ISSUE THREAD

**Issue by Track77** [thundernest/quicktext#9]
Script Tab is missing

![snap_2018 05 19_12h36m11s_001_quicktext settings](https://user-images.githubusercontent.com/2233954/40267196-727a6534-5b61-11e8-8c83-cdf9c1a9084a.png)

Thanks!

**Comment by jobisoft** [comment]
The version including script tag is not yet released. Will not take long.

**Comment by jobisoft** [comment]
The wiki is a little ahead :-) But this is all happening right now. After the pending pull request is done, it will be send to Mozilla for final review. Probably as version 1.0.

**Comment by Track77** [comment]
Glad to hear this.
Again thanks for most useful Thunderbird's plugin!
