### ISSUE TITLE
Oh no! Thunderbird 68.2.1 (32 bit) update kills QuickText

### ISSUE THREAD

**Issue by buybeach** [thundernest/quicktext#92]
Just when I thought I could safely update this email client, they killed QuickText compatibility (again). Anyone knw a work-around?

**Comment by jobisoft** [comment]
just update your addons.

**Comment by buybeach** [comment]
Thanks! Sounds idiot proof but apparently not to me. Bless you for taking the time to reply. Of course, you'd think that that would be a suggestion on the "add on" page where the software announces that an add-on is "incompatible" rather than sort-of hidden in a drop-down menu.

**Comment by jobisoft** [comment]
Yeah, that is a sad bug in Thunderbird, which did notget fixed. But you did find it now, right? So we can close this issue?

**Comment by buybeach** [comment]
Yes, thank you so very much.
