### ISSUE TITLE
Problem with Import on startup 

### ISSUE THREAD

**Issue by KevinGade** [thundernest/quicktext#95]
I'm trying to centralize management of our Quicktext templates and use the "Import on startup" function. The xml file is located on a Windows AD share. I can manually import the same file for all users however when I insert the path to the file in import on startup, click save and restart TB, the field is just empty if I open Quicktext settings again. 

I have searched and tried everything I could think of but it seems to me that this function doesn't work anymore?

TB version: 68.2.2
Quicktext version: 2.6

Best Regards,
Kevin

**Comment by jobisoft** [comment]
I cannot confirm this:

![grafik](https://user-images.githubusercontent.com/5830621/70061705-0d1e3900-15e5-11ea-9988-6f857a2da34a.png)

Works like a charm. 

Do you see anything on the console? 
Is the path entered correct?
Remove any leading/trailing space.
Multiple files need to be seperated by ; and again no spaces anywhere.

How did you generate the to-be-imported files, maybe they are corrupt? Try to generate new ones for testing by exporting again from the current version of quicktext.

**Comment by jobisoft** [comment]
I will close this as invalid, if no further feedback.
