### ISSUE TITLE
Not working after 68.3.0 update

### ISSUE THREAD

**Issue by Vanko0045** [thundernest/quicktext#98]
It does not work after 68.3.0 update. You cannot add any text to an email. Uninstalling and installing did not help.

**Comment by floeff** [comment]
It seems related to yesterday's release of QuickText - for me, neither Autotext nor adding text by shortcut is working. Had the problem before 68.3.0 as well.

**Comment by psevd0** [comment]
Same problem in 68.2.2
I wrote a separate bug report a couple of minutes later than this.

**Comment by seebronn** [comment]
The addon is great, my most favorite for thunderbird. But after updating the addon and Thunderbird it doesn't work any more. Please fix, thanks a lot.

**Comment by jobisoft** [comment]
Released an updated version v2.8 to fix the issue. Just update your addons.

**Comment by Noebian** [comment]
had the same problems. The new version works for me. thank you.

**Comment by DE2019-tb** [comment]
works. thanks!

**Comment by filiplajszczak** [comment]
Had the same problem. Update to 2.8 fixed it.

**Comment by KnutDerKahlschlagg** [comment]
Updated version works perfect, thanks a lot, man.
Love this plugin, saves me hours of typing or copy &  paste...
