### ISSUE TITLE
The add-on stopped working after updating to version 2.7

### ISSUE THREAD

**Issue by psevd0** [thundernest/quicktext#99]
Hello!
After upgrading to version 2.7, the add-on stopped working - neither keyboard shortcuts nor clicking on menu items of templates work.
I tried to reinstall both Thunderbird and the add-on itself - there is no effect.
I am attaching a screenshot from debugging (though I don’t know if it is correct or not).
![изображение](https://user-images.githubusercontent.com/58505788/70124575-262af680-1686-11ea-9b49-a2e29581c3e0.png)

**Comment by floeff** [comment]
Confirming the problem, same here on macOS with TB 68.3.0 and the previous TB release.

**Comment by chrgan** [comment]
I also can confirm this, TB 68.3.0 on Windows 10.

BTW, I love this add-on, thanks for the work!

**Comment by fmommeja** [comment]
Hi, same here with this message:
![image](https://user-images.githubusercontent.com/19188155/70127152-bd8a4c80-167a-11ea-8cb0-bf1522ccc092.png)

Which means: "XML parsing error: undefined entity
Location: chrome:///quicktext/content/settings.xul
Line number 112, Column 27"

MacOS 10.14.6 - TB 68.3.0 (same with previous version)

**Comment by MarcKrikke** [comment]
We have the same issue with W10 TB 68.2.2 (32bit)
If you go into de addon all is there, but you can't use it nothing shows up.

**Comment by sigbertklinke** [comment]
I can confirm the problem with TB 68.2.1 (64bit) & Quicktext 2.7 under Ubuntu 18.04.3 LTS.

**Comment by DE2019-tb** [comment]
Confirming the problem, same here on macOS with TB 68.3.0

**Comment by wkrawczak** [comment]
> I can confirm the problem with TB 68.2.1 (64bit) & Quicktext 2.7 under Ubuntu 18.04.3 LTS.

Same here - same versions.

**Comment by jobisoft** [comment]
[quicktext_2.7.1.xpi](https://github.com/thundernest/quicktext/files/3921361/quicktext.zip)

Can you retry with this version?

**Comment by wkrawczak** [comment]
@jobisoft This works, thanks :)

**Comment by floeff** [comment]
Works for me. There's another bug still though, that if I use the Tab for autocomplete, there's one tab added to the text, since recent versions.

Instead of

"Yours truly," it is "Yours truly,     "

Can file a new issue if required

**Comment by jobisoft** [comment]
It was due to a flaw in the new header feature and it would die if you did NOT use it. I of course tested only WITH the new header tag. Sorry.

**Comment by jobisoft** [comment]
@floef Yes new issue please

**Comment by MarcKrikke** [comment]
Will all updates use the 'new' version now?

**Comment by jobisoft** [comment]
Yes, all users will automatically get v2.8, either today or tomorrow.
